### ISSUE TITLE
godep doesn't complain when building with the wrong language version

### ISSUE THREAD

**Issue by shutej** [tools/godep#101]
I have coworkers who have `go1.2` and who try to build a package that specifies `go1.3` in Godeps.  This results in a compile error vs. godep barfing with a version mismatch warning.

**Comment by freeformz** [comment]
This is maybe something we should report on when working on #273, but generally I agree. Closing.

**Comment by shutej** [comment]
I didn't mean it should control the version of Go, I meant it should *check* the version of Go and either warn or fail.  Otherwise why even bother storing it in the `Godeps.json`?

**Comment by freeformz** [comment]
@shutej it's primarily for other systems to know which version of go to select to build the code.

Ultimately godep will **not** be involved in building code. My plan is to deprecate `godep go ... ` after Go 1.6 and remove it around Go 1.7. Once Go 1.6 is released people should switch to using `vendor/` (this is possible now, but requires an ENV variable), which is supported by the `go` tool directly.
