### ISSUE TITLE
Best practice for specifying dependencies on tools

### ISSUE THREAD

**Issue by joeshaw** [tools/godep#104]
One issue I've had with godep is trying to figure out how best to specify dependencies on Go packages that are not imported by my Go code.  For instance, command-line tools that generate Go code, like github.com/jteeuwen/go-bindata/go-bindata, github.com/joeshaw/rst-extract, and code.google.com/p/gogoprotobuf/{proto,protoc-gen-gogo,gogoproto}.

Is there a way to specify these in godep, and what is it?  An update to the README for this use case would be very helpful.

**Comment by freeformz** [comment]
IMO these things are outside the scope of godep. You can't import a main package anymore starting with Go 1.5. If you vendor the code and have the go tools around you can still install it. So I'm going to close this. Thanks!
