### ISSUE TITLE
A way to install godep securely, hashable/pinning

### ISSUE THREAD

**Issue by edulix** [tools/godep#110]
I like godep because it allows me to install dependencies securely, specifying the hash of each dependency. But I need a way to bootstrap that. go-lang is installed in my system using a package manager like apt, but to install godep from an official source I have to use "go get github.com/tools/godep", which is not very secure. Couldn't you do releases and package them, so that we can download and unpack them and install them in GOPATH for bootstraping?

I'd like to be able something like:
$ mkdir gopath; cd gopath; wget http://path/to/godep-rev.tar.gz
$ [ "$(sha512sum godep-rev.tar.gz)" == "whateverhash" ] && tar zxf godep-rev.tar.gz || echo "Invalid tarball"
$ export GOPATH="$(pwd)"
$ then use godep

**Comment by kr** [comment]
Where would you get "whateverhash" from, and why should it be any more trustworthy than the code you can get directly from https://github.com/tools/godep/archive/master.tar.gz? (Or from 'go get', which also uses https on github.)
