### ISSUE TITLE
feature request: a way to run in an environment with just the component + its godeps

### ISSUE THREAD

**Issue by vito** [tools/godep#115]
"godep go ..." prepends the Godeps to the `$GOPATH`, which potentially hides problems (e.g. new packages that aren't dep'd in but exist in the outer `$GOPATH`).

It would be nice to be able to run with a more locked down `$GOPATH` that has *just* the component and its dependencies.

One idea: symlink the project into its own Godeps; this way a single `$GOPATH` can be used, containing just `$PWD/Godeps/_workspace`. This may be tricky if you don't know what the package's own import path is, but in basic manual testing it gets the job done.

**Comment by freeformz** [comment]
Closing in favor of #273
