### ISSUE TITLE
│godep: directory "XXX/GoProjects/src" is not using a known version control system

### ISSUE THREAD

**Issue by jonbonazza** [tools/godep#116]
I am trying to run godep save from within my package and I am getting the error in the title.

Here is some information:

My GOPATH envvar is set to "XXX/GoProjects"

My directory structure looks like this under GOPATH:

```
bin/
pkg/
src/
    proj1/
          .git/
          ...
          main.go        #all files in this project are in package main
      proj2/
          .git/
          ...
          proj2.go   #all files in this project are in package proj2 (matches parent dir).       
```

I can execute all the go tools fine, even go list.

the output of __go list -json__ is (modied a bit for security purposes):
```json
{
	"Dir": "XXXX/src/proj1.git",
	"ImportPath": "proj1.git",
	"Name": "main",
	"Doc": "blah",
	"Target": "XXXX/bin/proj1.git",
	"Root": "XXXX",   #matches GOPATH
	"GoFiles": [
		"handlers.go",
		"main.go",
		"util.go"
	],
	"Imports": [
		"crypto/tls",
		"crypto/x509",
		"encoding/base64",
		"encoding/json",
		"flag",
		"fmt",
		"goku.git",    # our own library
		"io/ioutil",
		"log",
		"net/http",
		"os",
		"path/filepath",
		"regexp",
		"strings"
	],
	"Deps": [
		"bufio",
		"bytes",
		"compress/flate",
		"compress/gzip",
		"container/heap",
		"crypto",
		"crypto/aes",
		"crypto/cipher",
		"crypto/des",
		"crypto/dsa",
		"crypto/ecdsa",
		"crypto/elliptic",
		"crypto/hmac",
		"crypto/md5",
		"crypto/rand",
		"crypto/rc4",
		"crypto/rsa",
		"crypto/sha1",
		"crypto/sha256",
		"crypto/subtle",
		"crypto/tls",
		"crypto/x509",
		"crypto/x509/pkix",
		"encoding",
		"encoding/asn1",
		"encoding/base64",
		"encoding/binary",
		"encoding/hex",
		"encoding/json",
		"encoding/pem",
		"errors",
		"flag",
		"fmt",
		"github.com/rcrowley/go-metrics",
		"github.com/rcrowley/go-tigertonic",
		"goku.git",
		"hash",
		"hash/crc32",
		"io",
		"io/ioutil",
		"log",
		"log/syslog",
		"math",
		"math/big",
		"math/rand",
		"mime",
		"mime/multipart",
		"net",
		"net/http",
		"net/textproto",
		"net/url",
		"os",
		"path",
		"path/filepath",
		"reflect",
		"regexp",
		"regexp/syntax",
		"runtime",
		"runtime/cgo",
		"runtime/debug",
		"sort",
		"strconv",
		"strings",
		"sync",
		"sync/atomic",
		"syscall",
		"time",
		"unicode",
		"unicode/utf16",
		"unicode/utf8",
		"unsafe"
	],
	"TestGoFiles": [
		"handlers_test.go",
		"proj1_test.go",
		"util_test.go"
	],
	"TestImports": [
		"crypto/tls",
		"crypto/x509",
		"crypto/x509/pkix",
		"github.com/stretchr/testify/assert",
		"github.com/stretchr/testify/mock",
		"github.com/stretchr/testify/suite",
		"net/http",
		"net/url",
		"testing"
	]
}
```
No idea what is going on here. I saw in another (already closed) issue that this is how the directory structure should look, so I am obviously doing something else wrong.

**Comment by ddo** [comment]
It's golang/tool/vcs.FromDir error, it should be return package dir path instead of the golang root src.
So please make sure all of your dependencies are under code version control(git, etc...)

**Comment by ahmetalpbalkan** [comment]
:+1: this is really annoying.

**Comment by TannerMoore** [comment]
Since this is still open, I thought I would explain how I fixed this issue.  For me it was because I had various test programs sitting in my $GOPATH/src folder. The error message was saying the whole src folder didn't have a known version control system, but what it meant was there were some projects within that folder that weren't being tracked by github. I pulled them out briefly (they were only there to test the socket communication of the projects I actually cared about) and was able to successfully run

    godep save -r ./...

**Comment by tnolet** [comment]
My builds are now failing because of this. I can run

```
godep save -r ./...
```

without error, but `godep restore` still gives:

```
godep: unable to detect version control system for code.google.com/ path
```

**Comment by rberger** [comment]
Suddenly having this problem with all our go projects that use godep.

All our repos and dependencies have a .git or .hg in them (I.e. they have been VCS initialized/installed)

Help!

**Comment by rberger** [comment]
Figured it out.

Remove any entries that are from code.google.com from your `Godeps/Godeps.json` file. They should have moved to another repo as code.google.com is shutting down.

**Comment by osiloke** [comment]
I just updated godep to e28aafa1c4a9ab9108ae98211f12bbcc43e24510. This seems to spit out more useful information that actually tells you what repo isn't using a vcs.

**Comment by abhat** [comment]
+1. I am trying to import some of the Kubernetes' pkgs in my go project. I did a git clone of the Kubernetes repository and updated GOPATH to be: /home/abhat/gocode:/home/abhat/gocode/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/

Here are the errors that godep save -r spews out.

https://gist.github.com/abhat/0503971bbf9d2a4e6a7f

Am I missing something?

**Comment by freeformz** [comment]
@abhat Don't modify the GOPATH like that. Wrap the go commands with godep: e.g. godep go install ...

**Comment by freeformz** [comment]
I'm going to close this as we now indicate which repo isn't using a VCS.

**Comment by abhat** [comment]
@freeformz +1. For posterity, I was missing a 'godep restore step' on the Kubernetes clone before calling 'godep save'.

**Comment by freeformz** [comment]
@abhat I really wish Kubernetes rewrote their deps so the restore and a few of their other dev bits wouldn't be necessary.

**Comment by themihai** [comment]
I'm using git and I still get this error. The path reported is the Go source directory, it's not even GOPATH.

bash-3.2$ git status
On branch master
nothing to commit, working directory clean
bash-3.2$ godep save
godep: dirty working tree: /Users/myuser/go/src/comp.io/dev
godep: directory "/Users/myuser/go/src" is not using a known version control system
godep: dirty working tree: /Users/myuser/go/src/comp.io/hamux/errors
godep: dirty working tree: /Users/myuser/go/src/comp.io/tools/evm
godep: directory "/Users/myuser/gosrc/src" is not using a known version control system
godep: error loading dependencies

**Comment by freeformz** [comment]
@themihai `godep version` ?

**Comment by least-olegs** [comment]
In my project we don't use separate repositories for some other our projects, which are nevertheless linked to the main project.

Is there any way to avoid having to deal with VCS at all? Why is this even needed?

**Comment by freeformz** [comment]
@least-olegs godep requires the commit sha / tag of the version of the code that it is copying. Without that info there is no way for godep to help you manage your dependencies.

**Comment by least-olegs** [comment]
@freeformz I might be totally misunderstanding the purpose of this tool then. I wasn't after managing dependencies, I wanted to discover them (as in package X inadvertently introduced dependency on package Y by importing package Z, which in turn imports... and so on). Is this something that godep is supposed to do?

**Comment by themihai** [comment]
@freeformz there doesn't seem to be any --version flag. The git head is 58d90f262c13357d3203e67a33c6f7a9382f9223

**Comment by freeformz** [comment]
@themihai `godep version`

**Comment by freeformz** [comment]
@least-olegs godep does analyze all of your source code to determine which deps are in use and then copies those deps from $GOPATH into `vendor/` (or, for older versions of Go, `Godeps/_workspace/src`).

**Comment by freeformz** [comment]
@themihai that is a super old version, so am not surprised you are having issues.

**Comment by least-olegs** [comment]
@freeformz Would it be possible then to skip the version control check and the copying step? I'm only interested in analysis.

**Comment by binary132** [comment]
AFAICT, this issue happens when one of your dependencies is not under _ITS OWN_ version control.

The problem I'm facing is that we use one monolithic repository for *all of our code*, so saving deps from inside one project, referring to another project in the tree, is impossible, since all the projects are simultaneously version-controlled.

😭

**Comment by freeformz** [comment]
@binary132 I'm not sure how you are using godeps then? It's really meant to be run at the top level of a repo. Maybe I should enforce that? Or will need to make tests to exercise other use cases.

**Comment by binary132** [comment]
It's a bit of a conundrum for me as well.  I think we're going to fall back to simply copying things by hand into a vendor path.  It's like this:

```bash
# .git folder in 'core'
core/common/src/go/
# - in 'go': a build script, a readme, and a script to set GOPATH, and then under 'go'....
src/proj1/...
src/proj2/...
# so proj1 main.go is $GIT_ROOT/common/src/go/src/proj1/main.go
# proj1, proj2 also have external deps
```

I'd probably want to run `godep` in `$GIT_ROOT/common/src/go` with GOPATH set to `$GIT_ROOT/common/src/go:$GOPATH`, and then any deps not in the first piece of GOPATH would be searched for in the next GOPATH segment.

**Comment by binary132** [comment]
I noticed a number of blog posts about this exact topic.  It seems to be a pattern some people use.

**Comment by freeformz** [comment]
That's a very unusual workspace (https://golang.org/doc/code.html#Workspaces). If you are going to check a $GOPATH entry in, why not just git subtree your deps into your tree instead?
