### ISSUE TITLE
Exclude _workspace on GitHub

### ISSUE THREAD

**Issue by nathany** [tools/godep#121]
Using one of these or having _workspace added will remove that code from the language statistics on GitHub:
https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml#L58

I don't know that it will remove vendored code from diffs though. :frowning: 
Worth a shot?

Generated code is removed from diffs, but this isn't really generated code.
https://github.com/github/linguist/blob/master/lib/linguist/generated.rb

**Comment by kr** [comment]
Note, we are currently waiting on github/linguist#2017.

**Comment by nathany** [comment]
Though it wouldn't help if paths became internal/github.com/...

**Comment by kr** [comment]
> Though it wouldn't help if paths became internal/github.com/...

Yeah, I was thinking about that recently.
We'll cross that bridge when we come to it.

**Comment by kr** [comment]
The fix is live on github as of a few hours ago. :tada:
