### ISSUE TITLE
Bridge file (internal_test.go) doesn't seem to be built when running tests

### ISSUE THREAD

**Issue by gsalgado** [tools/godep#125]
I've setup a project of mine to use godep and it's working fine except that one of the packages in that project uses an internal_test.go bridge file to make private bits available to tests, and when I run the tests they fail because the names defined there can't be found. This obviously works as expected (i.e. tests pass) when I'm not using godep.

To reproduce:

 1. git clone https://github.com/monetas/btcwallet
 2. cd btcwallet
 3. git checkout godep
 4. godep go test ./waddrmgr

salgado@delgadito.../godep-test/btcwallet (godep) $ godep go test ./waddrmgr
 _/tmp/godep-test/btcwallet/waddrmgr_test
waddrmgr/common_test.go:71: undefined: waddrmgr.TstSetScryptParams
waddrmgr/manager_test.go:1016: undefined: waddrmgr.TstReplaceNewSecretKeyFunc
waddrmgr/manager_test.go:1021: undefined: waddrmgr.TstResetNewSecretKeyFunc
waddrmgr/manager_test.go:1039: tc.manager.TstCheckPublicPassphrase undefined (type *waddrmgr.Manager has no field or method TstCheckPublicPassphrase)
waddrmgr/pool_test.go:274: undefined: waddrmgr.RunWithReplacedCryptoKeyScript
waddrmgr/pool_test.go:360: pool.TstExistsSeries undefined (type *waddrmgr.VotingPool has no field or method TstExistsSeries)
waddrmgr/pool_test.go:423: pool.TstPutSeries undefined (type *waddrmgr.VotingPool has no field or method TstPutSeries)
waddrmgr/pool_test.go:443: manager.EncryptWithCryptoKeyPub undefined (type *waddrmgr.Manager has no field or method EncryptWithCryptoKeyPub)
waddrmgr/pool_test.go:447: manager.EncryptWithCryptoKeyPriv undefined (type *waddrmgr.Manager has no field or method EncryptWithCryptoKeyPriv)
waddrmgr/pool_test.go:452: undefined: waddrmgr.TstValidateAndDecryptKeys
waddrmgr/pool_test.go:452: too many errors
FAIL	_/tmp/godep-test/btcwallet/waddrmgr [build failed]
godep: go exit status 2

**Comment by freeformz** [comment]
Project maybe no longer uses godep, so closing because I can't repro.
