### ISSUE TITLE
Should I commit _workspace?

### ISSUE THREAD

**Issue by hurrymaplelad** [tools/godep#131]
Fuller question [on StackOverflow](http://stackoverflow.com/questions/26334220/should-i-commit-godeps-workspace-or-is-godeps-json-enough).

I'm confused whether I should commit Godeps.json, _workspace, both, or it's up to me.  Whatever the answer, we should update the docs to clear it up.  This paragraph under [Getting Started](https://github.com/tools/godep#getting-started) was particularly confusing:

> This will save a list of dependencies to the file Godeps/Godeps.json, and copy their source code into Godeps/_workspace. Read over its contents and make sure it looks reasonable. Then commit the file to version control.

**Comment by IvanMalison** [comment]
The fact that the official way to manage dependencies is to commit the whole _workspaces directory deeply offends my sensibilities. Its really hard for me to imagine a good reason for this. It seems like the dependencies should be part of a submodule at the very least to keep the repo history clean.

Also the comment/issue from heroku buildpack is gone. It would be great if the README explained the rationale for thsi practice.

**Comment by mariokostelac** [comment]
That way is called vendoring so please watch https://www.youtube.com/watch?v=c3dW80eO88I (Dave Cheney on reproducible builds) and try to think about that again. I also thought it's stupid, now I think different (keep in mind that there is no real package provider like `npm` or `cargo` that would keep packages there forever).
