### ISSUE TITLE
Confusing behavior when updating only one package from a repository

### ISSUE THREAD

**Issue by edsrzf** [tools/godep#138]
Say my command package `C` depends on two packages in the same repository: `pkg/A` and `pkg/B`. I'm using godep to manage the dependency.

I make a change to `pkg/A` and then want to update `C`'s dependency on `pkg/A`, so I run `godep update pkg/A`. I get the output:

    godep: no packages can be updated

I didn't understand this until I dug into the source and realized that this behavior seems to be intentional and there's even a test for it. Eventually I figured out that I could run `godep update pkg/...` and get the result I wanted.

My theory for why godep works this way: I only asked to update `pkg/A`, but doing that would require updating the whole repository, which would also mean updating `pkg/B`. But I didn't ask for that! So godep does nothing.

Technically it would be possible to depend on two different revisions of the same repo, but it would be complicated and I don't need that.

### Questions

1. Is this intended behavior?
2. Is my theory for why it's intended correct?
3. Can we consider a more helpful error message?

**Comment by schmitch** [comment]
Current I can't update sub packages too.

my Godeps.json looks like that:
```
		{
			"ImportPath": "stash.envisia.de/envisia/libs/auth",
			"Rev": "ac02a7d3a7edba3d42fc51eb06cac2fdcb1206dc"
		},
		{
			"ImportPath": "stash.envisia.de/envisia/libs/client",
			"Rev": "ac02a7d3a7edba3d42fc51eb06cac2fdcb1206dc"
		},
		{
			"ImportPath": "stash.envisia.de/envisia/libs/config",
			"Rev": "ac02a7d3a7edba3d42fc51eb06cac2fdcb1206dc"
		}
```

if i just use godep update without anything I get something like that happens when i added ```godep gopath```:

```godep: directory "/Users/schmitch/go/src/stash.envisia.de/envisia/crm/Godeps/_workspace/src" is not using a known version control system```

**Comment by freeformz** [comment]
Closing in favor of #86, which I believe is the same thing.
