### ISSUE TITLE
godep does not skip "testdata" folders when enumerating Go packages.

### ISSUE THREAD

**Issue by shurcooL** [tools/godep#140]
See the relevant code in [save.go#L293](https://github.com/tools/godep/blob/754ee6f4e0e5fc8d0ef2692fb239d15c7a09dd84/save.go#L293):

```Go
if c := w.Stat().Name()[0]; c == '.' || c == '_' {
	// Skip directories using a rule similar to how
	// the go tool enumerates packages.
	// See $GOROOT/src/cmd/go/main.go:/matchPackagesInFs
	w.SkipDir()
}
```

But `$GOROOT/src/cmd/go/main.go:/matchPackagesInFs` in Go 1.3.3 has:

```Go
// Avoid .foo, _foo, and testdata directory trees, but do not avoid "." or "..".
_, elem := filepath.Split(path)
dot := strings.HasPrefix(elem, ".") && elem != "." && elem != ".."
if dot || strings.HasPrefix(elem, "_") || elem == "testdata" {
	return filepath.SkipDir
}
```

Notably, it skips the "testdata" folder. `godep` should do the same. The "testdata" folder is sometimes used to have invalid .go code files (e.g., for testing the Go parser) and other such things inside, which may prevent otherwise valid Go packages from working with `godep`.

The behavior of `go` tool skipping "testdata" folders has been recently documented, see https://codereview.appspot.com/148170043.

**Comment by shurcooL** [comment]
This issue prevents godep from working in some cases:

```bash
$ godep save
godep: Godeps/_workspace/src/golang.org/x/tools/go/loader/testdata/badpkgdecl.go:1:34: expected 'package', found 'EOF'
```

It should not be reading .go files inside testdata folder!

**Comment by shurcooL** [comment]
There's a PR #166 that fixes it, can it be merged please?

**Comment by shurcooL** [comment]
There's a PR #166 that fixes this issue, can it be reviewed and merged please?

**Comment by neurogeek** [comment]
I just pushed a fix to ignore testdata directories. Thanks @shurcooL for bringing this up!

**Comment by shurcooL** [comment]
For reference, this issue was resolved in commit bb418303c7e0886d29a75b5bbec49b64cdc3fa1c, not closed as "wontfix".

(As a side note, if you had used one of the [supported keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) like "resolves", "fixes" or "closes", that would've been clearer. "addresses" is not one of the supported keywords.)

**Comment by pierrre** [comment]
`testdata` directories are useful if you want to run a dependency's tests.

**Comment by freeformz** [comment]
This is why I suggest that we change the behavior to just skip parsing of testdata directories and copy them as is.

**Comment by neurogeek** [comment]
Yes, I'm working on a better fix. I'll send it out for review in the next couple of days.

**Comment by freeformz** [comment]
@neurogeek Awesome. Thanks!
