### ISSUE TITLE
godep get fetches dependencies unnecessarily

### ISSUE THREAD

**Issue by edsrzf** [tools/godep#141]
`godep get x` fetches all x's dependencies as `go get x` would, even when they aren't needed since all x's depencencies are vendored with godep.

**Comment by slimmy** [comment]
> Also, godep restore fails without a network connection even though local versions exists in the godep workspace. Is this how godep is designed to work or is it a bug?

I would also like to know this, I have instances in AWS in a VPC so `go get` wont work there. If all the source code is available in the godep workspace why is this not utilized?

**Comment by wheaties** [comment]
Same, running into an issue with a private repo on github. Will look at this code and see if we can add some flags to the `godep restore` command and if not, will see about submitting a patch.

**Comment by freeformz** [comment]
get is a holdover from when godep didn't save the files. You generally don't need to use it.
