### ISSUE TITLE
Cannot update sub packages

### ISSUE THREAD

**Issue by Johnny-Malizia** [tools/godep#142]
Currently when updating a sub package but not the root, an update aborted.

eg.

```
godep update github.com/org/project/log
godep: not in manifest: github.com/org/project/log
godep: no packages can be updated
```

I dug into this a little and seems to be caused by https://github.com/tools/godep/blob/master/update.go#L154 and the other uses of the noupdate map.

I have a change to remove that usage, but was curious as to whether or not this was done on purpose. My thinking is that if explicitly updating a sub package, it should be allowed to update regardless of it's root.

I would submit a PR, but it seems to break a test explicitly checking for this.

**Comment by freeformz** [comment]
Closing in favor of #86 as well.
