### ISSUE TITLE
Question about godep workflow for modifying vendor packages

### ISSUE THREAD

**Issue by marcesher** [tools/godep#148]
@kr  This is not a bug report, but a question about workflow. If there's existing documentation that explains it, I'd love to read it.

What's the suggested workflow for using vendor packages which you've modified? 

For example, say I godep save `src/github.com/marcesher/myproject`

I then want to modify `Godeps/_workspace/src/github.com/foo/bar` and push that change to my own fork of the package.

While I wait for the pull request to be accepted, which could be an hour or it could be never, I need all developers, and all continuous integration systems, to use my version of this package.

This implies, I think, rewriting the path for just that project.

When you're in this situation, how do you do it?

Thanks!

**Comment by lazywei** [comment]
but what if the upstream doesn't merge the pull request?
Is it possible to specify a forked github repo url for a package?

**Comment by freeformz** [comment]
Closing in favor of #79
