### ISSUE TITLE
godep exec -- please

### ISSUE THREAD

**Issue by tve** [tools/godep#171]
Maybe I'm missing something, but I believe that a `godep exec` command that executes an arbitrary command with the correct GOPATH is necessary. This would be similar to `godep go` just not limited to only the go command. For example, I use ginkgo for running tests and `go exec` would be really nice. The readme has a directly related example for the oracle command:
```
$ GOPATH=`godep path`:$GOPATH
$ oracle -mode=implements .
```
However my experience is that this is very bad practice. I did just that for ginkgo. Next I did is to add an import to my code and I typed the obvious into my shell: `godep get github.com/foo/bar`. Unless I'm mistaken this gets the package into the first directory in the GOPATH, which is the godep workspace. But then a `godep save` blows up 'cause the directory it is trying to create is there already. Lots of frustration ensues...

My conclusion is that the only safe way to operate is to have a `godep exec` command, or for each user to fabricate one themselves.

**Comment by tony-spataro-rs** [comment]
+1, a `godep exec` command would be supremely useful.

**Comment by phemmer** [comment]
I would find this useful as well, but a way to make your example safer would be:

    $ GOPATH=`godep path`:$GOPATH oracle -mode=implements .

Then `GOPATH` will only be set for that one command.

I would argue that this would be made even safer by doing

    $ GOPATH="$(godep path)" oracle -mode=implements

This will properly handle unusal characters in the path, and it won't use deps outside of `Godeps/` (in case you forgot to add a new dependency to godeps).

**Comment by freeformz** [comment]
Why not just rewrite the vendored deps and then there is no need for godep, except when managing deps?

**Comment by rogierlommers** [comment]
I want godep to use gox for building binaries, is that feasible with the godep path command?

**Comment by pcasaretto** [comment]
:+1:

**Comment by freeformz** [comment]
After Go 1.6 godep path and rewritting is going to go away and we won't be adding a godep exec.

Godep can't vendor gox, you should install it and use it as necessary.
