### ISSUE TITLE
Support management of ./vendor directory with godeps

### ISSUE THREAD

**Issue by stevvooe** [tools/godep#172]
Currently, one can use `godep save` to vendor dependencies and `godep save -r` to rewrite the imports to "<package path>/Godeps/_workspace/src/...". While this is convenient, it would be nice to have godep manage a vendor directory, as is done in other projects with various scripts.

For example, let's say we have a directory layout like this for a package:

```
./vendor
./vendor/Godeps.json
./vendor/github.com/...
... other go files ...
```

This gets rid of the ugly "Godeps/_workspace/src" in re-written imports and let's one choose whether or not to actually use godeps for builds, such as during `go get`. This also avoid issues with mutating GOPATH or using the correct incantation of godeps to merely get a build.

There seem to be a few concepts to follow that would allow such operation:

- Allow one to configure the "workspace" source directory for the target of godep. To support the example above, one might specify "./vendor" as the workspace source.
- Alternatively, the tool could walk the directory to find the Godeps.json file and treat that parent directory as the workspace source. For backwards compatibility, the tool would revert to the current layout if the parent directory is named "Godeps". 

I apologize if this is a duplicate issue or this concept isn't a direction in which the community would like to take this tool. Godeps is very close to being a nice vendoring solution and something along these lines would help to bring it all the way there.

**Comment by aluzzardi** [comment]
:+1:

**Comment by vieux** [comment]
:+1:

**Comment by dmcgowan** [comment]
I would also take a look at #184.  Using the `internal` directory may be a more future proof design. Also worth considering the "_" is there to keep the go tool from traversing the directory when starting at the project root.

Mixing the ideas may come up with something more like...
~~~~
./internal/Godeps.json
./internal/_vendor
./internal/_vendor/github.com/...
... other go files ...
~~~~

**Comment by vieux** [comment]
While we're at it, why not

`./internal/godeps.json`?

I find the capital G ugly

**Comment by stevvooe** [comment]
@dmcgowan Agreed. I think the use case in #184 would be covered by this request.

**Comment by dmcgowan** [comment]
Seems like the best path to support those use cases would be to add flags for specifying the godeps.json file and the _workspace/src directory.  Defaults would obviously be Godeps/Godeps.json and Godeps/_workspace/src, but being able to override and add to a Makefile would be great.

**Comment by freeformz** [comment]
We're supporting the go 1.5 vendor experiment, so I'm closing this.

Thanks!

**Comment by stevvooe** [comment]
@freeformz We spoke at GopherCon and I approve this message!
