### ISSUE TITLE
cross-arch awareness?

### ISSUE THREAD

**Issue by jbenet** [tools/godep#174]
(sorry if this is a dupe, didn't find it.)

Suppose I have:

```go
// foo_darwin.go
import (
  p "Godeps/_workspace/src/some/package/for/darwin/specific/stuff" 
)
```

running `godep save -r ./...` on non-`darwin` archs will unvendor `some/package/for/darwin/specific/stuff`, which causes frustration for non-`darwin` developers.

We can work around this by including a:
```go
// foo.go
import (
  p "Godeps/_workspace/src/some/package/for/darwin/specific/stuff" 
)

// this is to ensure go src tools (like godep) see arch-specific p across archs
var _ = p.somevar
```

But I think `godep` should probably be smart enough to detect this case. Or at least have some way to mark it depended upon.

**Comment by oliveagle** [comment]
:+1:     
and when a project contains multiple arch packages dependencies also painful right now.

on darwin `godep save`, then findout that windows dependencies have been removed from `_workspace` and `Godep.json`. 
now I have to checkout those deleted windows dependencies back into `_workspace` and modify Godep.json manually.  which is painful process.

**Comment by vrecan** [comment]
I am also running into this issue. I have a project that is currently compiling different code for linux and windows. When running godep save I am only getting the deps for the current arch and not for all the archs.

**Comment by phemmer** [comment]
I do think this is a dup of #161 
Just throwing in a comment to github links the 2 issues together.

**Comment by freeformz** [comment]
Closing. See #161
