### ISSUE TITLE
Feature Idea: Build Godeps metadata into binary

### ISSUE THREAD

**Issue by philips** [tools/godep#176]
It would be nice if there was a standard way inside of Go to annotate a package's debug information with a version (git commit, etc). The primary use case would be to introspect the binary to see if the packages inside of it contain un-patched vulnerabilities.

The UX I am looking for is something like:

```
$ godep describe ./etcd
golang.org/x/crypto git:f1d2d2f924e986ac86fdf7b36c94bcdf32beec15 version:1.4.1
code.google.com/p/go-uuid/uuid hg:6eadeac2dade6347e87c0d24fd455feffa7069f0
etc
...
```

The obvious way to do this would be to use the linker. So, if a user wants to expose this sort of information their package could define variables such as:

gopkgVersion
gopkgGit

Then at build time Godeps could help out by generating the necessary `-ldflags` to go into `go build`. 

Hard mode suggestion: push for this symbol layout to be part of the `go` command tooling.

/cc @bradfitz

**Comment by freeformz** [comment]
You could do this with the linker now, it would just be a bunch of convoluted uses of -X.

A convention like this is better off made as a https://github.com/golang/proposal though.
