### ISSUE TITLE
include VERSION for godep

### ISSUE THREAD

**Issue by jtarchie** [tools/godep#177]
Recently when using `godep` we have inconsistent behavior between our development machines. Though the `godep help` had the same output there was definitely difference in its execution.

It would have been useful to have a `godep version` to see that we were using different versions. In the end the way we figured out was by doing `shasum godep` on each workstation to find there was a difference in the compiled binaries.

Can this be added with a pull request?

**Comment by freeformz** [comment]
Please PR if you are still interested in this. I think it's becoming increasingly important.

**Comment by shurcooL** [comment]
Resolved in b6a021fcf062a94ce1248fc29c49414739c171b4.
