### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by hoffoo** [tools/godep#178]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with godep. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable godep on @Sourcegraph by going to https://sourcegraph.com/github.com/tools/godep and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by kr** [comment]
Done. Thanks for the report!
