### ISSUE TITLE
Exclude distro info from GoVersion section in Godeps.json

### ISSUE THREAD

**Issue by ceiroa** [tools/godep#181]
When running godeps for a Go project in mac, it adds darwin/386 after the go version. If you then try to push the project to Heroku, it will fail.

**Comment by m143554756454** [comment]
The same thing happens when runnnig godeps on windows, `windows/386` is added.
My current fix is to edit GoDeps.json by hand before I push.

**Comment by ceiroa** [comment]
Yes, I also modify the file manually to be able to push. That seems to work fine.

**Comment by freeformz** [comment]
This shouldn't happen now so closing. If it's still happening please re-open.
