### ISSUE TITLE
Moving /Godeps under /internal/ to implement proposal golang.org/s/go14internal

### ISSUE THREAD

**Issue by maruel** [tools/godep#184]
The general idea is that Godeps packages are a detail inside the base package and shouldn't be external APIs. As such, they should be contained in a directory /internal. That would fit squarely within the proposal and would be a great improvement from a maintenance perspective.

Currently the format is /Godeps/_workspace/src/.
The directory /Godeps would have to be named /internal to conform with the proposal. The rest is a judgment call. Should the Godeps me simply renamed, included or _workspace should be renamed? Where to put the godeps.json file? I propose:

  - /internal/_godeps/src/...
  - /internal/godeps.json

but I don't claim to know any better and I don't mind about the internal layout. I'm filing this issue to know if kr would accept a patch implementing this, to know what's his preference about the internal layout and what "upgrade path" is preferred. I'm fine with doing the actual implementation.

*Notes:*

  - While forcing a directory rename, could lowercase paths be used? E.g. "godeps.json" and "godeps".
  - I'm a bit surprised there was no such request already. Proposal https://golang.org/s/go14internal is useful from a maintenance standpoint and godep is squarely aimed at maintainable projects.

**Comment by freeformz** [comment]
We're supporting the go 1.5 vendor experiment so I'm closing this. Thanks!

**Comment by maruel** [comment]
No problem!
