### ISSUE TITLE
Godep doesn't seem to grok imports declared in *_test.go files

### ISSUE THREAD

**Issue by tony-spataro-rs** [tools/godep#185]
My project uses ginkgo and gomega, so my unit tests dutifully import those two packages. When I run `godep save`, it seems that neither of them is saved to  my workspace. What's the consequence?

1) I need to instruct everyone to install them manually in my README.

2) In order to run my tools, I need to tweak my PATH (to get my project's imorts) and then run ginkgo. (This would be alleviated somewhat by tools/godep#71) Or, I need to tell people to `godep restore` before running tests. Neither is quite optimal.

It seems like test dependencies are still part of a project's dependencies, even if they can be considered as optional in some circumstances. Shouldn't Godep give me the option to manage these?

**Comment by sethgrid** [comment]
Hey Tony, Here is what we are doing to get around this. 

We have a separate subpackage we call `deps` in our code and import it like:
`import _ "/src/github.com/our_company/the_package/deps"`

In there, we have deps.go. It looks like:

```
package deps

/*
January 2015

Godeps does not support build tags, so this file is a workaround to get packages vendoered by godeps.
These are all packages imported in test files that have +integration tag.

*/

import (
	"code.google.com/p/go-uuid/uuid"
	"github.com/bitly/go-simplejson"
	"github.com/sethgrid/httpsink"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func init() {
	var _ uuid.UUID
	var _ simplejson.Json
	var _ assert.TestingT
	var _ httpsink.HTTPSink
	var _ assert.Assertions
	if false {
		require.True(nil, true)
	}
}
```

This tricks godep into pulling in the files. Waiting on a fix in the meanwhile.

**Comment by tony-spataro-rs** [comment]
That's a clever workaround; thanks for the suggestion. I hastily tried a variant of that, but I don't think I referred to contents of the imports, so they probably got optimized away!

**Comment by freeformz** [comment]
I think I am running into this issue in an internal repo...
```
broker/io.go:8:2: code in directory /Users/emuller/go/src/github.com/heroku/busl/Godeps/_workspace/src/github.com/garyburd/redigo/redis expects import "github.com/garyburd/redigo/redis"
```

When I look into the files there I see things like this...

https://github.com/garyburd/redigo/blob/master/redis/conn_test.go#L27, which aren't rewritten, althought L28 is.

**Comment by freeformz** [comment]
Hmm. Maybe this wasn't related to this problem as I've managed to resolve it with some updates.

**Comment by schickling** [comment]
+1

**Comment by gonzaloserrano** [comment]
+1

**Comment by charleswli** [comment]
Running `godep save ./...` in the repo root saves the test dependencies for me, but I'm curious as to why `godep update ./...` does not work (it does not seem to evaluate the import package pattern):

```
> godep save ./...
> git diff
diff --git a/Godeps/Godeps.json b/Godeps/Godeps.json
index 374f731..d7e4123 10064a
--- a/Godeps/Godeps.json
+++ b/Godeps/Godeps.json
@@ -1,11 +1,24 @@
 {
        "ImportPath": "github.com/charleswli/mypackage",
        "GoVersion": "go1.4.2",
+       "Packages": [
+               "./..."
+       ],
        "Deps": [
+               {
+                       "ImportPath": "github.com/onsi/ginkgo",
+                       "Comment": "v1.1.0-38-g5ed93e4",
+                       "Rev": "5ed93e443a4b7dfe9f5e95ca87e6082e503021d2"
+               },
+               {
+                       "ImportPath": "github.com/onsi/gomega",
+                       "Comment": "v1.0-28-g8adf9e1",
+                       "Rev": "8adf9e1730c55cdc590de7d49766cb2acc88d8f2"
+               }
        ]
 }

> godep update ./...
godep: not in manifest: ./...
godep: no packages can be updated

**Comment by freeformz** [comment]
@charleswli update requires you to specify a specific package. AFAIK `./...` doesn't work with update.

**Comment by charleswli** [comment]
> update requires you to specify a specific package. AFAIK ./... doesn't work with update.

@freeformz, yep, my question is *why* does that pattern not work.

**Comment by kr** [comment]
Update matches its arguments as a pattern against the list of dependencies. By construction, none of the dependency packages are inside `.`, so the pattern `./...` matches none of them. If you want to match all dependencies, the easiest way is to use `...`.

**Comment by aresetian** [comment]
I had updated my version of  godep, but  (godep save -  godep save ... - godep save ./... - godep save . ) does not include dependency test - In my case  I need to include github.com/stretchr/testify/assert-. I believe that the solution that @sethgrid shows us work, but this isn't the solution I was waiting, In my humble opinion godep should include dependencies test.

**Comment by carlosmmelo** [comment]
+1

**Comment by tim-kretschmer-c2fo** [comment]
:+1:

**Comment by jayunit100** [comment]
Any updates on this ?   We'd like to import _tests from a project as well, and run into the same issue.

**Comment by freeformz** [comment]
The reported issue works for me. I made a test lib with a single function and used gomega to test it and ran `godeps save` and here's what it generated...

```console
$ cat Godeps/Godeps.json
{
	"ImportPath": "github.com/freeformz/t185",
	"GoVersion": "go1.5",
	"Packages": [
		"./..."
	],
	"Deps": [
		{
			"ImportPath": "github.com/onsi/ginkgo",
			"Comment": "v1.2.0-6-gd981d36",
			"Rev": "d981d36e9884231afa909627b9c275e4ba678f90"
		},
		{
			"ImportPath": "github.com/onsi/gomega",
			"Comment": "v1.0-28-g8adf9e1",
			"Rev": "8adf9e1730c55cdc590de7d49766cb2acc88d8f2"
		}
	]
}
```

@jayunit100 What issue are you running into?

**Comment by jayunit100** [comment]
Yes I think you are right.  My issue is a package not locally seeing imports from the same package.  I'll confirm what the precise problem is and update in this thread..

**Comment by jayunit100** [comment]
@freeformz ok, Im finding that my core issue here is that I cannot reference public functions or variables that are declared in  `_test.go` files. This is not really a Godeps issue in any way.   Ignore :)

**Comment by freeformz** [comment]
Great. Closing this issue as it appears to be solved.
