### ISSUE TITLE
Add command to un-rewrite import paths

### ISSUE THREAD

**Issue by eikenb** [tools/godep#189]
Add a command to switch from the vendored import paths to unvendored (pristine) paths. The reverse of 'godep save -r'. Being able to switch back and forth easily would allow for the benefits of the rewritten paths (go get-able, work with go tools) while still allow the benefits of the un-rewritten paths (easily switching between different versions, cleaner source, vendored packages in branch).

**Comment by glkz** [comment]
:+1:

**Comment by gfrey** [comment]
:+1: 
I'm missing this so badly when modifying dependent libraries.

**Comment by freeformz** [comment]
Does `godep save -r=false` not accomplish this?

**Comment by gfrey** [comment]
It does something like that, but for all vendored libraries, not a single one (at least for me it simply ignored the given package).

**Comment by freeformz** [comment]
@gfrey I'm not sure what you mean by "given package".

**Comment by gfrey** [comment]
I've vendored some large libraries and would like to be able to just "devendor" a single of them, like in `godep save -r=false github.com/dynport/urknall`. This would keep everything else fixed, keep the clutter in `git diff` minimal and allow for easy manipulation of a single library.

Not sure how dependent libraries of the dependency should be handled though.

**Comment by freeformz** [comment]
So you don't really want to unrewrite the import you want to remove it? If you remove all of the import statements imports a dependency and re-run `godep save -r` any no longer used imports will be removed from the workspace. The arguments to `godep save` aren't the packages that you want to vendor, they are the package spec(s) that you want to analyze for vendoring.

**Comment by gfrey** [comment]
In the example given (`godep save -r=false github.com/dynport/urknall`) I don't want to totally remove the usage of the urknall package (what I guess you understood), but un-rewrite the import paths, so that the version in my `$GOPATH` is used again, instead of the one in the `Godeps/_workspace`.

Benefit would be, that I'd not have to commit changes to the urknall library and use `godep update github.com/dynport/urknall` to test them in the respective binary.

When being finished with changing the urknall library, I'd just `godep update github.com/dynport/urknall && godep save -r ./...` to get everything back to normal in the binary.

**Comment by freeformz** [comment]
@gfrey that would confuse the meaning of the package spec passed to `godep save`, which is the packages you want to analyze dependencies for, usually '.' (the default), './...', or './cmd/...'. To be honest rewrites are going away as we approach Go 1.6 and the use of the `vendor/` directory, so I'm tempted to close as won't fix with the expectation being that you would use the vendor directory directly w/o rewrites anyway. At that time a `godep rm` command (which doesn't exist) would solve your problem (or just rm stuff manually from `vendor/`). ATM `godep save -r=false <your local package spec>` will un-rewrite everything so you can still do what you want, it will just take a few extra commands before or after. 

Does that make sense?

**Comment by gfrey** [comment]
If rewrite is going away anyway you are right (maybe I should put some focus on Go project politics), so I'm fine with issue being closed. Keep in mind I'm not the OP!
