### ISSUE TITLE
Godep with gvm linkthis

### ISSUE THREAD

**Issue by geovanisouza92** [tools/godep#195]
Hello guys, thank you for this amazing project!

I'm trying to run godep inside a folder that is linked with ```gvm linkthis```. My project code is under ```~/Code/foo```, then I run ```gvm linkthis github.com/geovanisouza92``` and I got:

```
“/home/geovani/.gvm/pkgsets/go1.4/global/src/github.com/geovanisouza92/foo” -> “/home/geovani/Code/foo”
```

Then I wrote some Go code inside main.go and tried to run ```godep save``` then I got:

```
godep: directory "/home/geovani/Code/foo" is outside source root "src"
godep: error loading packages
```

There is a way to change the godep "source root"?

**Comment by trkrameshkumar** [comment]
+1

**Comment by trkrameshkumar** [comment]
Hi @geovanisouza92,  have you found any solution for this issue?

**Comment by andrioid** [comment]
Try

```
cd /home/geovani/.gvm/pkgsets/go1.4/global/src/github.com/geovanisouza92/foo
godep save
```

Worked for me.

**Comment by geovanisouza92** [comment]
@andrioid If I have to go into GOPATH, what is the utility of ```gvm linkthis```?

**Comment by freeformz** [comment]
It looks like "/home/geovani/Code/foo" is outside of your GOPATH. godep really only works with packages inside of a GOPATH.

**Comment by geovanisouza92** [comment]
The point here is "how to tell godep to use the gvm linked folder, instead of cwd?"

**Comment by VarunBatraIT** [comment]
@geovanisouza92 

- Create a package set gvm pkgset create X
- Use it gvm pkgset use X
- Now you have gvm pkgenv with env variables. 
- Do gvm linkthis where you want. 
- cd to path.
- dep init
Now it should work - you can then go back to the main directory.
