### ISSUE TITLE
Does godep support package dependency files into tar file?

### ISSUE THREAD

**Issue by netroby** [tools/godep#197]
Does godep support package dependency files into tar file?

For example, we have a huge go source workspace, we want package workspace with dependency into a tar package, then send it to another clean pc, then we can using godep to extract it to workspace.

It's behaviour like put java's jar files into lib directory, then in new workspace, just copy the jars into fresh clean lib directory, every dependency resolved.

No more need download from the internet.

we can do local to local copy.

**Comment by freeformz** [comment]
I don't think godep will (or should) support this.

You could rsync the package from one machine to another.
Or use github (or other git hosting service).
