### ISSUE TITLE
function ends without a return statement

### ISSUE THREAD

**Issue by nadgowdas** [tools/godep#198]
Hi,

I am trying to setup godeps and i am getting following message:
> go get github.com/tools/godep

> golang.org/x/tools/go/vcs
src/golang.org/x/tools/go/vcs/discovery.go:20: function ends without a return statement
src/golang.org/x/tools/go/vcs/discovery.go:31: function ends without a return statement

Can you help me with this?

**Comment by tommymcdonald** [comment]
I'm currently having the same issue

**Comment by akavel** [comment]
What is your `go version` output? Most probable explanation would be that you're using too old version of Go (earlier than Go 1.1; see https://golang.org/doc/go1.1#return).

**Comment by freeformz** [comment]
Upgrade your go version as per @akavel.
If this still persists and you are also on the most recent version of godep (go get -u github.com/tools/godep) please re-open this issue.
