### ISSUE TITLE
godep support for goxc

### ISSUE THREAD

**Issue by sundarv85** [tools/godep#199]
Currently godep does not support goxc command. This is useful for cross compiling binaries. 

If we freeze using godep, it would make help to support cross compilation when we want to make production releases. 

It would be good if this can be supported

https://github.com/laher/goxc

**Comment by jpillora** [comment]
duplicate #34

**Comment by freeformz** [comment]
I use gox to cross compile several projects that are under godep. 

These tools run the `go` command you need to rewrite your dependencies (`godep save -r ./...`), then you  will no longer need to do `godep go ....` and will only need to use godep when adding new files to your application or managing dependencies.
