### ISSUE TITLE
Does not download sources for packages via gopkg.in

### ISSUE THREAD

**Issue by amoghe** [tools/godep#204]
When attempting to import `https://github.com/alecthomas/kingpin` via its gopkg.in URL `"gopkg.in/alecthomas/kingpin.v1"`, I only see the json file updated, and no sources are downloaded. However, updating the import path to `"github.com/alecthomas/kingpin"` does the right thing.

What am I missing? Are non-github import paths not supported?

Some details:
1. Im running `godep save ./...`
2. I'm running it in a dir that has no go source files but has subprojects (one of which is attempting to import the `kingpin` package)

**Comment by freeformz** [comment]
godep does not upload or download source files, it manages package locally vendored copies from those installed into your $GOPATH.

Try ..

```term
$ go get -u gopkg.in/alecthomas/kingpin.v2
$ cd $GOPATH/src/<your package>
# ensure that you are importing "gopkg.in/alecthomas/kingpin.v2" in one of your files
$ godep save -r ./...
```
