### ISSUE TITLE
godep hanging at Go tip

### ISSUE THREAD

**Issue by fsouza** [tools/godep#206]
Here's my example:

```
% go version
go version devel +f633e44 Thu Apr 16 16:50:30 2015 +0000 darwin/amd64
% pwd
$GOPATH/src/github.com/fsouza/sample
% ls
main.go
% cat main.go
package main

import (
	"fmt"
)12 

func main() {
	fmt.Println("Hello world!")
}
% godep save
```

It hangs forever, with a process named "go" eventually taking all the available memory (I killed the process when it was consuming around 12GB, when OS X went crazy compressing memory).

**Comment by acroca** [comment]
Same here

**Comment by acroca** [comment]
@fsouza My project has actually a dependency on your fsouza/go-dockerclient, perhaps including docker as a dependency is an  issue since it's too big? I'm not sure what's going on with godep, but both save and restore eats all the memory and never finishes.

**Comment by acroca** [comment]
I updated and recompiled go and it now works fine. I was using a go version from like a week ago.

**Comment by fsouza** [comment]
Hi @acroca, the sample I provided doesn't have any third party dependency, and yet it hangs.

I just updated Go and it works now, maybe it was something with Go itself. I've also checked and our [travis tip build](https://travis-ci.org/tsuru/tsuru/jobs/59590134) now works.

Since it was apparently an issue with Go, I'm closing this issue.

**Comment by fsouza** [comment]
It doesn't hang anymore, but now it's bad behaving, here is an example of file generated for [go-dockerclient](/fsouza/go-dockerclient): https://gist.github.com/fsouza/92851d03a03ec556e0be.

Using Go 1.4, I get a different result: https://gist.github.com/fsouza/39b171c301467cf85c84.

Seems like ``go list`` is changing.

**Comment by freeformz** [comment]
I cannot duplicate this with go from source as of today + current version of godep from source. Please re-open with a reproducible test case if this is still an issue.

Thanks!
