### ISSUE TITLE
[BUG] Cannot import from "gopkg.in"

### ISSUE THREAD

**Issue by redstrike** [tools/godep#208]
```
C:\Users\Tung\Go\src\myapp>godep save
godep: dirty working tree: C:\Users\Tung\Go\src\gopkg.in\flosch\pongo2.v3
godep: error loading dependencies
```

After I changed "gopkg.in\flosch\pongo2.v3" => "github.com/flosch/pongo2", it works.

**Comment by freeformz** [comment]
FWIW: This works fine for me unless the checked out version of `gopkg.in\flosch\pongo2.v3` had uncommitted changes in it, hence the "dirty working tree" error.
