### ISSUE TITLE
Feature Request: Add option for 'godep save' to create dependency list without coping source code

### ISSUE THREAD

**Issue by dhawal55** [tools/godep#209]
I would like an option for 'godep save' to generate the dependency list (godeps.json) without creating the _workspace folder. I can always use 'godep restore' to get the pinned dependencies and don't need to save them in _workspace folder.

**Comment by tve** [comment]
+1

**Comment by volker48** [comment]
Yeah, I don't understand the point of saving the source code if `godep restore` is just going to check it out from the repo anyway? Is it just in case the repo goes away? If so, just restore the files form the workspace and don't bother checking it out.

**Comment by omgnuts** [comment]
+1

**Comment by freeformz** [comment]
If anything the `_workspace` folder and restore are going away with the advent of the `vendor/` directory. You can't make reproducible builds if the code is not vendored, and that is the point of godep, so unfortunately -1.

AFAIK: `godep restore` is there as a relic of the past. If I can make it go away (and I haven't spent the requisite time yet) it will.
