### ISSUE TITLE
command: 'godep run'

### ISSUE THREAD

**Issue by kr** [tools/godep#21]
https://groups.google.com/d/msg/go-package-management/-rNvdrdPC-k/ofin3XevusYJ

@davecheney:

> godep shell anyone?

@ardan-bkennedy:

> That is an awesome idea. That could really help make things easy for everyone. People don't want to think, "just tell me what to do". 

>The shell could identify the Godep folder(s) within a workspace, automatically setup the GOPATH and everything would run. It could also intercept calls and perform magic when necessary. All the go tooling works without needing to type godep first. It could handle some of the harder problems I am sure.

**Comment by interlock** [comment]
:+1:

**Comment by freeformz** [comment]
For now you should rewrite your deps so that you only need to use godep when managing dependencies. Long term it's likely the need to rewrite will go away pending the [vendoring experiment](https://go-review.googlesource.com/#/c/10923/).
