### ISSUE TITLE
Is there a way to exclude specific packages?

### ISSUE THREAD

**Issue by jaytaylor** [tools/godep#211]
Is there a way to exclude specific packages from godep so that it will ignore them and not try to bundle them?

**Comment by hectorj** [comment]
:+1: 
I'd like a solution to that too

**Comment by neurogeek** [comment]
Hi @jaytaylor, 

Would you care to elaborate a bit on your use case?

Cheers,

**Comment by jaytaylor** [comment]
Hi @neurogeek, happy to elaborate.

Let us suppose there are 2 distinct "top-level" go projects involved, X and Y.

Package X.models contains the [shared] domain models.

Package Y.producer makes use of the domain models.

Package X.consumer makes use of Y.producer.

In this situation, I never want Godeps to vendor X or Y for either of these packages.  I strongly prefer to have the build fail due to a missing dependency rather than risk using a potentially stale version of either of these packages.

Right now it's a real pain to update Godeps for these projects because one must manually clean out traces of packages X and Y from the _workspace/src directory as well as manually edit Godeps.json.

**Comment by freeformz** [comment]
godep vendoring works are the repo level, not the package level.

**Comment by jaytaylor** [comment]
@freeformz Not sure what you are trying to convey.  AFAICT `godep` operates at the package level for me, e.g.:

__Here only the subdir containing the referenced package was pulled in by `godep` (not the entire repo):__

    $ tree Godeps/_workspace/src/github.com/samuel/go-zookeeper/
    Godeps/_workspace/src/github.com/samuel/go-zookeeper/
    └── zk
        ├── cluster_test.go
        ├── conn.go
        ├── constants.go
        ├── constants_test.go
        ├── flw.go
        ├── flw_test.go
        ├── lock.go
        ├── lock_test.go
        ├── server_help.go
        ├── server_java.go
        ├── structs.go
        ├── structs_test.go
        ├── tracer.go
        ├── util.go
        ├── util_test.go
        └── zk_test.go
    
    1 directory, 16 files

**Comment by freeformz** [comment]
I don't understand this use case though. 

Godep's goal is to vendor code for reproducible builds.

**Comment by jaytaylor** [comment]
The idea here is to gain control over what godep will vendor (or not vendor).  It is sometimes desirable to exclude a dependency if you know that there will always be a local up-to-date copy available somewhere else in $GOPATH. 

It is similar to the way `dpkg` lets you exclude what packages and files included in an operation.  From [the first search result for `dpkg exclude`](https://raphaelhertzog.com/2010/11/15/save-disk-space-by-excluding-useless-files-with-dpkg/):

    dpkg has two options --path-include=glob-pattern and --path-exclude=glob-pattern

@freeformz Is any of this information helpful?

**Comment by freeformz** [comment]
WRT Go: If you push me your repo or I check it out on a random machine, I need all the code in that repo to build the code. W/o all the necessary code I can't build the app.

**Comment by jaytaylor** [comment]
@freeformz Agreed, though I'm not sure why this is what we're discussing.

What is the issue with giving users more control over how Godep behaves?

Considering the `dpkg` example reference above, it is a very similar situation.  The package being installed with those flags may very well not end up in a working state.  Ok, then it's just on whoever is using (or misusing) the `dpkg` tool.

In this case I've proposed an option to increase the utility of Godep.  We all know that dependency management is a huge pain point with Go.  I think Godep is on the right track already and want it to grow to become the cure for all this pain.

**Comment by kr** [comment]
> What is the issue with giving users more control over how Godep behaves?

A proliferation of knobs and switches creates drag on both the interface and implementation. That makes it harder to design and implement truly important changes as they arise. Each new feature must "pay its way" by providing more benefit than the cost of maintaining it for the rest of eternity. This is doubly true for features that expose configuration options. (The ideal new feature "just works" without any change in the user's behavior. [Adding more configuration is an admission of failure.](http://ometer.com/preferences.html))

> In this case I've proposed an option to increase the utility of Godep.

This change would give a *local* increase in utility—confined to a few unusual cases—at the cost of a small but *global* decrease in the utility of Godep—for the numerous "background" use cases. It is not clear to me that the few occurrences of increased utility add up to more than the global cost.

It seems to me like a net decrease in utility.

However, these days @freeformz probably has a better idea than I do about how godep is being used. We should defer to his estimate.

**Comment by freeformz** [comment]
@kr Thanks I was just about to attempt to write more or less the same thing. Thanks for being so eloquent as always.

**Comment by tsuna** [comment]
This probably won't change anything but I'm in a similar situation where at Arista we have a repo in which we vendor all our third-party dependencies, but we don't want to vendor our other internal repos due how things are setup in our environment.

I fully understand the desire to keep `godep` simple, but I imagine that adding a flag (or an entry in `Godeps/Godeps.json`) to list package names that shouldn't be vendored and filter the list of packages collected by `godep` during commands like `godep save ./...` wouldn't be too big of a code change, if you're willing to consider it.

**Comment by freeformz** [comment]
@tsuna I'll have to think about it more.

**Comment by gotomgo** [comment]
Jeez this was a complete circle-jerk. Are all the GO forums like this?

**Comment by edhemphill** [comment]
I use a pre-processor. So, I have code in a `/src` folder. I would like godeps to ignore this. As the above poster noted, I have also found most of the people in the core Go and go tools community to be like this when it comes to feature requests. Alas.

**Comment by edhemphill** [comment]
As a workaround, you can rename folders and put a `.` in front of them. godep ignores hidden folders it seems. Works for more. I use a build script anyway, so this works for me.
