### ISSUE TITLE
install problem from china

### ISSUE THREAD

**Issue by jack1582** [tools/godep#213]
I was in go 1.3.3 . when I run 'go get github.com/tools/godep', it generated a error msg 'unrecognized import pkg golang.org/x/tools/vcs  etc...'.

The domain golang.org is not reachable from mainland in china,because of the chinese gfw :-(

so , would you please copy the golang.org 's vcs package to the github?

**Comment by anonx** [comment]
@kr This problem could be fixed by use of Godep for your Godep dependencies, lol.

**Comment by freeformz** [comment]
See comments on https://github.com/tools/godep/pull/214 for a workaround.
