### ISSUE TITLE
Godep save not saving all packages

### ISSUE THREAD

**Issue by mDomingues** [tools/godep#220]
Hi, first of all +5 for this project. :)

In my project I "godep save" all my project dependencies but some are missing from the JSON file.
All of them were fetch using "go get".
I read all the issues but nothing came as close. Does it have an explanation ?
Many many thanks

**Comment by abourget** [comment]
Did you try `godep save ./...`  ?

**Comment by freeformz** [comment]
I would also add a `-r` to that as well so that the dependencies get rewritten. This will allow you to not have to use godep unless you are modifying dependencies (i.e. you can just use `go test` and the like naked and the app is then `go get` 'able). Assuming it's an app and not a library.

**Comment by abourget** [comment]
What I would have liked is that when you re-run `godep save`.. it reissues the same parameter as was saved in `Package` in the _Godeps.json_ file .. having to remember what was the full command you typed is error prone.

**Comment by freeformz** [comment]
@kr what are your thoughts on storing the -r flag (or detecting it) and picking up the package spec from an existing Godeps.json file if none is provided?

**Comment by kr** [comment]
Sounds like DWIM. If I type `godep save`, it's not the same thing as `godep save ./...`.

Storing the -r might be ok, but then how would a project switch to not rewriting import paths?

If we did something like this, then the rules for godep's behavior would be more complicated. It would be a guessing game what exactly it'll do when you run `godep save`, and it's not really clear how to get the "real" `godep save` behavior when that's what you want.

**Comment by freeformz** [comment]
SGTM. I'm going to close this then as it's unlikely something that we'll do.
