### ISSUE TITLE
godep: unable to detect version control system for code.google.com/ path

### ISSUE THREAD

**Issue by myliu** [tools/godep#221]
We are unable to build recently due to the error "unable to detect version control system for code.google.com/ path", I wonder if it is related to the farewell of Google Code as mentioned in the following article?  Or it is newly introduced bug in godep?

http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html

**Comment by freeformz** [comment]
You likely need to re-vendor under the new paths?

**Comment by pmoust** [comment]
I faced the same issue just now.
Solution was to `%s#code.google.com/p/#github.com/google/#g`
Will have to submit a PR to all providers referencing `code.google.com` though.

**Comment by ghodss** [comment]
Shouldn't read-only code.google.com still be working through January of next year, though?

**Comment by myliu** [comment]
Unfortunately, some repos have migrated to to github, and the original repos have been closed. Here's an example: `code.google.com/p/snappy-go/`

We end up hacking our `Makefile` to make it work:
`git clone git://github.com/golang/snappy $$GOPATH/src/code.google.com/p/snappy-go/`
