### ISSUE TITLE
Can I use godep to vendor a whole other binary?

### ISSUE THREAD

**Issue by thockin** [tools/godep#222]
I want to vendor ALL of another project - including their main package.  The binary is part of our system and I want to control it.  But since I (obviously) do not reference their main package in my own code - how can I get godep to pull it in?

**Comment by freeformz** [comment]
You can't import another package's main package.

**Comment by kr** [comment]
You can import another package's main package:

##### depmain/main.go

```go
package main

import "fmt"

var X int

func main() {
	fmt.Println("hello from dependency")
}
```

##### example/main.go

```go
package main

import (
	"fmt"

	_ "depmain"
)

func main() {
	fmt.Println("hello from example")
}
```

```
$ go run main.go 
hello from example
$ go install
$ example
hello from example
```

This only works if you haven't installed the other package as a binary in your `$GOPATH/bin`.

**Comment by freeformz** [comment]
hunh. My bad. I thought you couldn't and never checked that assumption out.

**Comment by thockin** [comment]
Awesome!  That works.  You don't even need to make your file have a main() - just import the other main pkg as _.

```
package import_other
import _ "github.com/other/other"

**Comment by mattmoor** [comment]
I'm trying to do this (to vendor the K8s code-generator utilities) and I'm not able to get godep to pull  them in.

I have added to my `main` package:
```go
_ "k8s.io/code-generator/cmd/set-gen"
```

It's not on `$GOPATH/bin`, but is in `$GOPATH/src/k8s.io/...` and I've added it to `Godep.json`.

Any hints?  (sorry if a noob question)

**Comment by mattmoor** [comment]
Hmm, I suspect that this is because Go stopped allowing this?
```shell
$ CGO_ENABLED=0 go build 
controller.go:42:2: import "k8s.io/code-generator/cmd/set-gen" is a program, not an importable package
```
