### ISSUE TITLE
Promote/facilitate a convention for specifying the license type

### ISSUE THREAD

**Issue by m5rk** [tools/godep#226]
It would be awesome if `Godeps/Godeps.json` listed the license type of each dependency using [the standard SPDX ID spdx.org/licenses/ for the license](http://spdx.org/licenses/). How would golang package authors specify the license type (beyond merely listing the license itself in the canonical $pkg/LICENSE file) so that Godeps could find it? Is there a canonical metadata file that describes a golang package like .gemspec files are to rubygems?

**Comment by freeformz** [comment]
I don't think that's something Godep should really be involved in. 

If you feel different I suggest opening an issue on https://github.com/kardianos/vendor-spec, which will likely be supported in the future.

Thank You!

**Comment by m5rk** [comment]
Seems reasonable, thanks for the suggestion:

See kardianos/vendor-spec#21
