### ISSUE TITLE
godep causing go-sqlite3 to compile on every save with vim-go

### ISSUE THREAD

**Issue by gregf** [tools/godep#234]
I'm having a strange issue since I switched to godep. Every time I save a file in my project I noticed a cpu spike and a long delay before I can do anything inside vim. I looked at what was running, and it was compiling some c files inside of `Godeps/_workspace/src/mattn/go-sqlite3`. This happens every time I save the file. 

I would lean towards this being a issue with vim-go and maybe it is, but my go buiild times have more than doubled since I switched to using godep as well. 

Does anyone have a clue as to what might be happening? Thanks!

**Comment by freeformz** [comment]
Do you have syntastic enabled?

**Comment by fatih** [comment]
Vim-go doesn't call `go build` or anything a like. As @freeformz said it might be due https://github.com/scrooloose/syntastic which does auto build on every save.

**Comment by freeformz** [comment]
FWIW: I removed syntastic from my vim setup and similar issues are now resolved for me.

**Comment by freeformz** [comment]
@fatih thanks btw.

**Comment by gregf** [comment]
Thanks guys, and sorry I filed this bug report in the wrong place. I just happened to notice it the same time I was switching to godep.

Setting `let g:loaded_syntastic_go_go_checker = 0` in my vimrc solved the problem.
