### ISSUE TITLE
Could `godep restore` tell me what it does ? and not touch what doesn't need touching ?

### ISSUE THREAD

**Issue by abourget** [tools/godep#237]
When I run `godep restore` all the projects listed have their HEADs detached.. which is a little annoying.  If a dependency is on the `master` branch, and it corresponds to the revision we want to be on, why detach the head? just leave it as is.

Also, it doesn't *tell* me what it's doing.. I'd like to at least know if it's modifying some repos under my nose.

The thing is, not all projects in the world use godep, so touching the GOPATH in the most predictable way, and to know what happens is important.  Those are a few things that keep me from going `godep` all the way, because it touches a little bit to much things without me knowing.

**Comment by freeformz** [comment]
godep restore modifies stuff in your $GOPATH by cloning repos and attempting to checkout the specified revisions. It's *all* about messing with your $GOPATH. I generally recommend using rewrites limiting the need for restore to primary developers. With the vendor experiment this becomes even less necessary.
