### ISSUE TITLE
Godep doesn't handle GOROOT=<project-dir>

### ISSUE THREAD

**Issue by weberc2** [tools/godep#246]
I have this directory structure:

```
project-dir/
-- .git/
-- Godeps/
-- src/
---- pkg1
---- pkg2
```

When I open a shell to work on this project, I first `export GOPATH=$GOPATH:$PWD`, so the project directory *becomes* `$GOROOT`.

This structure is important to me because it allows me to import `pkg1` from `pkg2` without using absolute import paths, which break everything when someone else forks your repo (if my colleague forks my repo, changes `pkg1` and attempts to build `pkg2`, her build will pull in `weberc2/pkg1` instead of `colleague/pkg1`).

However, when I attempt to `godep save ./src/pkg2`, it fails with:
```
godep: error while inspecting "$GOPATH/github.com/weberc2/project-dir/src/pkg1": directory "$GOPATH/github.com/weberc2/project-dir/src" is not using a known version control system
```

I know there has been a lot of discussion about vendoring, and if there's some alternative package structure that would solve my problems (relative imports and godep), feel free to suggest it. Otherwise, could godep be made to support this use case?

**Comment by freeformz** [comment]
Godep isn't really designed for this scenario.

Personally, I would do the above differently, like so:

```term
$ export GOPATH=~/go
$ mkdir -p ~/go/src/github.com/freeformz/project-dir
$ cd ~/go/src/github.com/freeformz/project-dir
$ mkdir pkg1
$ mkdir pkg2
$ .... code .....
$ godep save -r ./...
$ go test -v -race ./...
...
```

The above would make `pkg1` and `pkg2` available to any other project in my `$GOPATH` as `import github.com/freeformz/project-dir/pkg1` and `import github.com/freeformz/project-dir/pkg2`, although I would then vendor + rewrite them for use in other projects.

If you want to work on "projects" in the way you describe then I suggest checking out https://github.com/constabulary/gb
