### ISSUE TITLE
restore broken on go1.5beta2

### ISSUE THREAD

**Issue by creack** [tools/godep#247]
cf https://groups.google.com/forum/#!topic/golang-dev/i2jD_TRAH4U

Until go1.5beta1, everything worked fine, but since 1.5beta2, godep restore break on CGO :(

Now, when trying to restore, I always get:

```
       imports C: unrecognized import path "C"
```

My guess is that go1.5beta2 changed something in the go/ast, go/parser or go/token which broke godep.

**Comment by freeformz** [comment]
Do you have a simple case / repo that we can use to reproduce?

**Comment by creack** [comment]
The issue occurs with some private repos. Trying to create a selfcontain reproducable example, I figured it is not an issue of godep, but an issue of go get itself.

To reproduce on go1.5beta2: `go get github.com/creack/cgotest`.
