### ISSUE TITLE
`godep update` creates a _workspace directory even when GO15VENDOREXPERIMENT=1

### ISSUE THREAD

**Issue by jacobsa** [tools/godep#250]
I have the environment variable `GO15VENDOREXPERIMENT=1` set. When I initially ran `godep save` to get started, it created a `vendor/` directory as expected. However, when I went to update and ran

    godep update github.com/jacobsa/bazilfuse/...

this caused the directory `Godeps/_workspace/src/github.com/jacobsa/bazilfuse/` to be created, with the up to date contents, and the `vendor/` directory to be untouched.

I'm using godep at d8799f112f6c8dfe1e56142831bc3bb5c8796a0e.

**Comment by gedw99** [comment]
i think you need to run the upgrade like it says on the main readme ?

**Comment by jacobsa** [comment]
More details? I don't see the word "upgrade" anywhere in the readme.

**Comment by freeformz** [comment]
It's updatable like any other go gettable application: go get -u github.com/tools/godep

**Comment by jacobsa** [comment]
@freeformz: This bug isn't about updating godep (I'm already using the latest version), it's about using godep to update my vendored dependencies. Could you please reopen?

**Comment by freeformz** [comment]
@jacobsa Sorry about that.

**Comment by freeformz** [comment]
And I have confirmed the bug with a test app.

**Comment by jacobsa** [comment]
@freeformz: No worries, thanks for coming up with a fix.

**Comment by freeformz** [comment]
@jacobsa If you update godep (go get -u github.com/tools/godep) you should be good to go.
