### ISSUE TITLE
Issue with import and "_"

### ISSUE THREAD

**Issue by shinji62** [tools/godep#252]
Hi,
I am using the last godep version and go 1.4.2 it's seems that import package using "_" is not working so well 
```golang
import proto "github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"

import io "io"
import fmt "fmt"
import github_com_gogo_protobuf_proto "github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/gogo/protobuf/proto"
....
...
func (m *Envelope) MarshalTo(data []byte) (n int, err error) {
        var i int
        _ = i
        var l int
        _ = l
        if m.Origin == nil {
                return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("origin")
        } else {
                data[i] = 0xa
                i++
                i = encodeVarintEnvelope(data, i, uint64(len(*m.Origin)))
                i += copy(data[i:], *m.Origin)
        }

```

When I use ``` godep go build ``` I got the error  ```  undefined: proto.NewRequiredNotSetError ```
It seems that ``` godep go build ``` could not use the imported package with the "_"

**Comment by kr** [comment]
Can you provide a complete program that exhibits the behavior you're describing? Please also include steps to reproduce the problem and describe the behavior you expected to see.

**Comment by shinji62** [comment]
Hi,

Please try this repository  https://github.com/shinji62/firehose-to-syslog/ and the branch "feature/update-sonde-go" .

You can try a "godep go build"

Thanks

**Comment by shinji62** [comment]
@kr Are you be able to reproduce with the code I give to you ?

**Comment by freeformz** [comment]
Works fine for me.

**Comment by freeformz** [comment]
Is your godep current (go get -u github.com/tools/godep)?

**Comment by shinji62** [comment]
Still not working @freeformz can you update your local branch I forget to commit the dependency maybe that's why is was working on your env.

So please checkout feature/update-sonde-go last commit should be
```
commit e42768084ec1f1596ad37313ebd30978d641a9aa
Author: Etourneau Gwenn <gwenn.etourneau@gmail.com>
Date:   Tue Aug 4 10:42:42 2015 +0900

    Commit sonde-go
```

The error I am still getting
```bash
🍣 etourg godep go build                                                                                         ➜  ~/.gvm/pkgsets/go1.4.2/global/src/github.com/cloudfoundry-community/firehose-to-syslog [feature/update-sonde-go] ⚡
# github.com/cloudfoundry/sonde-go/events
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/envelope.pb.go:629: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/envelope.pb.go:632: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/envelope.pb.go:817: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/envelope.pb.go:825: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/error.pb.go:163: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/error.pb.go:166: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/error.pb.go:169: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/error.pb.go:307: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/error.pb.go:315: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/error.pb.go:322: undefined: proto.NewRequiredNotSetError
Godeps/_workspace/src/github.com/cloudfoundry/sonde-go/events/error.pb.go:322: too many errors
godep: go exit status 2
```

**Comment by neurogeek** [comment]
Weird. I cannot reproduce this either.

$ git log | head
commit e42768084ec1f1596ad37313ebd30978d641a9aa
Author: Etourneau Gwenn <gwenn.etourneau@gmail.com>
Date:   Tue Aug 4 10:42:42 2015 +0900

    Commit sonde-go

**Comment by shinji62** [comment]
Wow strange .. I am using go 1.4.2 on Mac Osx 10.10.2

**Comment by neurogeek** [comment]
$ go version
go version go1.4.2 darwin/amd64

On a MacOS 10.10.4

**Comment by freeformz** [comment]
Okay. I was able to duplicate the issue, but I think it's a problem with the github.com/cloudfoundry/sonde-go/events, which won't compile on master (the same commit that is vendored) with the same errors.

**Comment by freeformz** [comment]
Ahh os the problem appears to be with the vendored version of gogo protobufs.

This commit updates deps a bit...
https://github.com/shinji62/firehose-to-syslog/compare/feature/update-sonde-go...freeformz:feature/update-sonde-go

And the resulting errors are with the code in the repo.

**Comment by shinji62** [comment]
So what should I do ??

**Comment by freeformz** [comment]
@shinji62 I would try to pull in the linked patch, which updates gogo protobufs, then fix the issues in the code locally.

**Comment by shinji62** [comment]
Hi, seems resolved when using last protobuf ..
Sorry guys and thanks for the help.

**Comment by freeformz** [comment]
@shinji62 no worries.
