### ISSUE TITLE
Godep save doesn't work on ...

### ISSUE THREAD

**Issue by sim4life** [tools/godep#253]
I manually created the directory _Godep_ and the file _Godep.json_ with it's contents. After that, when I ran the `godep save ./...` command, it didn't copy all the dependencies' source code to _Godeps/_workspace_. I had to delete the manually created _Godep_ directory to get it to work.
Shouldn't godep work with or without manually created directory/files?

**Comment by kr** [comment]
Godep uses the json file to, among other things, keep track of which dependencies it has vendored. If a package is listed in Godeps.json, godep will not bother to copy its source code into Godeps/_workspace/src.
