### ISSUE TITLE
Godep messes with imports if they have project/Godeps/_workspace

### ISSUE THREAD

**Issue by aanm** [tools/godep#254]
Let's start from the beginning.
I have a project that compiles with `go build`.
I do a `godep save ./...` and every dep goes to the `Godeps` directory.
Next, I rename all imports to something like `import project/Godeps/_workspace/github.com/dep1`, the same way you have here https://github.com/tools/godep/blob/master/rewrite.go#L16
If I try to run `godep save ./...`, `godep` changes all imports back to `import github.com/dep1`.
Any workaround to keep the `project/Godeps/` on all imports? Is this a bug?

**Comment by kr** [comment]
The flag `-r` means to rewrite import paths.

You should use `godep save -r ./...` as your command.

**Comment by aanm** [comment]
@kr Thanks a lot!

**Comment by kr** [comment]
You're welcome! :balloon:
