### ISSUE TITLE
Possibly a bug in GoDep on Windows when a "save -r ./..." is used

### ISSUE THREAD

**Issue by JanSichula** [tools/godep#255]
I am on the Windows platform with GoLang 1.4.2 and whenever I try to run godep save -r ./... to prepare a project for Heroku deployment, the procedure fails with following message. Any advice will be deeply appreciated.
 
c:\Inetpub\GoLanguage\src\github.com\mpnordland\coconut>godep save -r ./...
godep: rename C:\Inetpub\GoLanguage\src\github.com\mpnordland\coconut\config.go.temp C:\Inetpub\GoLanguage\src\github.com\mpnordland\coconut\config.go: Cannot create a file when that file already exists.

**Comment by freeformz** [comment]
@JanSichula I'm going to have to setup a windows environment to test.

**Comment by freeformz** [comment]
@JanSichula Which version of windows is this?

**Comment by JanSichula** [comment]
Hello,
I am using Windows 8.1 Pro x64.







On Tue, Aug 4, 2015 at 11:15 AM -0700, "Edward Muller" <notifications@github.com> wrote:
@JanSichula Which version of windows is this?

---

**Comment by freeformz** [comment]
@JanSichula I was able to repo and make a small fix. Was exactly what I thought it was. Thanks!

**Comment by JanSichula** [comment]
@freeformz Thank you for your prompt response. From early usage of updated version, it looks to be working without a hitch and I am once again excited about GoLang and Heroku.

**Comment by freeformz** [comment]
@JanSichula Great. Let me know if you run into other troubles.
