### ISSUE TITLE
Doesn't work with reflection / martini?

### ISSUE THREAD

**Issue by cdeadlock** [tools/godep#259]
It doesn't seem as if godep works with reflection / martini.

Code example and instructions at https://github.com/cdeadlock/godep-reflection-bug

The gracefulshutdown library is normal. The graceful library is the same thing using godep.
The second library will cause a runtime error during reflection of a martini handler.

Or am I doing something else wrong here?

**Comment by freeformz** [comment]
@cdeadlock I don't understand the linked repo and what it's trying to do show.

**Comment by freeformz** [comment]
BTW: I get this error with the "graceful" version even without involving godeps at all:

```
[martini] PANIC: Value not found for type martini.Context
/usr/local/go/src/runtime/panic.go:387 (0x145c8)
	gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/Users/emuller/go/src/github.com/go-martini/martini/martini.go:175 (0xaa8a6)
	(*context).run: panic(err)
/Users/emuller/go/src/github.com/go-martini/martini/martini.go:164 (0xaa773)
	(*context).Next: c.run()
/Users/emuller/go/src/github.com/go-martini/martini/recovery.go:140 (0xafb99)
	func.004: c.Next()
/usr/local/go/src/runtime/asm_amd64.s:402 (0x3cb05)
	call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:419 (0xd78d5)
	Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:296 (0xd66cc)
	Value.Call: return v.call("Call", in)
/Users/emuller/go/src/github.com/codegangsta/inject/inject.go:102 (0x187b97)
	(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/Users/emuller/go/src/github.com/go-martini/martini/martini.go:173 (0xaa861)
	(*context).run: _, err := c.Invoke(c.handler())
/Users/emuller/go/src/github.com/go-martini/martini/martini.go:164 (0xaa773)
	(*context).Next: c.run()
/Users/emuller/go/src/github.com/go-martini/martini/logger.go:25 (0xaf29f)
	func.001: c.Next()
/usr/local/go/src/runtime/asm_amd64.s:403 (0x3cb75)
	call64: CALLFN(·call64, 64)
/usr/local/go/src/reflect/value.go:419 (0xd78d5)
	Value.call: call(fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:296 (0xd66cc)
	Value.Call: return v.call("Call", in)
/Users/emuller/go/src/github.com/codegangsta/inject/inject.go:102 (0x187b97)
	(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/Users/emuller/go/src/github.com/go-martini/martini/martini.go:173 (0xaa861)
	(*context).run: _, err := c.Invoke(c.handler())
/Users/emuller/go/src/github.com/go-martini/martini/martini.go:69 (0xa95e4)
	(*Martini).ServeHTTP: m.createContext(res, req).run()
/usr/local/go/src/net/http/server.go:1703 (0x6e51a)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1204 (0x6bfe7)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:2232 (0x3ebc1)
	goexit:
[martini] Completed 500 Internal Server Error in 8.869917ms
```

**Comment by cdeadlock** [comment]
Right sorry, forgot the runtime error:
```
[martini] Started POST /signup for 127.0.0.1:54497
[martini] PANIC: Value not found for type martini.Context
/usr/local/go/src/runtime/panic.go:387 (0x412ec8)
/home/deadlock/src/go/src/github.com/go-martini/martini/martini.go:175 (0x440216)
	(*context).run: panic(err)
/home/deadlock/src/go/src/github.com/go-martini/martini/martini.go:164 (0x4400e3)
	(*context).Next: c.run()
/home/deadlock/src/go/src/github.com/go-martini/martini/recovery.go:142 (0x445709)
	func.004: c.Next()
/usr/local/go/src/runtime/asm_amd64.s:402 (0x426035)
/usr/local/go/src/reflect/value.go:419 (0x4c6dc5)
/usr/local/go/src/reflect/value.go:296 (0x4c5bbc)
/home/deadlock/src/go/src/github.com/codegangsta/inject/inject.go:102 (0x4d8087)
	(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/deadlock/src/go/src/github.com/go-martini/martini/martini.go:173 (0x4401d1)
	(*context).run: _, err := c.Invoke(c.handler())
/home/deadlock/src/go/src/github.com/go-martini/martini/martini.go:164 (0x4400e3)
	(*context).Next: c.run()
/home/deadlock/src/go/src/github.com/go-martini/martini/logger.go:25 (0x444dcf)
	func.001: c.Next()
/usr/local/go/src/runtime/asm_amd64.s:403 (0x4260a5)
/usr/local/go/src/reflect/value.go:419 (0x4c6dc5)
/usr/local/go/src/reflect/value.go:296 (0x4c5bbc)
/home/deadlock/src/go/src/github.com/codegangsta/inject/inject.go:102 (0x4d8087)
	(*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/deadlock/src/go/src/github.com/go-martini/martini/martini.go:173 (0x4401d1)
	(*context).run: _, err := c.Invoke(c.handler())
/home/deadlock/src/go/src/github.com/go-martini/martini/martini.go:69 (0x43ef54)
	(*Martini).ServeHTTP: m.createContext(res, req).run()
/usr/local/go/src/net/http/server.go:1703 (0x47a51a)
/usr/local/go/src/net/http/server.go:1204 (0x477fe7)
/usr/local/go/src/runtime/asm_amd64.s:2232 (0x4280e1)
[martini] Completed 500 Internal Server Error in 1.272706ms
```
So this is a runtime reflection error while martini is attempting to do dependency injection. (only happens when the library is godep'd)

I just thought that perhaps I am not compiling everything with godep let me try to confirm that

**Comment by cdeadlock** [comment]
I think this was caused by me not compiling the main with godep, but the library was compiled with godep.

The problem was seen in a larger program before I made this little example. Even though I thought everything was godep compiled, apparently something must not have been. 

I guess this is an argument against reflection based dependency injection if it makes it easy to compile certain things and only seeing runtime errors.

Thanks for your time!

**Comment by freeformz** [comment]
@cdeadlock The code here work (either version): https://github.com/freeformz/grb

I updated martini after posting and before saving the deps.

**Comment by cdeadlock** [comment]
Oh thanks so much, that tree structure looks much better.
I guess its bad to have 
--lib
     --godeps
          --martini
--main
     --godeps
           --martini

**Comment by freeformz** [comment]
@cdeadlock the repo I linked to is my recommended project layout as inspired by https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091

**Comment by cdeadlock** [comment]
So I went through a restructuring of my project, and eventually had it working.
Then I somehow screwed up by calling go install without godep infront of it somewhere....

This put my system in a perpetually bad build situation where no matter what kind of cleaning I did it was still building improperly, and I would get the same runtime error.

I used 
```
godep go install -a -v -x ./...
```
and I could see that it was referencing the martini source that was NOT in the GODEPS

So I deleted the martini code from my $GOROOT/src. The next build with the same -a -v -x looked ok, and works.

**Comment by freeformz** [comment]
This is why I highly suggest using `godep save -r ./...` as name spacing compiled stuff can become an issue.

If things get to messed up you can nuke your packages directory (`$GOPATH/pkg`) and it's sub-dirs and `go install -v ./...` will show you what it's re-compiling.
