### ISSUE TITLE
godep save: dirty working tree -- godep modifying files inside the current repository

### ISSUE THREAD

**Issue by bmatsuo1** [tools/godep#260]
One of our builds was broken with a recent commit, 9805c4da6f164857a4e32dbfe83767f1118c9ad4. 

The layout of the project in question is a little strange. Commands built with godep are in subdirectories. They use some packages which were cloned with `hg` and committed to the repository before godep was introduced.

The project directory layout (a simplified form) looks something like this:

```
projectroot/
  |- subdir/
  |    |- src/mycmd/main.go
  |    `- Godeps/...
  `- go/
       |- snappy-go/...
       `- go-uuid/...
```

We have been using godep **without** the `-r` flag. And when running `godep save ./src/...` from the root/subdir/ directory an error is produced:

```
# cd /home/bmatsuo/src/projectroot/go/go-uuid/uuid; hg diff -r 7dda39b2e7d5e265014674c5af696ba4186679e9+
hg: parse error at 41: not a prefix: end
godep: dirty working tree (please commit changes): /home/bmatsuo/src/projectroot/go/go-uuid/uuid
godep: dirty working tree (please commit changes): /home/bmatsuo/src/projectroot/go/influxdb/client
godep: dirty working tree (please commit changes): /home/bmatsuo/src/projectroot/go/lmdb.exp
# cd /home/bmatsuo/src/projectroot/go/snappy-go/snappy; hg diff -r 8850bd446ad6f18a271a08aae26bdf85bdf87c7f+
hg: parse error at 41: not a prefix: end
godep: dirty working tree (please commit changes): /home/bmatsuo/src/projectroot/go/snappy-go/snappy
godep: dirty working tree (please commit changes): /home/bmatsuo/src/projectroot/go/wault
godep: error loading dependencies
```

Additionally (as stated by godep) the repository is not in a clean state after the command terminates. 

```
$ git status --porcelain
 M go/go-uuid/.hg/dirstate
 M go/snappy-go/.hg/cache/tags
 M go/snappy-go/.hg/dirstate
?? go/go-uuid/.hg/cache/branchheads-base
$
```

**Comment by freeformz** [comment]
Sorry about that. I'm not really sure how this ever worked. Why not clean this up and use godep to vendor everything?

Also can you provide a publicly accessible repository that duplicates the issue?

PS: What is your $GOPATH set to?

**Comment by bmatsuo1** [comment]
I created a small example here https://github.com/bmatsuo1/nodep.

If I knew `hg` a little better I probably would have noticed before, but it turns out that the specific reason `godep save` fails is because the two mentioned packages, go-uuid/uuid and snappy-go/snappy, have local modifications (which have been committed to git but not to the hg repo which is also committed with the source in git).

This should have been evident because `hg identify --id --debug` appends a `+`  to the end of the commit id (the effect is seen in the `hg diff` commands in the OP).

Had the files not been modified locally `godep save` would have successfully copied the dependencies within the repository. Though, the hg state files listed by `git status` in the OP are still left modified following `godep save`.

It is possible to clean things up more locally. I'm not opposed to doing that. But it wasn't broken before, and as a result we didn't fix it. And I'm only bringing it up here because something that worked stopped working. Thanks for the attention.

**Comment by freeformz** [comment]
So it looks like a mix of git and hg then. FWIW I would use godep to vendor those deps and remove them  from the other locations.
