### ISSUE TITLE
goimports support for `godep save -r`

### ISSUE THREAD

**Issue by glasser** [tools/godep#263]
I was getting frustrated that `goimports` didn't work well with `godep save -r` because (a) it ignores paths starting with `_` and (b) it prefers shorter import paths over longer ones.

So I made a fork of goimports that fixes this.

```
go get -u github.com/glasser/golang-tools/cmd/goimports
```

(The relevant change is https://github.com/glasser/golang-tools/commit/438006b089d6efbaf036d19b66ebcd3a25ec8047)

This isn't a bug, but I figured I wouldn't be the only person looking for `godep save -r` and `goimports`.  (Maybe worth mentioning in the readme?)

(Looks like goimports is going to need fixes to work with the vendor experiment.)

**Comment by freeformz** [comment]
Orly? I use `goimports` with `godep save -r` all the time.

**Comment by glasser** [comment]
I was getting the behavior that existing import lines were left alone, but when using a package in a file for the first time it would add the un-qualified version.

**Comment by freeformz** [comment]
Interesting to note. I've seen this, but I end up doing a save -r ./... to rewrite files whenever I add a new one so it hasn't bothered me. It probably should though. TBH this won't be needed at some point with `vendor/` being a thing (which is incompatible with rewrites).
