### ISSUE TITLE
godep save -r doesn't rewrite imports in subdirectories of saved dep until godep update

### ISSUE THREAD

**Issue by jmhodges** [tools/godep#265]
So, I did a `godep save -r` and my dependency tree got updated. I have deps on `A` and `B` in my code.

The `A` package has a `A/SubA` package within it that `A` depends on. In my code, the package `A/SubA` is never imported, however.

Then I went to `godep update B`, and noticed that `A`'s imports of `A/SubA` were rewritten (and previously had not!) to use my `Godeps/workspace/_src/A/SubA` path. 

I'm quite happy with `A`'s imports of `A/SubA` being rewritten, I just wish it happened:

 * when `godep save -r` had been called
 * not as a side-effect of `go update B`

(This is the corrected version of issue #264).

**Comment by jmhodges** [comment]
Ugh, I thought that was all that happened, but I'm not able to repro.

I will take some time to figure out what occurred.

**Comment by freeformz** [comment]
that would be awesome.

**Comment by jmhodges** [comment]
Okay, this must have been PEBKAC. I can't figure out how I got into that state other than running `go save` once without the -r.

I'm sorry for the noise. I'll keep my eyes out to see if I really did chance on a weird series of commands to run but that's unlikely.

**Comment by freeformz** [comment]
Yeah. it's sub optimal (save vs. save -r). We could record what was used in Godeps.json, but that will also cause it's own set of problems at times. Plus rewriting should be going away pending the outcome of the 1.5 vendor experiment, so I really haven't had enough incentive to do anything.

**Comment by jmhodges** [comment]
That's an extremely reasonable reaction. Thank you for the nice software.
