### ISSUE TITLE
What are the right steps to avoid saving testing dependencies?

### ISSUE THREAD

**Issue by hermanjunge** [tools/godep#274]
Currently, I'm forced to store into the `vendor` directory my testing dependencies. What is the right way to `godep save` my dependencies avoiding the ones referenced in the `_test` files?

Do we fill a backlog ticket instead for this feature?

Regards.

**Comment by freeformz** [comment]
#276 should fix this once I get it reviewed by other maintainers and merged.

**Comment by hermanjunge** [comment]
Thanks @freeformz, looking forward to it.

**Comment by hermanjunge** [comment]
Closing issue, as it has been solved.
