### ISSUE TITLE
Cannot save when old deps are missing from $GOPATH

### ISSUE THREAD

**Issue by ahmetalpbalkan** [tools/godep#277]
I started adding godep my project with `GO15VENDOREXPERIMENT` enabled.

I did `godep save` and it all worked, I have a `Godeps/` directory with the json and a `vendor/` directory with the dependencies. It looks like this:

```
$ tree -d vendor
vendor
└── gopkg.in
    └── yaml.v2

2 directories
```

The project builds fine etc and I can see `vendor/` is used by Go 1.5.

Now I want to add another dependency, but `godep save` says it cannot find the earlier dependency:

```
$ go get gopkg.in/check.v1
$ godep save
godep: cannot find package "gopkg.in/yaml.v2" in any of:
        /usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
        /home/azureuser/gopath-docker-extension/src/gopkg.in/yaml.v2 (from $GOPATH)
godep: error loading dependencies
```

According to this output, it does not look at `vendor/` for that..

I tried to do `GOPATH=$GOPATH:`pwd`/vendor godep save` but that didn't work simply because `vendor/` directory does not have src/ path... 

Any suggestions?

**Comment by freeformz** [comment]
@ahmetalpbalkan I can't duplicate this. I added an import for check.v1 to a main.go file and then used the C struct from there and godep save worked and did the right thing (added the dep to Godeps/Godeps.json and vendored the files in vendor/)

Are you using check in a test file? I tried that as well (making a main_test) and `godep save` DTRT as well.

What Go version are you using?
What Godep version are you using?
What is your $GOPATH?

**Comment by ahmetalpbalkan** [comment]
Oh well I couldn't repro either. Thanks @freeformz for taking a look.

**Comment by freeformz** [comment]
Ahh. I was able to repro! Had an idea after posting that.

I had to delete (remove from my $GOPATH) `gopkg.in/yaml.v2`. A `godep restore` solved that.

Maybe you temporarily had a different $GOPATH set? One without `gopkg.in/yaml.v2` in it?

**Comment by ahmetalpbalkan** [comment]
@freeformz not really.

**Comment by ahmetalpbalkan** [comment]
maybe it was because the `gopkg.in/check.v1` is not imported in the program code but test code. Now that doesn't repro if I `import _ "gopkg.in/check.v1"` as well.

**Comment by freeformz** [comment]
well I can duplicate by removing `gopkg.in/yaml.v2` from $GOPATH. I think this is a bug in `vendor/`support because the go tool should be able to find the package in the vendor directory. We're just doing `go list -e -json`.

**Comment by freeformz** [comment]
ahh I forgot that the go tooling internally add `vendor` to all things in `vendor`. So it can't find it becuse go list returns `"github.com/freeformz/t/vendor/gopkg.in/yaml.v2"` in my case.

**Comment by freeformz** [comment]
So currently godep strips out the vendor part of the path and then passes a constructed list of all flattened paths to `go list -e -json`, which then can't find `gopkg.in/yaml.v2` because in the context of `go list` in my test app it's really `github.com/freeformz/t/vendor/gopkg.in/yaml.v2`. This isn't trivial to fix AFAICT, especially when dealing with `vendor/` behavior vs. `Godeps/_workspace`. But probably worth the investment in time.

**Comment by freeformz** [comment]
PS: For now the best way to handle new `godep save` is to do a `godep restore` before hand, ensuring that your GOPATH contains all of the required dependencies at the right versions before doing the new save.
