### ISSUE TITLE
godep restore fails for golang.org

### ISSUE THREAD

**Issue by liyichao** [tools/godep#279]
When I run `go restore`, it reports these errors:

```
package github.com/influxdb/influxdb
	imports golang.org/x/crypto/bcrypt: unrecognized import path "golang.org/x/crypto/bcrypt"
godep: restore: exit status 1
package golang.org/x/crypto/bcrypt: unrecognized import path "golang.org/x/crypto/bcrypt"
godep: restore: exit status 1
package golang.org/x/crypto/blowfish: unrecognized import path "golang.org/x/crypto/blowfish"
godep: restore: exit status 1
```

while I grep `golang.org/x/crypto/bcrypt` in my repo:

```
  halo git:(master) ag 'golang.org/x/crypto/bcrypt'
Godeps/_workspace/src/github.com/influxdb/influxdb/LICENSE_OF_DEPENDENCIES.md
19:- golang.org/x/crypto/bcrypt

Godeps/_workspace/src/github.com/influxdb/influxdb/meta/store.go
26:	"git.in.zhihu.com/infrastructure/halo/Godeps/_workspace/src/golang.org/x/crypto/bcrypt"

Godeps/Godeps.json
62:			"ImportPath": "golang.org/x/crypto/bcrypt",
```

**Comment by freeformz** [comment]
What revision of `github.com/influxdb/influxdb` is vendored? What is the "Rev" key for it from your Godeps/Godeps.json file?

**Comment by liyichao** [comment]
```
	{
			"ImportPath": "github.com/influxdb/influxdb",
			"Comment": "v0.9.4.1",
			"Rev": "c4f85f84765e27bfb5e58630d0dea38adeacf543"
		}
```

**Comment by freeformz** [comment]
Also, what version of godep are you using?

**Comment by freeformz** [comment]
while testing this I get the same thing with a simple go get -u of github.com/influxdb/influxdb (before 

```console
$ go get -u github.com/influxdb/influxdb
package golang.org/x/crypto/bcrypt: cannot find package "golang.org/x/crypto/bcrypt" in any of:
	/usr/local/go/src/golang.org/x/crypto/bcrypt (from $GOROOT)
	/Users/emuller/go/src/golang.org/x/crypto/bcrypt (from $GOPATH)
```

I ended up having to remove $GOPATH/src/golang.org/x/crypto from my $GOPATH. I suspect that the golang.org/x/crypto package is somehow incomplete and suggest removing it and then either re-fetching or using `godep restore`.

**Comment by liyichao** [comment]
Your error message is different from me. I also find that there is no crypto thing in my $GOPATH.

**Comment by freeformz** [comment]
What version of go are you using?

**Comment by liyichao** [comment]
1.5

**Comment by freeformz** [comment]
What happens if you run `golang.org/x/crypto/bcrypt` ? What is the output of that?

**Comment by liyichao** [comment]
You mean `godep go get golang.org/x/crypto/bcrypt` or `go get golang.org/x/crypto/bcrypt`?

**Comment by freeformz** [comment]
go get ....

**Comment by liyichao** [comment]
It reports error:

```package golang.org/x/crypto/bcrypt: unrecognized import path "golang.org/x/crypto/bcrypt"```

**Comment by freeformz** [comment]
Are you in China?

If so the great firewall blocks golang.org AFAIK and you will need to do the following:

```console
$ mkdir -p $GOPATH/src/golang.org/x
$ cd $GOPATH/src/golang.org/x
$ git clone https://go.googlesource.com/crypto
```

**Comment by HuKeping** [comment]
So famous the GFW, @freeformz 's solution work for me, thanks.

**Comment by haydenzhourepo** [comment]
Chinese need a go package mirror, just like composer Chinese mirror!
