### ISSUE TITLE
bzr support for -copy=false

### ISSUE THREAD

**Issue by kjk** [tools/godep#28]
I'm using the latest godep (as of 14-11-2013). It looks like it should support bzr but it doesn't work for me.

My test file:

krzysztofs-mbp:test_godep kkowalczyk$ cat main.go
```
package main

import (
	"fmt"
	"launchpad.net/goamz/aws"
)

func main() {
	fmt.Printf("Test for godep\n")
	_ = aws.Auth{"foo", "bar"}
}
```

```
krzysztofs-mbp:test_godep kkowalczyk$ godep save -copy=false
godep: Unsupported sandbox VCS: Bazaar
godep: Instead, run: godep save -copy .
```

`godep save` works, but I would really like the `-copy=false` option to work.

Can the problem be related to handling sub-packages (i.e. `launchpad.net/goamz/aws` is a sub-package of `launchpad.net/goamz`) ?

**Comment by freeformz** [comment]
I am closing this because it's no longer possible to use -copy=false (since 754ee6f4e0e5fc8d0ef2692fb239d15c7a09dd84).
