### ISSUE TITLE
When using GO15VENDOREXPERIMENT path should return vendor directory

### ISSUE THREAD

**Issue by lox** [tools/godep#288]
When I have `GO15VENDOREXPERIMENT=1`, I'd expect `godep path` to return `vendor` so that anything using it to manually set the gopath would refer to the `vendor` dir. It currently still returns the non-existent `Godeps/_workspace` directory. Am I doing this wrong?

**Comment by kr** [comment]
If you have `GO15VENDOREXPERIMENT=1` in your environment, you don't need to use `godep path` at all.

**Comment by lox** [comment]
That's the theory :) In practice lots of tools like goimports don't support
vendor yet, so having godep path return the right thing means it's easier
to write portable shellscript wrappers in the interim.

**Comment by kr** [comment]
> having godep path return the right thing means it's easier
to write portable shellscript wrappers in the interim

It sounds like you're asking for a new feature. The command `godep path` returns a workspace—a directory suitable for including in the `GOPATH` list. The vendor directory is not a workspace and it can't usefully be included in your `GOPATH`. When you're using `GO15VENDOREXPERIMENT=1`, there is no "right thing" for `godep path` to print.

However, in that case, it's trivial to construct the correct path yourself, so I don't see how a godep feature would make writing portable shell script wrappers any easier.

**Comment by kr** [comment]
But I do agree there's a bug in godep here: if `GO15VENDOREXPERIMENT=1` is in the environment, then `godep path` should print a helpful error message and exit with a nonzero status code.
