### ISSUE TITLE
godep versions should receive git tags

### ISSUE THREAD

**Issue by flavorjones** [tools/godep#289]
Currently it looks like when a new godep version is released, `Changelog.md` and `version.go` are bumped (as in 0450b47), but no tag is created for the version on github origin.

It's a popular convention to tag releases. This notifies the world in a structured way that there's a new version available. Many tools watch for new tags, and in fact Github is smart enough to create a "release" skeleton on the project "Releases" page (e.g. https://github.com/tools/godep/releases).

I'd like to humbly petition the godep core maintainers to adopt this convention.

Thank you for reading!

**Comment by freeformz** [comment]
I pushed a tag and I'll endeavor to do that in the future as well.

**Comment by flavorjones** [comment]
Awesome, thank you!
