### ISSUE TITLE
Godep silently failing to vendor code.google repo

### ISSUE THREAD

**Issue by awsmsrc** [tools/godep#293]
Running 
```
godep save 
```

Appears to work just fine, there is no error output and the vendor directory and Godep directory are created

packages hosted on github are vendoring fine
"github.com/joho/godotenv"

this package does not get vendored
"code.google.com/p/go-uuid/uuid"

I know this issue is vague on details, happy to provide anything i can

**Comment by freeformz** [comment]
I was able to reproduce with a simple test project. :-( Looking.

**Comment by freeformz** [comment]
Well `godep save -v` tells me what's going on:

```console
$ godep save -v
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/LICENSE
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/dce.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/doc.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/hash.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/json.go
godep: save: skipping test file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/json_test.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/node.go
godep: save: skipping test file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/seq_test.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/time.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/util.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/uuid.go
godep: save: skipping test file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/uuid_test.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/version1.go
godep: save: skipping untracked file: /Users/emuller/go/src/code.google.com/p/go-uuid/uuid/version4.go
```

Def a bug.

**Comment by client9** [comment]
note: "code.google.com/p/go-uuid/uuid" and everything on code.google.com is going to be shutdown (although when I'm not sure).  I believe with go 1.5 a warning is emitted.

The item in question should be updated to point to https://github.com/pborman/uuid

Hopefully that will solve your immediate issue, but doesn't solve the silent failure.

**Comment by freeformz** [comment]
@client9 it would because that uses git. Basically hg had a bug in it when there were sub packages in play. This is now resolved.

@awsmsrc You should switch to the package @client9 mentions though regardless.

**Comment by awsmsrc** [comment]
@freeformz already switched ;)

thanks for the note @client9 

Will a go get now upgrade godep?

**Comment by freeformz** [comment]
`go get -u github.com/tools/godep` will upgrade your local install of godep.

You can now also download binaries as well from https://github.com/tools/godep/releases, but `go get -u` is easier if you already have a working Go setup.
