### ISSUE TITLE
no buildable go source files

### ISSUE THREAD

**Issue by netroby** [tools/godep#294]
```
godep get github.com/gin-gonic/contrib
package github.com/gin-gonic/contrib: no buildable Go source files in /home/huzhifeng/go/src/github.com/gin-gonic/contrib
godep: exit status 1
```

Error message when run godep get command
I am running go 1.5.1 with export GO15VENDOREXPERIMENT=1

**Comment by freeformz** [comment]
There are no files in contrib, they are in sub packages so you need to do `godep get github.com/gin-gonic/contrib/<sub package you want>`
