### ISSUE TITLE
godep version ?

### ISSUE THREAD

**Issue by client9** [tools/godep#309]
Hi guys,

didn't know you guys did versioned binary releases.  Interesting!

It would be nice to know what version you have via `godep version` (version here is really more like "last milestone" since you might be in an intermediate commit)

Or has this idea already been rejected?  I didn't see it in the closed tickets but "version" in the context of godep is highly overloaded, so I might have missed it.

regards,

n

**Comment by freeformz** [comment]
@client9 Any commits merged to master should include a version bump and a changelog entry. Since that's a manualish process it hasn't gone as smoothly as I'd like. Improvements to the process that continue to maintain godep's `go get`ableness are appreciated.

**Comment by client9** [comment]
Ahh intersting ok.

as intermediate step I was thinking of something like this

```bash
$ godep version
v20
```

or something to let you know what version (or last tagged version) is running.  Thats probably 10 LOC max since you have the version info in go-code already.

That won't fix the process, but should help.

**Comment by freeformz** [comment]
That already exists https://github.com/tools/godep/blob/58b9be6061a97e574c0695d6f15031f8b01a9629/main.go#L83-L86

**Comment by client9** [comment]
hilar.. I didn't try that since the "godep help" didn't list it.  I'll make a pull request adding that to help page.
thx!
