### ISSUE TITLE
godep update doesn't have a -t flag

### ISSUE THREAD

**Issue by jmhodges** [tools/godep#312]
There is no way to update a package but keep test files.

`godep update -t <pkg>` fails with a cli error:

    flag provided but not defined: -t

Also, if you run `godep update` and had previously `godep save`'d with the `-t` flag, those test files will now be removed.

**Comment by freeformz** [comment]
-t wasn't propagated to update. This should be fixed. If you have time/interested in doing a PR, great. If not I'll probably get to it either later today or tomorrow.
