### ISSUE TITLE
trailing slashes in godep update confuse godep

### ISSUE THREAD

**Issue by jmhodges** [tools/godep#313]
Including a trailing slash causes `godep update` to not recognize a path. A minor thing but causes confusion and digging through Godeps.json files.

    $  godep update github.com/golang/protobuf/proto/
    godep: not in manifest: github.com/golang/protobuf/proto/

**Comment by kr** [comment]
It would be better to fix this by calling path.Clean on the command line arg before supplying it to matchPattern. The function matchPattern is a lower-level routine that expects to get a true import path.

In the go tool, this is the difference between
https://github.com/golang/go/blob/master/src/cmd/go/main.go#L347-L355

and matchPattern:
https://github.com/golang/go/blob/master/src/cmd/go/main.go#L476

**Comment by kr** [comment]
Using path.Clean would fix not just trailing slashes, but all unclean paths, such as `github.com/golang/protobuf///.//proto`.

**Comment by freeformz** [comment]
Thanks @kr. See #316
