### ISSUE TITLE
godep restore to use local Godeps?

### ISSUE THREAD

**Issue by ddysher** [tools/godep#319]
Thanks for making the great tool!

I'm having a slow network so everytime I run `go restore`, it takes fair amount of time.  

I searched github but didn't find a relavent discussion.  What's the reason for not restoring from Godeps, is it because not everyone commits Godeps directory?  Is it possible to make it an optional feature?

**Comment by freeformz** [comment]
What would restoring from the Godeps workspace mean? We don't vendor the entire repository of packages being used, including the commit history, just the packages being used and the commit hash.

**Comment by ddysher** [comment]
Ok, thanks.  I think I misunderstood how it works.  If there is only package and commit hash, then current  restore workflow is sound.

**Comment by matejkramny** [comment]
@freeformz why do we need to commit _workspace into git if it isn't being used to restore the packages?

**Comment by freeformz** [comment]
@matejkramny it's what is used to build a project and the only way to guarantee that the code is available is to commit it along with our own code.

**Comment by matejkramny** [comment]
Ok I understand that, but i am questioning why the tool then fetches the git repos during `godep restore`.

**Comment by freeformz** [comment]
To fully restore the repos that the packages live in to the $GOPATH. If we didn't do that there would be missing packages/tests/etc in your $GOPATH.

FWIW: My plan is to remove `restore` sometime after most people appear to be using go1.6+ and using the GO15VENDOREXPERIMENT. So probably around the go1.7 timeframe. I'm hoping other maintainers/users agree with that (TBD).

**Comment by matejkramny** [comment]
Oh right. Understand.

Thank you for explaining.
