### ISSUE TITLE
godep save reports dirty working tree when ran from git hook

### ISSUE THREAD

**Issue by bojan-embroker** [tools/godep#327]
Running "godep save ./..." works fine, but when i put it into get pre-commit hook and try to commit, I get "godep: dirty working tree (please commit changes): ..."

It worked fine with git 1.9.2. I started having this issue when I upgraded to 2.6.2.

Is there anything that can be done in godep to fix this?

**Comment by freeformz** [comment]
Try unsetting $GIT_DIR maybe?

**Comment by bojan-embroker** [comment]
Thanks for the suggestion. Unfortunately, I did that already and it doesn't help.

**Comment by freeformz** [comment]
Oh duh on me. That's probably because godep save adds files to the repository, leaving it in a dirty state.

**Comment by bojan-embroker** [comment]
Can you please tell me what this message from godep actually means i.e. what is godep trying to do and what is failing.

Without understanding that, it just sounds like a chicken and egg problem: I want to run godep save in pre-commit hook, but it won't run in it because I didn't commit.

**Comment by freeformz** [comment]
godep save will will copy deps to `<proj>/Godeps/_workspace/src`. At that point the tree is dirty. At the very least least the hook needs to `git add -A Godeps` after the godep save.

**Comment by bojan-embroker** [comment]
I don't want to add anything to git automatically in pre-commit hook and not give committer opportunity to check and see what exactly he is committing. I want to prevent commit if committer forgot to do "godep save ./...", do it for him and tell him to do git add -A so he can review changes before committing.

The problem is that when I run "godep save ./..." in the folder nothing is changed as I didn't add any new dependencies, but when I do the same from pre-commit hook I get "godep: dirty working tree (please commit changes): ...". So basically, the hook isn't letting me commit even though there are no new dependencies.

Here is the whole hook:

```bash
#!/bin/bash

set -e

unset GIT_DIR
unset GIT_INDEX_FILE

export GOPATH=$1

$1/bin/godep save ./...
NOGODEPCHANGES="$(git ls-files . --exclude-standard --others --modified | grep Godeps | wc -l)"

if [ $NOGODEPCHANGES -gt 0 ]; then
  cat <<\EOF
ERROR: Some Go dependencies have been updated with `godep save`
ERROR: Please add them to your commit.
EOF
  exit 1
fi

exit 0
```
It worked as expected with git 1.9.2 and started giving that  "godep: dirty working tree (please commit changes): ..." message when I upgraded to 2.6.2.

**Comment by Son-Lam** [comment]
I am having the same issue.

Would you have any fix for it. It work on Go 1.5.3 but fails on Go 1.6rc1

**Comment by freeformz** [comment]
Tested this and with a few minor changes to the hook, it works currently.

This is the hook I used....

```bash
#!/bin/bash

set -e

unset GIT_DIR
unset GIT_INDEX_FILE

$GOPATH/bin/godep save ./...
NOGODEPCHANGES="$(git ls-files . --exclude-standard --others --modified | grep Godeps | wc -l)"

if [ $NOGODEPCHANGES -gt 0 ]; then
  cat <<\EOF
ERROR: Some Go dependencies have been updated with `godep save`
ERROR: Please add them to your commit.
EOF
  exit 1
fi

exit 0
```

**Comment by bojan-embroker** [comment]
That change doesn't fix my problem unfortunately.

**Comment by freeformz** [comment]
@bojan-embroker I don't understand your problem then as this worked for me.
