### ISSUE TITLE
'godep update ...' sometimes fails with an error message

### ISSUE THREAD

**Issue by netroby** [tools/godep#332]
currently we can only update package by following command

```
cat Godeps/Godeps.json | grep ImportPath | awk -F\" '{print $4}' | grep -v gosense| xargs godep update

```

Would you please add support for read all packages from Godeps.json, and update them ?

**Comment by kr** [comment]
Try `godep update ...` (three literal dots).

**Comment by kr** [comment]
This should absolutely be documented better. There could be an example in the help output for `godep help update`.

**Comment by netroby** [comment]
It does not working

```
godep update ...
godep: not in manifest: ../..
godep: no packages can be updated

```

**Comment by kr** [comment]
This sounds like a bug.

**Comment by gittycat** [comment]
I'm also hitting this bug fwiw
