### ISSUE TITLE
godep save thinks everything's unversioned

### ISSUE THREAD

**Issue by imajes** [tools/godep#339]
I'm certain this is a misconfiguration from go convention, and i'm too blame, but I can't figure it out.

```go list -json``` returns what looks valid:

https://gist.github.com/imajes/8ae3025edb35c140446d

but, ```go save -v ./...``` seems to disagree:

https://gist.github.com/imajes/412835d9393eac768faf

and creates ```Godeps/``` with a completely empty ```_workspace```.

would anyone be able to help me figure out what's going wrong?

**Comment by freeformz** [comment]
What is the output of `echo $GOPATH` and `pwd` when you run these commands?

**Comment by imajes** [comment]
hey @freeformz - 

good call.

```
% echo $GOPATH
/Users/james/src/go
% pwd         
/Users/james/Projects/chexology/moonraker
```

But, when i run the commands from within GOPATH, i get the same results.

**Comment by imajes** [comment]
in other words, i think i'm conforming to the go code layout/organization idiom as best as i can, though it's not as easy to work when i'm in ```$GOPATH```. my ```Projects/chexology/moonraker``` directory is a symlink _into_ the correct folder in ```GOPATH```, so it should all work as expected.

**Comment by freeformz** [comment]
Turns out @imajes's $GOPATH is symlinked out of a Dropbox folder. `git rev-parse --show-toplevel` shows the absolute path, so none of the `Contains()` calls finds the file.
