### ISSUE TITLE
Does not compile on golang 1.2 or 1.3

### ISSUE THREAD

**Issue by robdimsdale** [tools/godep#344]
From the README:

> This tool assumes you are working in a standard Go workspace, as described in http://golang.org/doc/code.html. We require Go 1.1 or newer to build godep itself

but since https://github.com/tools/godep/commit/bd1a5cd1a59bff09fa53022436490eb03fb0dc4c there is a reference to `build.MultiplePackageError` on https://github.com/tools/godep/commit/bd1a5cd1a59bff09fa53022436490eb03fb0dc4c#diff-a54693ac2ffd17a27b00b97e88aacce0R163 - this does not exist in golang 1.2 or 1.3 (I didn't check golang v1.1)

If golang 1.2 and 1.3 are not supported, can we update the README to mention this. If, on the other hand, support for golang 1.2 and 1.3 are desired, is there a way to support them?

Thanks

**Comment by kr** [comment]
Now that @freeformz is making binary releases of godep, it seems like there's less reason to spend effort making godep compile with older Go versions.

**Comment by freeformz** [comment]
FWIW: My plan is to really only support "compilation" (go get github.com/tools/godep) against the current major version of go and the last major version of go. Currently go1.5.* & go1.4.* basically.

PS: Once #352 lands this should be fixed.

**Comment by robdimsdale** [comment]
Great. Thanks for the responses. Sounds like compilation in older versions might be fixed soon. If not, no worries as the binary releases should also suffice.

@freeformz would it be possible to update the README to reflect what you said above about only supporting the current and most recent major versions of golang?

**Comment by freeformz** [comment]
@robdimsdale I updated the readme slightly to reflect the new versions. If you feel that's not sufficient a PR would be great!

PS: #352 is merged as v34 and should fix this problem. Can you confirm?

**Comment by robdimsdale** [comment]
@freeformz that's fantastic, thank you very much.
