### ISSUE TITLE
Godep save issue when importing lib/pq

### ISSUE THREAD

**Issue by njohns-grovo** [tools/godep#348]
Hello,
I'm running into a little bit of an issue vendoring dependencies that includes `import _ "github/lib/pq"`

Error: 
`godep: found packages oid (doc.go) and main (gen.go) in $GOPATH/src/github.com/lib/pq/oid`

Directory Tree
```
.
├── main.go
└── subp
    └── subp.go
```

main.go:
```go
package main

import (
	"fmt"
	"github.com/taion809/godeptest/subp"
	"log"
)

func main() {
	fmt.Println("Testing godep save -r ./...")
	s, err := subp.NewSubp("postgres", "postgres://root:root@localhost:5432/db")
	if err != nil {
		log.Fatal(err)
	}

	defer s.Close()
	err = s.Ping()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Worked")
}
```

subp/subp.go:
```go
package subp

import (
	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
)

type Subp struct {
	db *sqlx.DB
}

func NewSubp(driver, addr string) (*Subp, error) {
	db, err := sqlx.Open(driver, addr)
	if err != nil {
		return nil, err
	}

	return &Subp{db: db}, nil
}

func (s *Subp) Close() error {
	if s.db != nil {
		return s.db.Close()
	}

	return nil
}

func (s *Subp) Ping() error {
	return s.db.Ping()
}
```

**Comment by njohns-grovo** [comment]
Update, I reverted to 8956568036ef22a1bad9e349d9b3a991cd6a744f and it's functioning as expected

**Comment by freeformz** [comment]
@njohns-grovo Yeah [v32](https://github.com/tools/godep/tree/v32) should be okay atm. Sorry about that. I think I was being too optimistic with my use of build.Context. I'll add a test to duplicate this and bang on the new package evaluation code to fix it.
