### ISSUE TITLE
How to add any folder/files in GoDeps workspace?

### ISSUE THREAD

**Issue by codefx9** [tools/godep#355]
We are using GRPC Gateway which needs `$GOPATH/src/github.com/gengo/grpc-gateway/third_party/googleapis` as part of the build process. We would like to add this into GoDeps folder. This will help us avoid build issues. Is there a way to do this?

**Comment by freeformz** [comment]
`godep save -r ./... github.com/gengo/grpc-gateway/third_party/googleapis/...`

Rewrites will work sanely once #343 is merged (likely next week pending rebase / update by author).

That should vendor the `github.com/gengo/grpc-gateway/third_party/googleapis` and all it's sub packages assuming they're not messed up in some way (or a bug).
