### ISSUE TITLE
Godeps format compatibility and evolution

### ISSUE THREAD

**Issue by kr** [tools/godep#36]
In #35, @mreiferson writes:

> Relatedly, I'm curious to hear your thoughts on "versioning" of godep itself. Its been fantastic that as it evolved it has maintained backwards compatibility and I think the change as you've implemented here continues that. Still, it might be important to begin to lay the groundwork so something can be embedded in the manifest identifying compatibility, making it a little easier to manage the possibility of needing to make breaking changes.

**Comment by freeformz** [comment]
`godep version` now works and prints a version.
Godep is likely (but not finally) going to use https://github.com/kardianos/vendor-spec as per #270.

So I'm going to close this. Please re-open and update if I'm wrong.

Thanks!.
