### ISSUE TITLE
GO15VENDOREXPERIMENT is GOOS-specific

### ISSUE THREAD

**Issue by krishicks** [tools/godep#360]
Previously we were able to just run `godep save ./...` to get all of our dependencies for all platforms.

With `GO15VENDOREXPERIMENT=1` we're only getting dependencies specific to the platform where `godep save ./...` is run. In this case we were missing Windows dependencies because deps were saved from an OS X machine.

The workaround is to run `GO15VENDOREXPERIMENT=1 GOOS=windows godep save ./...`, which then adds the missing dependencies (without removing the non-Windows dependencies).

This was tested on go1.5.2 darwin/amd64.

**Comment by freeformz** [comment]
what is your godep version?

**Comment by freeformz** [comment]
FWIW: until v33 `godep save ./...` would only save deps for the current platform.

**Comment by krishicks** [comment]
I'm away from that machine now but I will check tomorrow.

**Comment by krishicks** [comment]
Oops, I was on a super old version of godep. v14.

It's hard to tell the current version of godep as there's no 'version' command. I had to go to the GOPATH and look at the tags.

**Comment by freeformz** [comment]
`godep version` should work for any version of godep after ~v1 (IIRC).

**Comment by krishicks** [comment]
I am not sure how I missed that. Maybe I was just doing --version and didn't read the helpful text which said 'version' was a command.
