### ISSUE TITLE
zsh: command not found: godep

### ISSUE THREAD

**Issue by Entalpi** [tools/godep#373]
For some reason my shell can't find godep, I am literally out of ideas why it does not find 'godep'. 
![screen shot 2015-12-19 at 22 56 17](https://cloud.githubusercontent.com/assets/1652130/11915355/de447824-a6a3-11e5-8e8c-fc0d36d7b88e.jpg)

**Comment by Entalpi** [comment]
This helped resolve it; https://forums.docker.com/t/godep-go-install-not-working/2607

![screen shot 2015-12-20 at 17 54 08](https://cloud.githubusercontent.com/assets/1652130/11918929/bbaf53e8-a742-11e5-97f7-2fc85131e67d.jpg)

**Comment by kr** [comment]
That looks like a good fix. There are two slight refinements you might want to make:

1. You don't need `$GOPATH` in there; it's unlikely any executables will be put there.
2. You don't need to set `GOBIN`, you can just put the bin directory directly in path as `$GOPATH/bin`.

So, putting those together it would be:

```shell
export PATH=$GOPATH/bin:$PATH
```
