### ISSUE TITLE
Godep restore fails with -v, works without

### ISSUE THREAD

**Issue by thockin** [tools/godep#374]
If I `godep restore` kubernetes it works (well, it produces a bunch of source - I have doubts about it being right, that's what I am trying to find out).

If I `godep restore -v` it fails:

I get a whole lot of this, and then an exit(1).

```
execute &{Path:/usr/local/go/bin/go Args:[go get -d -v github.com/appc/spec/schema] Env:[] Dir: Stdin:<nil> Stdout: Stderr: ExtraFiles:[] SysProcAttr:<nil> Process:0xc2082546e0 ProcessState:exit status 0 lookPathErr:<nil> finished:true childFiles:[0xc20802e408 0xc20802e428 0xc20802e428] closeAfterStart:[0xc20802e408 0xc20802e428] closeAfterWait:[0xc20802e420] goroutine:[0x497700] errch:0xc2082ff020}godep: restore: exec: already started
```

**Comment by freeformz** [comment]
Pleas try again with the current version of godep.

**Comment by thockin** [comment]
Thanks, it turns out I was NOT running at head, as I thought.
