### ISSUE TITLE
godep restore + godep save changes revisions

### ISSUE THREAD

**Issue by thockin** [tools/godep#375]
I just did a `godep restore` on kubernetes followed by `godep save ./...` - I expected this to be a no-op, but I wanted to verify.  Instead, I find that ONE particular library has had it's version changed to the current tip of the master branch.

I can't figure out why.  `godep restore -v` is failing (#374 here)

Specifically:

```
                {
                        "ImportPath": "github.com/coreos/go-systemd/dbus",
-                       "Comment": "v2-27-g97e243d",
-                       "Rev": "97e243d21a8e232e9d8af38ba2366dfcfceebeba"
+                       "Comment": "v4-15-ga831f36",
+                       "Rev": "a831f36d09de8f095c28eeee839df52e9de5031f"
                },
```

Any clues would be great?  Godep is kind of inscrutable.

**Comment by freeformz** [comment]
What version of godep? (godep version)

**Comment by thockin** [comment]
I did a 'go get -u' yesterday

**Comment by kr** [comment]
> I did a 'go get -u' yesterday

Ok, but what version do you have? It would be helpful if you can run `godep version` and paste the output here so we know exactly what you have.

**Comment by thockin** [comment]
It's good to have assumptions challenged.  It turns out I was not running at head, despite go get -u.  v41 seems to work but for a different issue, which I will file it if is not open already
