### ISSUE TITLE
godep save with GO15VENDOREXPERIMENT doesn't save everything

### ISSUE THREAD

**Issue by thockin** [tools/godep#376]
godep v41 (from head today)

`godep restore && godep save ./...` show no diffs.

`godep restore; export GO15VENDOREXPERIMENT=1; rm -rf Godeps; godep save ./...` returns 0, but there are diffs to Godeps.json and there's a LOT of things missing from my vendor/ dir, even stuff that is listed in Godeps.json

I can't tell if the other open issues are related - these are things that are directly referenced by code in ./... - not transitive.

**Comment by freeformz** [comment]
Confirmed, closing in favor of #358
