### ISSUE TITLE
godep reports error when restoring goose

### ISSUE THREAD

**Issue by lziest** [tools/godep#379]
It appears that the latest build of godep gives me the following error:
$ go get github.com/tools/godep 
7.23s
$ godep restore
godep: Dep (bitbucket.org/liamstask/goose/lib/goose) restored, but was unable to load it with error:
	Package (github.com/go-sql-driver/mysql) not found
godep: Error checking some deps.
The command "godep restore" failed and exited with 1 during .

**Comment by freeformz** [comment]
What repository are your trying to restore?

**Comment by lziest** [comment]
Our repo is https://github.com/cloudflare/cfssl
I guess the following line triggers the error in CI. I need to double-check with my local env
https://github.com/cloudflare/cfssl/blob/master/Godeps/Godeps.json#L111

**Comment by lziest** [comment]
I guess we have solved the problem, apparently the package 'goose' in question is not longer used in our code. Removing that in Godeps.json solves the problem. and godep is now more strict about it?
