### ISSUE TITLE
[Windows] godep save ./... memory leaks

### ISSUE THREAD

**Issue by ab22** [tools/godep#383]
**Windows** = 8.1 64bit
**Go** = 1.5.2
**GOVENDOREXPERIMENT** = 1
**Godep** >= v38

When running: ```godep save ./... ``` godep.exe starts growing on memory until it freezes the computer. The debug shows that it gets stuck when running ```Adding search dir: c:\vendor\encoding\gob``` on an infinite loop. I switched to different versions of godep and found that v37 works without any issues.

Attached is the debug log from running: ```godep save -d ./... ```.
[output.txt](https://github.com/tools/godep/files/71935/output.txt)

It looks like the logic is fine except for one small detail. When running the ``findDirForPath`` this is what the debug prints:

**Edit:**
```
-------------------------
Adding search dir: c:\Users\aB\gocode\src\github.com\ab22\abcd\vendor\encoding\gob
base: c:\Users\aB\gocode\src\github.com\ab22\abcd
cr: C:\Users\aB\gocode
-------------------------
Adding search dir: c:\Users\aB\gocode\src\github.com\ab22\vendor\encoding\gob
base: c:\Users\aB\gocode\src\github.com\ab22
cr: C:\Users\aB\gocode
-------------------------
Adding search dir: c:\Users\aB\gocode\src\github.com\vendor\encoding\gob
base: c:\Users\aB\gocode\src\github.com
cr: C:\Users\aB\gocode
-------------------------
Adding search dir: c:\Users\aB\gocode\src\vendor\encoding\gob
base: c:\Users\aB\gocode\src
cr: C:\Users\aB\gocode
-------------------------
-------------------------
Adding search dir: c:\Users\aB\gocode\vendor\encoding\gob
base: c:\Users\aB\gocode
cr: C:\Users\aB\gocode
-------------------------
```

If you notice `c:\Users\aB\gocode` != `C:\Users\aB\gocode`.

**Comment by freeformz** [comment]
This should be closed by v45. If not please re-open. Thanks!
