### ISSUE TITLE
-v prints nothing, -d is insane

### ISSUE THREAD

**Issue by thockin** [tools/godep#388]
I'm trying to figure this out:

```
$ godep save -v ./...
godep: WARNING: Recorded go version (go1.5.1) with minor version string found.
godep: WARNING: Recorded major go version (go1.5) and in-use major go version (go1.4) differ.
godep: To record current major go version run `godep update -goversion`.


godep: cannot save github.com/opencontainers/runc/libcontainer/cgroups at revision d97d5e8b007e4657316eed76ea30bc0f690230cf: already have github.com/opencontainers/runc/libcontainer at revision 97bc9a7faf3dd660d9be90a2880b2e37f3cdbf38.
Run `godep update github.com/opencontainers/runc/libcontainer' first.
```

I don't want to update libcontainer.  My Godeps.json file lists 97bc9a... - why is it trying to import a diffrent rev?  Running with `-v` gives me nothing extra - not a single line.  Running with `-d` has generated 40 MILLION LINES of debug and is still running 20 minutes later.

Neither one seems very useful.  How do I track this down?

**Comment by thockin** [comment]
I killed it after 30 minutes and 65M lines of output (4GB of disk)

**Comment by freeformz** [comment]
Godep requires that all packages from a single repo be at the same revision.

And yes save needs some -v love.

**Comment by thockin** [comment]
I know it requires the same version - I am trying to figure out where it
got the idea that there was a different version involved?  The parent repo
(libcontainer) is vendored at rev X, why is it trying to pull a child of
that at rev Y?

**Comment by thockin** [comment]
oh for the love of ...

It's finding a different rev in GOPATH than I have vendored.  Despite the
fact that it won't (as per another issue I filed, thanks for the patience)
actually replace Godeps that are already present, it complains if the
versions don't match,

Godep's logic is inscrutable to me.

**Comment by freeformz** [comment]
Godep works off what's in the $GOPATH and doesn't (🏧) care what's vendored. You need to "godep restore" before doing most things. I'd like to change that over time along with the vendor/ folder, but people still rely on the old behavior too and an explosion of flags and possible code paths is :-(.

**Comment by freeformz** [comment]
And fwiw I think I'm going to add a "list" of "status" command to show what the status of various packages is.
