### ISSUE TITLE
I got a problem about nsq: "godep: no buildable Go source files in"

### ISSUE THREAD

**Issue by bells** [tools/godep#39]
bells@bells-desktop:~$ godep get github.com/bitly/nsq
package github.com/bitly/nsq
    imports github.com/bitly/nsq
    imports github.com/bitly/nsq: no buildable Go source files in /home/bells/go/src/github.com/bitly/nsq
godep: exit status 1
bells@bells-desktop:~$ 
bells@bells-desktop:~$ 
bells@bells-desktop:~$ godep get github.com/bitly/nsq
godep: no buildable Go source files in /home/bells/go/src/github.com/bitly/nsq
bells@bells-desktop:~$ 

why?

thank you!

**Comment by dadgar** [comment]
I am also getting this when trying to update:
godep update github.com/hashicorp/go-getter
godep: no buildable Go source files in /Users/adadgar/Projects/go/src/github.com/StackExchange/wmi
godep: error loading dependencies

I have a project that has different imports depending on OS and the above is only used on windows. I tried to just `GOOS=windows go get github.com/StackExchange/wmi` which worked but then get the above error.

**Comment by freeformz** [comment]
What version of godep are you using?

I’ll also see if I can reproduce this.

**Comment by dadgar** [comment]
godep v57 (darwin/amd64/go1.6)

**Comment by freeformz** [comment]
@dadgar what if you go get github.com/StackExchange/wmi and try updating again. Please not that you probably want to use `godep update github.com/hashicorp/go-getter/...` atm because of a bug in the update code.

**Comment by dadgar** [comment]
Tried to run the command again but got `godep: no packages can be updated`

**Comment by freeformz** [comment]
@dadgar did you run `godep update github.com/hashicorp/go-getter/...` And is `github.com/hashicorp/go-getter` anywhere in your Godeps.json file?

**Comment by dadgar** [comment]
Ah I did `godep update github.com/hashicorp/go-getter/` but your suggested command worked. Problem is now I am up to date so I believe it was a no-op.

go-getter is in the Godeps.json file and it was when I initially opened this issue. I think the root of the problem is that godep doesn't like it when a package is being imported but isn't buildable on the platform you are using godep on. This is a problem when you are developing a project that has dependencies for both windows and linux as no single platform builds them all!

**Comment by freeformz** [comment]
@dadgar godep is platform agnostic. the go tool isn't atm, so it will not pull down all possible deps for a package, only the ones the local arch needs to build. Godep will find all deps across all arches as it ignores build tags (except for ignore and appengine) atm.
