### ISSUE TITLE
v33-onwards: Undocumented change regarding including non-standard build tag dependencies on save.

### ISSUE THREAD

**Issue by shurcooL** [tools/godep#391]
Hi,

I've done a binary search on godep versions and traced this change of behavior/regression to version 33. It affects all versions starting from 33 onwards. Version 32 and earlier don't have this behavior.

The change is that now when doing `godep save`, it saves all dependencies even for non-standard build tags. This was previously not the case.

Here's a minimal reproduce case. Consider a Go package with 3 .go files:

```Go
package main

import (
	"fmt"
	"os"
)

func main() {
	_, err := assets.Open("foo.txt")
	fmt.Println(os.IsNotExist(err))
}
```

```Go
// +build !dev

package main

import "net/http"

var assets = http.Dir(".")
```

```Go
// +build dev

package main

import (
	"net/http"

	"github.com/shurcooL/httpfs/union"
)

var assets = union.New(map[string]http.FileSystem{
	"/assets": http.Dir("."),
})
```

With godep version 32, if you run `godep save ./...`, you'd get:

```JSON
{
	"ImportPath": "github.com/shurcooL/play/172",
	"GoVersion": "go1.5.2",
	"Packages": [
		"./..."
	],
	"Deps": []
}
```

Which makes sense because the normal package has no external dependencies (it only imports Go standard library).

But with version 33 and later, doing the exact same `godep save ./...` command, you get:

```JSON
{
	"ImportPath": "github.com/shurcooL/play/172",
	"GoVersion": "go1.5.2",
	"Packages": [
		"./..."
	],
	"Deps": [
		{
			"ImportPath": "github.com/shurcooL/httpfs/union",
			"Rev": "5782901d7de3a2107e252a57f5b3403213e7ec4f"
		},
		{
			"ImportPath": "github.com/shurcooL/httpfs/vfsutil",
			"Rev": "5782901d7de3a2107e252a57f5b3403213e7ec4f"
		},
		{
			"ImportPath": "golang.org/x/tools/godoc/vfs",
			"Rev": "4ad533583d0194672e7d3bc6fb8b67c8e905d853"
		}
	]
}
```

Note that it vendors dependencies that are only there if you specify `-tags=dev` build tag. They're not dependencies when doing a normal `godep go build`.

Is this a bug/regression or working as intended?

Given that it's a significant change of behavior that is not documented in the changelog, I'm tempted to understand it's an unintended regression.

This has a significant effect on packages that use build tags for some non-critical functionality (for example, a "dev" build tag for development mode, or "ignore" build tag for some go generate helper.

It also means doing `godep save ./...` on existing projects after 33 will potentially create a significant diff by adding more packages. If this behavior is meant to be, I want to confirm so that it doesn't unexpected change again without notice in a future version of godeps, causing yet another disruptive large unexpected diff when doing `godep save ./...` in an existing project.

Thanks.

**Comment by sqs** [comment]
Is this related to https://github.com/tools/godep/issues/271?

**Comment by shurcooL** [comment]
That does look related.

It sounds like this is WAI. If that's the case, this is a documentation/changelog issue, since this new behavior is currently not clearly communicated.

**Comment by freeformz** [comment]
It was an oversight omitting it from the Changelog (at the least) and the README. I'll see about fixing that up ASAP.

We currently do ignore files with `ignore` and `appengine` tags: https://github.com/tools/godep/blob/a1054101461cab7f7c67a22e3aabd0fdb567ce3a/list.go#L271

FWIW: I'd like to add back in more tag support at some point.

**Comment by shurcooL** [comment]
I see, thanks for clarifying that this is indeed intended behavior.

> We currently do ignore files with `ignore` and `appengine` tags

That's also good to know (and I agree, should be documented). Thanks.

**Comment by shurcooL** [comment]
Thanks!
