### ISSUE TITLE
godep: Package (github.com/olekukonko/ts) not found

### ISSUE THREAD

**Issue by gregf** [tools/godep#398]
Trying to setup godep for a project and I'm getting `godep: Package (github.com/olekukonko/ts) not found`. The project does exist on github. So I'm not sure why I would see this message.

I'm using godep v48 (linux/amd64/go1.5.2)

**Comment by gregf** [comment]
Hmm seems I had to run go get -u github.com/olekukonko/ts first. Is this normal behavior?

**Comment by freeformz** [comment]
Probably. godep expects the packages to exist in the $GOPATH atm. If you are starting a new project you'd start with `go get <pkg>`, use it, then `godep save` to record / copy it into your godep workspace (or `vendor/`). If you are working with an existing project that uses godep, you can start with a `godep restore`, which will modify your gopath to equal the recorded/saved deps. This can be worked around somewhat by saving with rewrites (`godep save -r`), but the ultimate solution is that godep will (eventually) use what's in `vendor/`. Some of that logic already exists, but not all of it yet.

Does that help? If not, can you please describe what you are doing in more detail?

**Comment by gregf** [comment]
That explains it, thank you very much!
