### ISSUE TITLE
godep save -r seems completely busted unless you run from inside your project in $GOPATH.

### ISSUE THREAD

**Issue by parkr** [tools/godep#401]
Hey,

I was working on https://github.com/jekyll/dashboard in `~/jekyll/dashboard` and `godep save` and `godep save -r` and `godep save .` and `godep save ./...` (etcetera) all failed. I had it symlinked to `$GOPATH/src/github.com/jekyll/dashboard`, but no dice. None of it worked.

**It would be nice if `godep` would fail when being run outside of `$GOPATH/src`**
### Steps to reproduce
1. `mkdir ~/my-new-proj && cd my-new-proj`
2. Write a go program that imports at least 1 external package
3. `godep save ./...`
4. `godep go build ./...`
### Expected Behaviour

Step 3 would vendor all my imports into `Godeps/_workspace` and write the metadata out to `Godeps/Godeps.json`. It would rewrite the imports to point to this new vendored workspace

Step 4 would build my project with those vendored imports.
### Actual Behaviour

Step 3 creates `Godeps/`, but `Godeps.json` contains only:

``` js
{
    "ImportPath": ".",
    "GoVersion": "go1.5",
    "Deps": []
}
```

and `_workspace` is empty.

Step 4 works fine, but it's not using the vendored packages because there's nothing vendored.
### Steps to Resolve
1. `mv ~/my-new-project $GOPATH/src/github.com/you/my-new-project`
2. `cd $GOPATH/src/github.com/you/my-new-project`
3. Repeat step 3
4. Repeat step 4

Props to @freeformz for helping out: https://twitter.com/freeformz/status/689875007443329028

**Comment by majewsky** [comment]
+1

I'm actively avoiding putting my stuff inside GOPATH to ensure that it stays compilable everywhere, so that users can just `git clone && make` without needing to worry about setting up a GOPATH, and packagers can grab a tarball and have it compile everywhere (even without internet connection).
