### ISSUE TITLE
Vendor Experiment not supported for Go1.6Beta2

### ISSUE THREAD

**Issue by jcmoore0** [tools/godep#402]
Godep v50 does not support vendorexperiment when  majorGoVersion = "go1.6Beta2".

main.go  
(majorGoVersion == "go1.6" && os.Getenv("GO15VENDOREXPERIMENT") != "0")  

needs to be
(majorGoVersion == "go1.6Beta2" && os.Getenv("GO15VENDOREXPERIMENT") != "0")  

or some alternate string parse

**Comment by freeformz** [comment]
Thanks for reporting this. Total oversight. ;-) Should be fixed in master (v51) and as soon as travis makes a release it will be on the releases page.
