### ISSUE TITLE
Godep restore failing on non "/<package>" suffixed URL Imports

### ISSUE THREAD

**Issue by derekdowling** [tools/godep#406]
Happens specifically with [goji.io](https://godoc.org/goji.io).

```
$ godep restore
godep: error downloading dep (goji.io): unrecognized import path "goji.io"
godep: Error downloading some deps. Aborting restore and check.
```
Example here: https://travis-ci.org/derekdowling/jsh-api/jobs/105525674.

**Comment by freeformz** [comment]
Thanks for the report. Will look into it.

**Comment by MrJoy** [comment]
I'm having the same issue with packages hosted on a Github Enterprise server.  

```
$ godep restore ./...
godep: error downloading dep (<our internal domain name>/tools/go-<product>/client): unrecognized import path "<our internal domain name>/tools/go-<product>/client"
godep: error downloading dep (<our internal domain name>/tools/go-test-tools/httptestserver): unrecognized import path "<our internal domain name>/tools/go-test-tools/httptestserver"
godep: error downloading dep (<our internal domain name>/tools/golang-jenkins): unrecognized import path "<our internal domain name>/tools/golang-jenkins"
godep: Error downloading some deps. Aborting restore and check.
```

(Removing actual domain name and the name of one of our products as I'm not yet sure what I can/can't say out loud.)

If I manually git clone the relevant repos under the expected locations in my `$GOPATH` all works well.  The relevant URL form for the `git clone` command winds up being `git@<our internal domain name>:tools/<package>`.

Thoughts on how best to proceed other than adding setup instructions telling people to manually clone a bunch of repos?

**Comment by freeformz** [comment]
I'll have to see what the vcs library generated for a url and see if that's the problem in these cases. Sorry, been working on other stuff for a bit. Hoping to get back to this later in the week or next week.

**Comment by MrJoy** [comment]
Is there an option to `godeps` that will cause it to spit out the generated URL, or some other means by which I can get you more information here?

**Comment by freeformz** [comment]
@MrJoy `godep save -d <other args>` should do that and a LOT more however.

**Comment by MrJoy** [comment]
Actually, I've sussed out what's happening on my end, and I think it may be of relevance to the original issue:

Go has knowledge of specific domain names, and when presented with a thing that looks like a domain but is unknown, will tend to kvetch.  You can give it a hint by adding, for example, ".git" to the portion of the import path that represents the repo.

So for us, we fixed the issue by changing import paths to:

```
<our internal domain name>/tools/<package>.git/<sub-package>
```

Or:

```
<our internal domain name>/tools/<package>.git
```

As appropriate.

The Goji folks are using a mechanism to nudge `go get` to figure out what kind of repo it is, and where to find it by putting a special marker in the HTML at https://goji.io:

```html
<meta name="go-import" content="goji.io git https://github.com/goji/goji">
```

So if the original author changes the import from `goji.io` to `github.com/goji/goji`, then he can proceed.

For you, maintaining this project, you may wish to look at how Go susses this stuff out and the cheats and hints it accepts, and try to mirror that.

**Comment by MrJoy** [comment]
The relevant arcana can be found via `go help importpath`.

**Comment by freeformz** [comment]
@MrJoy Thanks for the analysis ! This is pretty much what I *thought* is likely happening, sorry I wasn't more specific in my response.

FWIW: godep uses https://godoc.org/golang.org/x/tools/go/vcs, which I *thought* took care of all of that. It may not though as there is a wide discrepancy between the go command line tooling and these supplemental libraries. 

I'll look into those libs to verify what they do and if they don't work like the go tooling will patch and PR them.

**Comment by MrJoy** [comment]
:+1:

**Comment by afex** [comment]
@freeformz hi has there been any progress towards your research?

**Comment by skippyta** [comment]
Pinging this again. I've been able to work around the restore problems manually for now but it's a bit of a pain. Any update?

**Comment by Kaidence** [comment]
@freeformz Pinging this again, is this something godep will try to solve?

**Comment by freeformz** [comment]
@MrJoy @derekdowling So the error for goji is being returned from https://github.com/golang/tools/blob/3f1f7eeff104d9ef829677f12b9780dfdd26a96a/go/vcs/vcs.go#L395, which was thrown from `RepoRootForImportDynamic` which calls `parseMetaGoImports` which looks for the `go-import` tag. So something in the golang/tools/go/vcs package is busted vs `go get` AFAICT. 

Digging more.

**Comment by freeformz** [comment]
This is fixed in v64. It was a bug in the [vcs package](https://github.com/golang/tools/commit/157f8abbbd7c19e90432c72cb6216cf0b9324c55)
