### ISSUE TITLE
"godep save" fails to vendor a dependency under some circumstances

### ISSUE THREAD

**Issue by russellhaering** [tools/godep#408]
I'm using Godep for an internal project successfully vendoring >100 dependencies. But for reasons I can't discern it always misses a certain dependency and I have to vendor it manually.

I've created a repository that reproduces the issue: https://github.com/russellhaering/godep-timetools-bug

In short, if I import `github.com/vulcand/vulcand/service` I see `github.com/mailgun/timetools` successfully pulled in, but its import of `gopkg.in/mgo.v2/bson` is not rewritten and `gopkg.in/mgo.v2/bson` is not vendored.

Again, this seems to be an unusual but painful edge case. I'm not sure what makes it unique.

**Comment by cmoesel** [comment]
Interestingly enough, I have the same exact problem -- with the same exact dependency (`gopkg.in/mgo.v2/bson`).  It's in the *Godeps.json* file, but doesn't get copied over to the vendor directory.

**Comment by freeformz** [comment]
@cmoesel Can you share your Godeps.json file and any code? Also, what does 'find . -type d -name "bson"` return ?

**Comment by freeformz** [comment]
I can't duplicate this, so I need more info.

```console
$ cat main.go
package main

import (
	"fmt"

	"gopkg.in/mgo.v2/bson"
)

func main() {
	fmt.Println(bson.Binary{})
}
$ godep save
$ cat Godeps/Godeps.json
{
	"ImportPath": "github.com/freeformz/t408",
	"GoVersion": "go1.6",
	"GodepVersion": "v70",
	"Deps": [
		{
			"ImportPath": "gopkg.in/mgo.v2/bson",
			"Comment": "r2016.02.04-1-gb6e2fa3",
			"Rev": "b6e2fa371e64216a45e61072a96d4e3859f169da"
		}
	]
}
$ find .
.
./Godeps
./Godeps/Godeps.json
./Godeps/Readme
./main.go
./vendor
./vendor/gopkg.in
./vendor/gopkg.in/mgo.v2
./vendor/gopkg.in/mgo.v2/bson
./vendor/gopkg.in/mgo.v2/bson/bson.go
./vendor/gopkg.in/mgo.v2/bson/decode.go
./vendor/gopkg.in/mgo.v2/bson/encode.go
./vendor/gopkg.in/mgo.v2/bson/LICENSE
./vendor/gopkg.in/mgo.v2/LICENSE
```

Also @russellhaering when I checkout your example repo and I run godep save on it `Godeps/_workspace/src/gopkg.in/` get's added.

Maybe it was solved in the meantime?

@cmoesel What version of godep are you using?

**Comment by russellhaering** [comment]
Yes, its not clear to me what fixed it, but this issue no longer seems to affect me. Thanks for looking into it.
