### ISSUE TITLE
Have to run `godep save ./...` multiple times to vendor all dependencies

### ISSUE THREAD

**Issue by gracedo** [tools/godep#412]
Note: this is using the vendor experiment, so all my deps are in `/vendor`

First run of `godep save ./...` failed to grab the deps of an imported package (in a private repo, if that helps to pinpoint the issue). Second run of `godep save ./...` grabbed the "next level" of deps in that imported package. Finally, the third run of `godep save ./...` grabbed the level under: the deps of the deps of the first dependency (my actual `import <pkg>`). At that point I finally had no more deps missing and was able to build the service successfully.

Seems like a bug, shouldn't need to run it multiple times to get all my deps, layer by layer.

I'm thinking it may be specific to private repos, since `aws-sdk-go` vendors successfully with all the "layered" deps needed.

**Comment by freeformz** [comment]
What version of godep are you using?

**Comment by freeformz** [comment]
Also, when you say private repos, what do you mean? godep works with what's on disk already in your $GOPATH.

**Comment by gracedo** [comment]
```$ godep version
godep v34 (darwin/amd64/go1.5.1)```

Sorry, yeah the package I'm trying to import is in my $GOPATH; private as in private git repo, so I had to clone it into my $GOPATH

**Comment by freeformz** [comment]
Please upgrade and try again w/o a `vendor/` or `Godeps/` directory. The current version is v52 and I remember something like this being fixed a ways back.

**Comment by gracedo** [comment]
@freeformz Yup that was it, bah! Thanks :+1:

**Comment by freeformz** [comment]
No worried. Thanks for giving it a try!
