### ISSUE TITLE
godep save deletes all deps

### ISSUE THREAD

**Issue by tcurdt** [tools/godep#413]
I have project uses `godep` for dep management. It installs and runs fine.
I have added some new files and a new library dependency. I then ran:

    godep save
    godep save -r
    godep save -r ./...

but instead of _adding_ my new dependencies this just **removes** all existing from the `Godeps.json` and deletes all in `_workspace`.

What am I missing?

godep v53 (darwin/amd64/go1.5.3)

**Comment by tcurdt** [comment]
I was wondering if it's somehow related to https://github.com/tools/godep/issues/401 ... but trying from inside the GOPATH folder does not seem help either.

**Comment by freeformz** [comment]
`godep` is designed to be run from within your $GOPATH with all of the deps also in the $GOPATH. So if you are working outside of the $GOPATH with symlinks and/or your deps are the same way `godep` may not work well for you. If you are inside of the $GOPATH though I'd really like to see if we can re-produce this to fix the issue and make a test case for it.

**Comment by tcurdt** [comment]
@freeformz I tried both. So yes - all inside the $GOPATH did not work for me.
Is the following structure correct for `godep`?

    export GOPATH=`pwd`/.go

    tree .go
    ├── bin
    │   ├── godep
    │   ...
    ├── pkg
    └── src
        ├── github.com
        │   ├── project
                ├── Godeps
                    ├── Godeps.json
                    └── _workspace
                        └── src
                            ├── github.com
                            ...

**Comment by freeformz** [comment]
That seems like  a strange $GOPATH. Normally $GOPATH is something like `export GOPATH=$HOME/go`. And the you `cd $GOPATH/src/<project>`, where `<project>` == something like `cd $GOPATH/go/src/github.com/tools/godep; edit code; godep save`.

**Comment by tcurdt** [comment]
But that is `cd $GOPATH/src/github.com/<project>` and there I was trying `godep save`

**Comment by freeformz** [comment]
what version of godep, go, is the vendor experiment turned on or off and (based on the tree output example) I assume the project was created w the vendor experiment turned off....

**Comment by tcurdt** [comment]
$ go version
    go version go1.5.3 darwin/amd64
    $ godep version
    godep v53 (darwin/amd64/go1.5.3)

and there is a `vendor` directory (with only one dep in there) - but I don't see anywhere a `GO15VENDOREXPERIMENT=1` (if that's what you are asking).

**Comment by freeformz** [comment]
Hmm. Nothing jumps out as off. I'm going to need the extremely large (possibly) output of `godep save -d -v <whatever other args you are using` unless you can re-produce it on a public repo.

**Comment by tcurdt** [comment]
My setup is without any symlinks. Would be really great if you had an idea.
Here is the output (too big for a comment): http://vafer.org/pub/output.txt.gz

**Comment by freeformz** [comment]
Please try again with v55+ and if there is still a problem please upload a new `godep save -d -v <pkg spec>`. I fixed a few bugs and added some more debug output (which may help in this case).

**Comment by tcurdt** [comment]
I've upgrade to v57 (and go1.6). This is what I get or `godep save -d -v`:

        $ godep save -d -v
        godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
        versionString() godep v57 (darwin/amd64/go1.6)
        majorGoVersion go1.6
        VendorExperiment false
        sep /Godeps/_workspace/src/
        dotPackageImportPath: github.com/foo/bar/backend
        dotPackageDir: /Users/tcurdt/.go/src/github.com/foo/bar/backend
        godep: Go Version: go1.6
        godep: WARNING: Recorded major go version (go1.5) and in-use major go version (go1.6) differ.
        godep: To record current major go version run `godep update -goversion`.
        godep: Finding dependencies for [.]
        LoadPackages [.]
        listPackage .
        findDirForPath . <nil>
        Filling package: github.com/foo/bar/backend from /Users/tcurdt/.go/src/github.com/foo/bar/backend
        Looking For Package: . in /Users/tcurdt/.go/src/github.com/foo/bar/backend
        &build.Package{
            Dir:            "/Users/tcurdt/.go/src/github.com/foo/bar/backend",
            Name:           "",
            ImportComment:  "",
            Doc:            "",
            ImportPath:     "github.com/foo/bar/backend",
            Root:           "/Users/tcurdt/.go",
            SrcRoot:        "/Users/tcurdt/.go/src",
            PkgRoot:        "/Users/tcurdt/.go/pkg",
            PkgTargetRoot:  "",
            BinDir:         "/Users/tcurdt/.go/bin",
            Goroot:         false,
            PkgObj:         "",
            AllTags:        nil,
            ConflictDir:    "",
            GoFiles:        nil,
            CgoFiles:       nil,
            IgnoredGoFiles: nil,
            InvalidGoFiles: nil,
            CFiles:         nil,
            CXXFiles:       nil,
            MFiles:         nil,
            HFiles:         nil,
            SFiles:         nil,
            SwigFiles:      nil,
            SwigCXXFiles:   nil,
            SysoFiles:      nil,
            CgoCFLAGS:      nil,
            CgoCPPFLAGS:    nil,
            CgoCXXFLAGS:    nil,
            CgoLDFLAGS:     nil,
            CgoPkgConfig:   nil,
            Imports:        nil,
            ImportPos:      {},
            TestGoFiles:    nil,
            TestImports:    nil,
            TestImportPos:  {},
            XTestGoFiles:   nil,
            XTestImports:   nil,
            XTestImportPos: {},
        }
        Done Looking For Package: . in /Users/tcurdt/.go/src/github.com/foo/bar/backend
        &main.Package{
            Dir:            "/Users/tcurdt/.go/src/github.com/foo/bar/backend",
            Root:           "/Users/tcurdt/.go",
            ImportPath:     "github.com/foo/bar/backend",
            Deps:           nil,
            Standard:       false,
            Processed:      false,
            GoFiles:        nil,
            CgoFiles:       nil,
            IgnoredGoFiles: nil,
            TestGoFiles:    nil,
            TestImports:    nil,
            XTestGoFiles:   nil,
            XTestImports:   nil,
            Error:          struct { Err string }{},
            Imports:        nil,
        }
        godep: Found package: github.com/foo/bar/backend
        godep:  Deps: 
        []*main.Package{
            &main.Package{
                Dir:            "/Users/tcurdt/.go/src/github.com/foo/bar/backend",
                Root:           "/Users/tcurdt/.go",
                ImportPath:     "github.com/foo/bar/backend",
                Deps:           nil,
                Standard:       false,
                Processed:      false,
                GoFiles:        nil,
                CgoFiles:       nil,
                IgnoredGoFiles: nil,
                TestGoFiles:    nil,
                TestImports:    nil,
                XTestGoFiles:   nil,
                XTestImports:   nil,
                Error:          struct { Err string }{},
                Imports:        nil,
            },
        }
        Filtered projectPackages
        []*main.Package{
            &main.Package{
                Dir:            "/Users/tcurdt/.go/src/github.com/foo/bar/backend",
                Root:           "/Users/tcurdt/.go",
                ImportPath:     "github.com/foo/bar/backend",
                Deps:           nil,
                Standard:       false,
                Processed:      false,
                GoFiles:        nil,
                CgoFiles:       nil,
                IgnoredGoFiles: nil,
                TestGoFiles:    nil,
                TestImports:    nil,
                XTestGoFiles:   nil,
                XTestImports:   nil,
                Error:          struct { Err string }{},
                Imports:        nil,
            },
        }
        godep: Computing new Godeps.json file
        fill github.com/foo/bar/backend
        []*main.Package{
            &main.Package{
                Dir:            "/Users/tcurdt/.go/src/github.com/foo/bar/backend",
                Root:           "/Users/tcurdt/.go",
                ImportPath:     "github.com/foo/bar/backend",
                Deps:           nil,
                Standard:       false,
                Processed:      false,
                GoFiles:        nil,
                CgoFiles:       nil,
                IgnoredGoFiles: nil,
                TestGoFiles:    nil,
                TestImports:    nil,
                XTestGoFiles:   nil,
                XTestImports:   nil,
                Error:          struct { Err string }{},
                Imports:        nil,
            },
        }
        LoadPackages []
        path [github.com/foo/bar/backend]
        uniq, unqualify'd path [github.com/foo/bar/backend]
        LoadPackages [github.com/foo/bar/backend]
        listPackage github.com/foo/bar/backend
        findDirForPath github.com/foo/bar/backend <nil>
        searching /usr/local/Cellar/go/1.6/libexec/src/github.com/foo/bar/backend
        searching /Users/tcurdt/.go/src/github.com/foo/bar/backend
        Looking For Package: github.com/foo/bar/backend in /Users/tcurdt/.go/src/github.com/foo/bar/backend
        &build.Package{
            Dir:            "/Users/tcurdt/.go/src/github.com/foo/bar/backend",
            Name:           "",
            ImportComment:  "",
            Doc:            "",
            ImportPath:     "github.com/foo/bar/backend",
            Root:           "/Users/tcurdt/.go",
            SrcRoot:        "/Users/tcurdt/.go/src",
            PkgRoot:        "/Users/tcurdt/.go/pkg",
            PkgTargetRoot:  "",
            BinDir:         "/Users/tcurdt/.go/bin",
            Goroot:         false,
            PkgObj:         "",
            AllTags:        nil,
            ConflictDir:    "",
            GoFiles:        nil,
            CgoFiles:       nil,
            IgnoredGoFiles: nil,
            InvalidGoFiles: nil,
            CFiles:         nil,
            CXXFiles:       nil,
            MFiles:         nil,
            HFiles:         nil,
            SFiles:         nil,
            SwigFiles:      nil,
            SwigCXXFiles:   nil,
            SysoFiles:      nil,
            CgoCFLAGS:      nil,
            CgoCPPFLAGS:    nil,
            CgoCXXFLAGS:    nil,
            CgoLDFLAGS:     nil,
            CgoPkgConfig:   nil,
            Imports:        nil,
            ImportPos:      {},
            TestGoFiles:    nil,
            TestImports:    nil,
            TestImportPos:  {},
            XTestGoFiles:   nil,
            XTestImports:   nil,
            XTestImportPos: {},
        }
        Done Looking For Package: github.com/foo/bar/backend in /Users/tcurdt/.go/src/github.com/foo/bar/backend
        &main.Package{
            Dir:            "/Users/tcurdt/.go/src/github.com/foo/bar/backend",
            Root:           "/Users/tcurdt/.go",
            ImportPath:     "github.com/foo/bar/backend",
            Deps:           nil,
            Standard:       false,
            Processed:      false,
            GoFiles:        nil,
            CgoFiles:       nil,
            IgnoredGoFiles: nil,
            TestGoFiles:    nil,
            TestImports:    nil,
            XTestGoFiles:   nil,
            XTestImports:   nil,
            Error:          struct { Err string }{},
            Imports:        nil,
        }
        standard or dest skipping github.com/foo/bar/backend
        New Godeps Filled
        &main.Godeps{
            ImportPath: "github.com/foo/bar/backend",
            GoVersion:  "go1.5",
            Packages:   nil,
            Deps:       nil,
            isOldFile:  false,
        }
        godep: Computing diff between old and new deps
        []main.Dependency(nil)
        []main.Dependency(nil)
        godep: Rewriting paths (if necessary)
        []string(nil)

**Comment by freeformz** [comment]
Does `github.com/foo/bar/backend` import anything ? godep isn't detecting any imports or dependencies.

**Comment by tcurdt** [comment]
`backend` is the root folder of the project on looks something like this:

    .
    ├── Makefile
    ├── cmd
    │   └── foo
    │       └── main.go
    ├── db
    │   ├── db.go
    .
    ├── http
    │   ├── handlers
    │   │   ├── status.go
    .

Sorry, I've given up on `godep` and moved on. I am using go1.6 with the standard `vendor` support now.

Feel free to close or leave it open but I still think it's an issue.

**Comment by freeformz** [comment]
Thanks for trying. I don't understand what you mean by "standard vendor support". Are you not using a tool to maintain `vendor/`?

**Comment by freeformz** [comment]
Oh, so if `backend` doesn't contain any files you need to pass `godep save` a package spec that includes all of the packages you want to have it analyze. This defaults to `.`, hence nothing is being saved to `vendor/`. Given the package structure you described, you probably want `godep save ./cmd/...`

**Comment by tcurdt** [comment]
I just mean the go1.6 `vendor` folder (not a Godeps folder) without import rewriting. For the time being I am using `glide` to maintain the `vendor` folder. Not perfect but got the job when I couldn't convince `godep` to do it. Thanks for the help.

**Comment by freeformz** [comment]
Ahh okay. FWIW: godep writes to `vendor/` when go1.6 (or go1.5 + env var) is used. Sorry you had troubles. Do you think there is any way I could update godep or the docs to better convey how save is supposed to be used?

**Comment by tcurdt** [comment]
Ah - didn't know about the `vendor` folder support in `godep`.
Hm - how did I miss that? That's quite prominent in the docs.
Anyway - what to pass as parameter could indeed be expanded on in docs.
Unless I missed that, too :-p
