### ISSUE TITLE
aws-sdk-go private packages being removed on restore / save?

### ISSUE THREAD

**Issue by phinze** [tools/godep#416]
This is perhaps related to #400, but I wanted to start it as a separate thread and we can merge the two later it makes sense to do so.

I had a user asking how to add a dependency in Terraform, and I instructed them to:

```bash
git checkout master
godep restore
git checkout feature-branch
godep save $(go list ./... | grep -v /vendor/)
```

But they reported unexpected diffs in `aws-sdk-go`. I looked into it and on [Terraform master right now](https://github.com/hashicorp/terraform/tree/938ab99d51195f04fbde54d7bcc9f2e53e0ffcfc), if I run:

```
godep restore -v
godep save -v $(go list ./... | grep -v /vendor/)
```

I see the removal of all packages under `github.com/aws/aws-sdk-go/private/...` - the diff I ended up submitting here: https://github.com/hashicorp/terraform/pull/5225, assuming it was just an oversight of not updating deps after a removed import reference. But those packages are definitely necessary for operation, as [Travis made immediately clear](https://travis-ci.org/hashicorp/terraform/builds/110515988). :grinning: 

I feel like I might be misunderstanding something here about the `go list ./... | grep -v /vendor/` workaround. If I switch to `go save ./...` godep ends up capturing another half-dozen debug/development type dependencies -- stuff like `go-spew` -- from things like `examples` subdirs in the `vendor/` tree. I'd prefer to avoid carrying around extra stuff in vendor that's not needed at runtime. But it looks like the `go list` approach is somehow failing to catch these transitive dependencies.

It seems to be like the pair of commands I ran should be a logical noop, but that's not what's happening. What am I missing here?

Thanks in advance for your time! :+1:

```
❯ godep version
godep v52 (darwin/amd64/go1.5.3)
```

**Comment by phinze** [comment]
Ah I just saw the PR here https://github.com/tools/godep/pull/415

I believe that would solve this problem:

>   If I switch to `go save ./...` godep ends up capturing another half-dozen debug/development type dependencies -- stuff like `go-spew` -- from things like `examples` subdirs in the `vendor/` tree. I'd prefer to avoid carrying around extra stuff in vendor that's not needed at runtime.

And then we could just switch to "Add a dependency" instructions like this:

```
git checkout master
godep restore
git checkout feature-branch
godep save ./...
```

Does that sound right to you, @freeformz?

**Comment by freeformz** [comment]
@phinze Yep. I was looking into why `./...` wasn't working with go install's for various go1.6 setups (with vendor) because it just should have. And that's when I noticed what seems to be previously spec'd behavior that I disagree with (copying all sub dirs of a required package).

**Comment by freeformz** [comment]
@phinze checking with terraform master now to see if what godep's generates is good.

**Comment by freeformz** [comment]
Once hashicorp/terraform#5248 is merged the instructions should be:

```$ console
$ git checkout master
$ godep restore
$ git checkout <feature-branch>
$ <edit code, add imports as necessary>
$ godep save ./...
$ git add -A .
$ git commit -av
```

If that doesn't work (except for exotic situations) then I consider it a bug.

**Comment by phinze** [comment]
This was solved w/ `godep v54` and deps fixed up in https://github.com/hashicorp/terraform/issues/5248 - thanks again @freeformz!
