### ISSUE TITLE
godep: dirty working tree (please commit changes)

### ISSUE THREAD

**Issue by melihmucuk** [tools/godep#424]
I'm using golang 1.6 and `godep save` gives me this output:

<pre><code>Melih-MacBook-Air:apasifik melih$ godep save
godep: dirty working tree (please commit changes): /Users/melih/go/src/github.com/gin-gonic/gin
godep: dirty working tree (please commit changes): /Users/melih/go/src/github.com/gin-gonic/gin/binding
godep: dirty working tree (please commit changes): /Users/melih/go/src/github.com/gin-gonic/gin/render
godep: dirty working tree (please commit changes): /Users/melih/go/src/github.com/jinzhu/gorm
godep: dirty working tree (please commit changes): /Users/melih/go/src/github.com/lib/pq/hstore
godep: dirty working tree (please commit changes): /Users/melih/go/src/golang.org/x/net/context
godep: error loading dependencies</code></pre>

whats wrong ?

![screen shot 2016-03-02 at 02 09 16](https://cloud.githubusercontent.com/assets/3147488/13446393/e645e254-e01b-11e5-8d8c-8703a0e26297.png)

**Comment by freeformz** [comment]
What version of godep (output of `godep version`)?

**Comment by melihmucuk** [comment]
`godep v56 (darwin/amd64/go1.6)`

I deleted godep and project folder, then reinstall it. Now It works.
