### ISSUE TITLE
Unknow Error!

### ISSUE THREAD

**Issue by WanliTian** [tools/godep#426]
go version
    go version go1.6 linux/amd64

    godep save
    godep: dirty working tree (please commit changes): /home/users/tianwanli01/Code/Go/gopath/src/github.com/samuel/go-zookeeper/zk
    godep: dirty working tree (please commit changes): /home/users/tianwanli01/Code/Go/gopath/src/golang.org/x/net/http2
    godep: dirty working tree (please commit changes): /home/users/tianwanli01/Code/Go/gopath/src/golang.org/x/net/http2/hpack
    godep: error loading dependencies

**Comment by freeformz** [comment]
What version of godep are you using (godep version).

**Comment by WanliTian** [comment]
godep v56 (linux/amd64/go1.6)

**Comment by freeformz** [comment]
Can you attach the output of `godep save -v -d 2>&1`. it will be quite large and you may need to upload it elsewhere / provide a compressed version.

**Comment by WanliTian** [comment]
https://raw.githubusercontent.com/WanliTian/gpush/master/error.txt
