### ISSUE TITLE
Add an option to skip vendoring tests or add build flags

### ISSUE THREAD

**Issue by arekkas** [tools/godep#427]
This is a follow up to https://github.com/golang/go/issues/14417 and more specifically to https://github.com/golang/go/issues/14417#issuecomment-191829754 .

Vendoring everything may break things when running e.g. `go test ./...`. Godep should therefore support an option to make vendoring `*_test.go` files optional or add build flags to these files as suggested by @bradfitz [here](https://github.com/golang/go/issues/14417#issuecomment-189899744).

**Comment by freeformz** [comment]
Godep hasn't vendored dependency's test files by default since ~v9 (9/2015). So any save that was created before v9 may have done so, but any later saves should remove them.  What version of godep are you using?

**Comment by freeformz** [comment]
I also fixed a bug recently where godep was vendoring more than it should have (because of old assumptions in the code). If you are using godep please update to v56+ and do the following:

```console
$ godep restore
$ rm -rf Godeps vendor
$ godep save <pkg spec> 
$ git add -A .
$ git commit -am "re-save to remove cruft"
```

Where <pkg spec> is the packages you want godep to analyze, so proabably `.` (the default) or `./...`.

**Comment by arekkas** [comment]
Oh I see, could possibly be related to using an outdated version of godep on my side (don't have the system available where the vendoring took place). Thanks for the hint and I'll also check out the new version of godep and report back if I run into problems. Thanks for the uber quick response, appreciate it always when maintainers do that.

**Comment by freeformz** [comment]
Thanks! I try to respond quickly, but can't always. So yay for finding just the right time to ask a Q. ;-)

**Comment by arekkas** [comment]
lucky me ;D
