### ISSUE TITLE
Proposal: Add godep version to Godeps.json

### ISSUE THREAD

**Issue by ericchiang** [tools/godep#429]
A very common bug we've experienced is developers using an old version of godep when attempting to use this tool. Our first recommendation when devs have issues with godep is "are you on the latest version?" Additionally different versions of godep handle tests, licenses, etc differently. 

I propose adding the godep version to the Godeps.json file. At the very least, during code review we could see that a user has used an outdated version of godep to update vendored packages.

```json
{
	"ImportPath": "github.com/foo/bar",
	"GoVersion": "go1.6",
	"GodepVersion": "v53",
	"Packages": [
		"./..."
	],
	"Deps": [
	]
}
```

**Comment by freeformz** [comment]
I have been thinking about doing this very thing for those very reasons.
