### ISSUE TITLE
feature request: support alternate project layouts

### ISSUE THREAD

**Issue by insasho** [tools/godep#43]
godep holds a strong opinion about how the source tree of a project is managed. See https://groups.google.com/forum/#!topic/golang-nuts/8NJq6jTIpas. Like Frank, our repository contains the entire source tree (and more). This allows ut do have a company-wide Makefile that implements various policies and procedures useful to our workflow, and allows stuff related to the project to be stored in the same git repo (ex: Vagrantfiles).  Also, we have a policy where all of our code must use the same dependencies.

In summary, this is our git repository structure:
```
/
/ops
/go
/go/src/company.com/proj1
/go/src/company.com/proj2
```

godep is incompatible with this structure. Example: `cd go/src/company.com && godep save` will fail with a "directory ../x/y/z/go is not using a known version control system", probably because /go is not the top-level directory of the repository.

godep has all of the other features we'd like in a dependency management system, but changing our model to support its requirements is too constraining for us. My request is that godep be adapted to support this pattern.

**Comment by freeformz** [comment]
#108 is merged and may fix this.
