### ISSUE TITLE
Question about godep save behaviour

### ISSUE THREAD

**Issue by declantraynor** [tools/godep#431]
Hey,

I've been using Godep for a while with relatively few problems. I've noticed a change in the behaviour of Godep in recent versions (v56+) when saving dependencies for a project that uses dot-import syntax for one or more of its dependencies. 

Suppose we have a package that imports `github.com/foo/bar` as follows:

`. import "github.com/foo/bar"`

After running `godep save ./...`, `Godeps.json` will now contain a separate entry for each package provided by `github.com/foo/bar`, where before it just contained a single entry. Is this expected behaviour? Is there documentation anywhere which explains the reasoning behind this change?

While it's not a huge deal in my present situation, it is introducing some churn in the `Godeps.json` where multiple developers are using different versions of Godep.

Thanks in advance!

**Comment by freeformz** [comment]
Sorry it took so long to answer this Q. It got lost in email :-(

It probably has less to do with `.` than with godep being explicit about which packages it is importing. Previously godep would only note the top level package and would also copy in all sub packages and directories, even if they **aren't** being used. This causes a bunch of problems when using `./...` with the go1.5+ vendor experiment as the go tool's use of `./...` includes **everything** in vendor.

This change happened in v54: https://github.com/tools/godep/blob/master/Changelog.md#v54-20160222

**Comment by declantraynor** [comment]
Hey, don't worry about the delay. Hardly an urgent matter :smile: 

Thanks for the explanation. I definitely understand not wanting to copy *everything* into `vendor/`, but I'm still confused about what's going on with `Godeps.json`. Perhaps I could have phrased my original question better.

Basically, I'm seeing a bunch of _additions_ in `Godeps.json` after running a `godep save ./...`. These appear to correlate exactly with the sub packages of any dependency that I've imported with `.`. Is this behaviour expected / related to the vendoring changes you've described above?

Thanks again.

**Comment by freeformz** [comment]
Yes, it's expected as godep is more specific wrt what it records as being used. Before it was kind of loose. I don't think it's related to `.` (`.` isn't treated specially by godep), it's just that those packages actually import sub packages that are properly part of your dependencies.

**Comment by declantraynor** [comment]
Ah, I get it now :+1:

Makes perfect sense now that I re-read your original response. Thanks again, and cheers for all the hard work!
