### ISSUE TITLE
after runing godep save, i cannot find any package under vendor dir

### ISSUE THREAD

**Issue by WanliTian** [tools/godep#432]
hi, all
there are items about subpackages under golang.org within godeps.json
but i cannot find any packages in vendor dir.

go 1.6

**Comment by freeformz** [comment]
What version of godep are you using?
Were you in your project's root directory in your $GOPATH?
What options did you pass to 'godep save'?

**Comment by WanliTian** [comment]
just godep save

**Comment by freeformz** [comment]
@WanliTian And the other things I asked about?

**Comment by WanliTian** [comment]
i change my environment from one machine to another, it works.
