### ISSUE TITLE
godep restore fails if commit is a tag not on a branch

### ISSUE THREAD

**Issue by eparis** [tools/godep#436]
My project has `github.com/skynetservices/skydns/server` at commit bb2ebadc9746f23e4a296e3cbdb8c01e956baee1 in its Godeps. This commit is a tag, but is not on any branch. `git pull --ff-only` only updates the branches and those tags which are on the branches. So I get the following failure when I try to restore:
```
# cd /storage/gopath/src/github.com/skynetservices/skydns/server; git checkout bb2ebadc9746f23e4a296e3cbdb8c01e956baee1
fatal: reference is not a tree: bb2ebadc9746f23e4a296e3cbdb8c01e956baee1
```

I can fix this by hand:
```
cd /storage/gopath/src/github.com/skynetservices/skydns/server
git fetch --tags
```

And then `godep restore` will work. I think it would be great if godep would try to fetch tags if it can't checkout before giving up. (Also it would be great if people didn't have tags on non-branches but that's something I can see someone did)

**Comment by eparis** [comment]
@ironcladlou

**Comment by freeformz** [comment]
What version of godep?

Also can you provide the output of `godep restore -v` ?

**Comment by freeformz** [comment]
Also `bb2ebadc9746f23e4a296e3cbdb8c01e956baee1` is not a tag. It looks like a fetch wasn't done. I rewrote restore to work better a few months ago and I'm pretty sure it does a fetch if the rev isn't available: https://github.com/tools/godep/blob/91e0ec806b03862d597978a9132fb592c0d6ba39/restore.go#L142-L145

**Comment by eparis** [comment]
godep v57 (linux/amd64/go1.6)

I'll try to get that one to reproduce with `-v`

**Comment by eparis** [comment]
(the godeps for the tree in question is a total nightmare, godep restore has about 5 different failures)

**Comment by freeformz** [comment]
If you could provide your Godeps/Godeps.json file I may be able to re-construct something. If it's large it will be harder to do though.

**Comment by eparis** [comment]
I'm going to close, because I haven't been able to reproduce....
