### ISSUE TITLE
go run don't run after godep save

### ISSUE THREAD

**Issue by FelipeUmpierre** [tools/godep#439]
Hello,

I am trying to use **godep** in my project but I am facing some weird problem. I have all my imports already installed in my local machine. When I do a `go run main.go` works fine, but when I do a `godep save`  and then a `go run main.go` I get this error:

```
conn/conn.go:8:2: cannot find package "_/Users/username/Documents/vm/projects/src/go/src/github.com/company/realtime/vendor/github.com/go-sql-driver/mysql" in any of:
	/usr/local/Cellar/go/1.6/libexec/src/_/Users/username/Documents/vm/projects/src/go/src/github.com/company/realtime/vendor/github.com/go-sql-driver/mysql (from $GOROOT)
	/Users/username/Documents/vm/projects/src/go/src/_/Users/username/Documents/vm/projects/src/go/src/github.com/company/realtime/vendor/github.com/go-sql-driver/mysql (from $GOPATH)
```

When I delete the `Godeps` and `vendor` folders and run again the main, it works again.

I've notice that godep is trying to load the file adding an undercore '_' before the $GOPATH. I don't know if it is correct or not.

Here is my project imports:

```
package conn

import (
	"database/sql"
	"log"

	_ "github.com/go-sql-driver/mysql"
)
```

GOPATH: `/Users/username/Documents/vm/projects/src/go`
Go version: 
```
$ go version
go version go1.6 darwin/amd64
```

Thanks!

**Comment by freeformz** [comment]
When you say "installed" what do you mean? installed into your $GOPATH with `go get` ?

What version of `godep`? (run `godep version`). If you are not running v60, please upgrade and try to re-save your deps.

godep is not adding the _, go is.

**Comment by FelipeUmpierre** [comment]
Hey @freeformz, thanks for the reply.

Sorry, when I say "install" I mean `go get` like you said. My bad.

```
$ godep version
godep v60 (darwin/amd64/go1.6)
```

So, you say that the problem is with go? But why, when I delete the godep folders in my project, it works? That's kind weird.

**Comment by freeformz** [comment]
Can you push a repo that I can use to reproduce this?

If you run `godep save` do you get any warning about being outside of the $GOPATH? `go` prepends stuff with _ when you are working outside of the $GOPATH (AFAICT).

**Comment by FelipeUmpierre** [comment]
This is an example of the project that I am working on: https://gist.github.com/FelipeUmpierre/7bcf72ceea702d432317

**Comment by freeformz** [comment]
godep does not work with relative imports and they are generally frowned upon toy code. Please make sure you are inside of a $GOPATH.

**Comment by FelipeUmpierre** [comment]
That was really is! Thanks!
