### ISSUE TITLE
Godep save not handling nested dependencies

### ISSUE THREAD

**Issue by dhawal55** [tools/godep#440]
```src
+ github.com
++ test
+++ helloWorld
++++ main.go (imports github.com/test/test1)
+++ test1
++++ test1.go (imports github.com/test/test2)
+++ test2
++++ test2.go
```

In the above scenario, HelloWorld imports test1 which in turn imports test2. When i run godep save on HelloWorld repo, it creates vendor/github.com/test/test1 but not vendor/github.com/test/test2

My godep version is ```godep v41 (darwin/amd64/go1.6)```

**Comment by freeformz** [comment]
Please upgrade to current and try again:

go get -u github.com/tools/godep

**Comment by dhawal55** [comment]
Ok, updated to latest godep - ```godep v60 (darwin/amd64/go1.6)```. But nested dependencies is still broken. Here's the real world example. My project is importing ```github.com/prometheus/client_golang/prometheus``` which in turn imports ```golang.org/x/net/context```. The golang.org repo is not getting vendored in the latest godep as well.

**Comment by dhawal55** [comment]
When i use glide (github.com/Masterminds/glide) with --all-dependencies option, it vendors nested dependencies as well but it does not clean the .git folder in vendored dependencies.

**Comment by freeformz** [comment]
I would suggest a full re-save.

```console
$ godep restore
$ rm -rf Godeps vendor
$ godep save ./...
```

It's likely that the dependencies for what godep thinks is already saved are not being pulled in. I need to see about constructing a test case for this, but the above 3 commands are what I have used to ensure everything is as clean as can be.

**Comment by dhawal55** [comment]
Closing this. Not sure what the issue was but deleting the entire repo and starting from scratch cleaned things up.
