### ISSUE TITLE
How to run godep go test with go1.6

### ISSUE THREAD

**Issue by smousa** [tools/godep#442]
When I run `godep go test ./...` I get missing packages errors for dependencies in my vendor/ directory.  Is there a fix or workaround for this?

**Comment by dhawal55** [comment]
```godep save -t``` will vendor test dependencies as well

**Comment by freeformz** [comment]
@smousa what version of godep are you using?

**Comment by smousa** [comment]
Thanks, that seemed to work @dhawal55
