### ISSUE TITLE
godep does not respect +build tags, latest golang.org/x/net/context breaks

### ISSUE THREAD

**Issue by themartorana** [tools/godep#448]
The [latest commit](https://github.com/golang/net/commit/afc22ee9133171570a267463982b542fb3edff5a) to the `context` package contains the file [go17.go](https://github.com/golang/net/blob/afc22ee9133171570a267463982b542fb3edff5a/context/go17.go) which imports the `context` library from the Go 1.7 standard library. 

Despite having the `// +build go1.7` tag at the top of the file, godep parses the file and throws a `godep: Package (context) not found` error.

I can get past this by going into the context package and checking out the `release-branch.go1.6` branch, but this simply illustrates the fact that `godep` isn't checking the `+build` tags, and is attempting to import packages for non-installed versions of Go.

**Comment by themartorana** [comment]
Sorry, tapped the wrong button...

**Comment by CannibalVox** [comment]
It's worse than that- deleting go17.go wont' help because it actually refused to read pre_go17.go.  It's like build tag is reversed, it will ONLY read the 1.7 file.

**Comment by freeformz** [comment]
What version of godep? Versions of godep (circa v41+, I would need to check the changelog for the specific version) process all .go files, except for those with "ignore" and "appengine" build tags. Adding go version build tags shouldn't be that hard since we also store the major go version in the Godeps.json file though.

**Comment by themartorana** [comment]
For me: `godep v60 (darwin/amd64/go1.6)`

**Comment by CannibalVox** [comment]
Above PR fixes the issue, hopefully we can see the resolution live soon, this is a pretty serious deal :\

**Comment by freeformz** [comment]
Looks like go1.7 includes a package named "context" and if you are not on 1.7 (really devel) then godep can't find the package because you don't actually have it.

**Comment by freeformz** [comment]
Can anyone test our the branch that I pushed for this? I tested it here, but it's late and I don't want to merge it before reviewing it in the morning (or getting other +1s).

**Comment by ddgenome** [comment]
@freeformz I can confirm that using PR https://github.com/tools/godep/pull/451 `godep save -v` on a project that imports "golang.org/x/net/context" finishes successfully whereas it fails with `godep: Package (context) not found` when using master.

**Comment by themartorana** [comment]
@freeformz seconded.

**Comment by freeformz** [comment]
Thanks everyone, this should now be fixed.
