### ISSUE TITLE
error when comparing with devel

### ISSUE THREAD

**Issue by gyuho** [tools/godep#452]
```
$ godep restore
godep: WARNING: Go version (devel) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
godep: Error comparing go1.7 to devel
```

https://travis-ci.org/coreos/etcd-play/jobs/121345461

I think `godep` fails when it tries to compare go1.7 with devel?

Please let me know if I can provide more information.

Thanks!

**Comment by freeformz** [comment]
Ugh. I'm not sure how to ask the `go` command if it's go1.7 or not while it's in "devel" mode.

**Comment by freeformz** [comment]
I could at this point just assume that anything that reports "deve" is go1.7 though.

**Comment by freeformz** [comment]
The go tool uses a build.Context.ReleaseTags slice and `go1.7` has been added in devel. To take a "guess" at this I could compile/run this code with the current `go` version and take the left most element of the array. This is likely to work, until the go team changes the order of this slice for any random reason.

```go
package main

import (
  "fmt"
  "go/build"
)

func main() {
  fmt.Println(build.Default.ReleaseTags[len(build.Default.ReleaseTags)-1])
}
```

That's super fragile, but so is having to say deal with what the definition of "devel" is.

Thoughts?

**Comment by freeformz** [comment]
I could also parse the date returned by version in the devel case and hard code in the dates the tree was opened. This may then break every major cycle though.
