### ISSUE TITLE
Add a single dependency

### ISSUE THREAD

**Issue by sethgrid** [tools/godep#456]
It seems like godep is an "all or nothing" vendoring tool. What we have had multiple times just this week is "add a single new dependency in a given file". It would make so much sense to `godep save <new_dependency>` - but that is now how it works. If I do `godep save <my_file>`, I lose all the existing dependencies save the ones specific in that file. A `godep add <import_path>` would be so dang handy. Hand in hand with a `godep remove <import_path>`. I often do not want to `godep restore; godep save ./...` because it changes my packages in my $GOPATH.

**Comment by freeformz** [comment]
`godep save` takes package paths or files as you point out. It analyzes the package(s) you point it to and determines what dependencies are required based on what is in your $GOPATH. I plan to enhance `godep get <pkg>` to just vendor <pkg> into `vendor/`.

This along with some other future enhancements should go a long way to removing the need for godep restore, which I also plan to remove.

**Comment by sethgrid** [comment]
looking forward to it; just wanted to give some feedback from my end. Cheers!

**Comment by finalsatan** [comment]
Can I add a single new dependency without "godep restore" now?
Thanks!

**Comment by freeformz** [comment]
Not really.I really suggest people look into using [dep](https://github.com/golang/dep) or [govendor](https://github.com/kardianos/govendor) instead of godep.
