### ISSUE TITLE
update a single package

### ISSUE THREAD

**Issue by yields** [tools/godep#465]
```bash
$ godep update github.com/pkg/a 
godep: Package (github.com/pkg/b) not found
```

I thought that `godep update <pkg>` will update the given package, but seems like it "checks" all dependencies and errors if a dependency is not found, even though `github.com/pkg/a` has no dependencies.

Any reason to check them all, is there a workaround to updating a single package?

--

```
$ godep version
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
godep v66 (darwin/amd64/go1.6.1)
```

**Comment by freeformz** [comment]
The workflow for godep update is to first `godep restore`, then checkout the version of the package you want to update to, then update.

**Comment by yields** [comment]
I see, is there a workaround at all?

Seems to me that `godep <pkg>` should update a single package and it's dependencies and not error if another package does not exists, is there a reason for this workflow that i'm missing?

Would love to work on a fix if you're interested :)

**Comment by freeformz** [comment]
I agree. I thought there was a test for this, but maybe not.
