### ISSUE TITLE
save deletes everything and update does nothing

### ISSUE THREAD

**Issue by tjannaud** [tools/godep#469]
Hi, Im pretty new to Go but not to software. Im working on a new team with lots of projects and dependencies so we must use godep.

All the code is structure in the standard Go way, with files in $GOPATH/.../github.com/... etc (including our work which is in github)

I made changes to project A (github.com/ourTeam/A) and I want to run project B (github.com/ourTeam/B) which references A to test my code. So I commit my work from A in my own branch in A, (and even pushed the branch).

**-> All I want is to update B with my new version of A.**

From B, I tried:

- godep update github.com/A/subpackage. It said 'godep: no packages can be updated'
- godep save. It deleted EVERYTHING in the vendor folder, leaving the Godeps.json file empty from any dependencies
- manually updating Godeps.json with my commit, then running godep update. No message but it didnt update anything. Godep save after this change deleted everything too in the vendor folder and Godep.json

What am I missing ?

Note: Im using godep v65 (darwin/amd64/go1.6.2) and

```
godep save -v
godep: Finding dependencies for [.]
godep: Found package: github.com/ourTeam/B
godep:  Deps:
(nothing so the diff with old file removes everything)
```

**Comment by freeformz** [comment]
Please update godep and try again, there are some update fixes recently.
WRT save removing everything. This is because godep was unable to find any deps for the provided package spec (defaults to '.'). So either (a) save was run w/o the right package spec, (b) some weird symlink issue, (c) another filesystem case bug.

**Comment by tjannaud** [comment]
v69 fixed this

**Comment by kristijan-ujevic** [comment]
this is not fixed, running version "godep v74 (linux/amd64/go1.6.2)"
