### ISSUE TITLE
add a new dependency?

### ISSUE THREAD

**Issue by yields** [tools/godep#470]
I'm sure i'm missing something, looked up in the docs but didn't find any way to do it, how can i add a new dependency?

ATM i'm doing this:

```bash
$ godep save github.com/pkg/a
$ git checkout Godeps
$ git commit ..
```

Surely there's a better way?

Cheers!

**Comment by freeformz** [comment]
It's described in this read me section: https://github.com/tools/godep/blob/master/Readme.md#add-a-dependency 

How can I make that clearer?

**Comment by yields** [comment]
whoops, my bad.
