### ISSUE TITLE
while running the grafana code.. I got below errors...like

### ISSUE THREAD

**Issue by yuvaraj951** [tools/godep#492]
/usr/local/go/bin/go test -v ./... -bench . -run ^$
/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/pkg/middleware/util.go:5:2: **cannot find package "github.com/go-macaron/gzip"** in any of:
	/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/vendor/github.com/go-macaron/gzip (vendor tree)
	/usr/local/go/src/github.com/go-macaron/gzip (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/go-macaron/gzip (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/go-macaron/gzip
/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/pkg/plugins/app_plugin.go:7:2: **cannot find package "github.com/gosimple/slug" i**n any of:
	/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/vendor/github.com/gosimple/slug (vendor tree)
	/usr/local/go/src/github.com/gosimple/slug (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/gosimple/slug (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/gosimple/slug
/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/commands.go:7:7: cannot find package "github.com/fatih/color" in any of:
	/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/vendor/github.com/fatih/color (vendor tree)
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/fatih/color (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/fatih/color
/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/services/services.go:8:2: cannot find package "github.com/franela/goreq" in any of:
	/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/vendor/github.com/franela/goreq (vendor tree)
	/usr/local/go/src/github.com/franela/goreq (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/franela/goreq (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/franela/goreq
/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/pkg/cmd/grafana-cli/commands/upgrade_all_command.go:7:6: cannot find package "github.com/hashicorp/go-version" in any of:
	/home/gogimcoitdev2/IdeaProjects/src/github.com/grafana/grafana/vendor/github.com/hashicorp/go-version (vendor tree)
	/usr/local/go/src/github.com/hashicorp/go-version (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/hashicorp/go-version (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/hashicorp/go-version
github.com/tools/godep/rewrite.go:15:2: cannot find package "github.com/kr/fs" in any of:
	/usr/local/go/src/github.com/kr/fs (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/kr/fs (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/kr/fs
github.com/tools/godep/msg.go:6:2: cannot find package "github.com/kr/pretty" in any of:
	/usr/local/go/src/github.com/kr/pretty (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/kr/pretty (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/kr/pretty
github.com/tools/godep/diff.go:7:2: **cannot find package "github.com/pmezard/go-difflib/difflib"** in any of:
	/usr/local/go/src/github.com/pmezard/go-difflib/difflib (from $GOROOT)
	/home/gogimcodev2/src/github.com/src/github.com/pmezard/go-difflib/difflib (from $GOPATH)
	/home/gogimcoitdev2/IdeaProjects/src/github.com/pmezard/go-difflib/difflib
package ./golang.org/x/net/icmp
	imports golang.org/x/net/internal/iana: use of internal package not allowed
package ./golang.org/x/net/ipv4
	imports golang.org/x/net/internal/iana: use of internal package not allowed
package ./golang.org/x/net/ipv6
	imports golang.org/x/net/internal/iana: use of internal package not allowed
package ./golang.org/x/net/trace
	imports golang.org/x/net/internal/timeseries: use of internal package not allowed
package ./golang.org/x/net/webdav
	imports golang.org/x/net/webdav/internal/xml: use of internal package not allowed
package ./golang.org/x/oauth2
	**imports golang.org/x/oauth2/internal:** use of internal package not allowed
package ./golang.org/x/oauth2/clientcredentials
	**imports golang.org/x/oauth2/internal:** use of internal package not allowed
package ./golang.org/x/oauth2/google
	imports golang.org/x/oauth2/internal: use of internal package not allowed
package ./golang.org/x/oauth2/jwt
	imports golang.org/x/oauth2/internal: use of internal package not allowed

**Comment by freeformz** [comment]
They are using the older style Godep workspace w/o rewrites, so run `godep restore` before running any go commands (or use `godep go <cmd>`).
