### ISSUE TITLE
Non-vendored operation: restore should install into godep path, not $GOPATH

### ISSUE THREAD

**Issue by antifuchs** [tools/godep#50]
For people who don't want to check in godep sources, it would be really convenient if `godep restore` had an option (or config setting) to install into the godep workspace. Currently, we run:

```
GOPATH=$(godep path) godep restore
```

to fetch the sources listed in the godep spec we check in. This (along with the next issue, which I'm gonna file shortly) would pretty much bring godep up to feature parity with bundler for us (no qualitative comparison intended :wink:).

**Comment by conslo** [comment]
I have an idea I'm surprised no one has proposed yet.

Many of these dependency pinning tools in some way reference Bundler as inspiration, I know that's what I think of whenever I see or use them. So why not take a page from that book and make a command `godep install`, which does exactly what's needed here: installs the dependencies listed in Godeps.json into the current projects `_workspace`.

I actually think `godep restore`'s functionality makes sense, it's a little ambiguous, so renaming it to `godep export` might make sense, but that's a breaking change so it should at the very least be done slowly (let both work with a deprecation warning for a while). Having `godep go` install dependencies if they're not already present is certainly a thing that could be done, but it's a bit to 'magic' for me. The most I'd be comfortable with there is a check and a warning printed. And I totally agree with @pdf, putting that expensive an operation into `godep path` is a bad idea.

**Comment by conslo** [comment]
I would like to add that I already do this as a shell alias:
```Bash
alias godep_install='GOPATH=$(godep path) godep restore'
```
and it works great. (if anyone wants to use this, it's quite important you use single quotes instead of double quotes, otherwise `godep path` is evaluated at alias creation, and not each time you run it)

**Comment by freeformz** [comment]
@kr How about we remove `restore` at this point?

**Comment by kr** [comment]
Restore is sometimes necessary when updating dependencies or saving new dependencies. Those other commands would have to be more careful if we want them to work without access to the full dependency set in $GOPATH.

This would be helped with better documentation for 'godep restore'. Restore is the opposite of save: save takes packages from GOPATH and puts the corresponding list of commit IDs in Godeps; restore takes a list of commit IDs from Godeps and puts the corresponding packages in GOPATH.

**Comment by kr** [comment]
I would instead say that the premise of this issue is increasingly invalid: "non-vendored operation" is something that the godep doesn't support. When folks ask how to handle the Godeps directory when they don't commit the source code, the response should be "you should commit the source code". If they *really* don't want to vendor code, then godep is not the tool for them.

**Comment by freeformz** [comment]
+1 and that is in line with the official Go team stance as well. With that said I'm going to close this issue. 

Thanks everyone for the discussion.
