### ISSUE TITLE
Package (database/sql) not found

### ISSUE THREAD

**Issue by nvartolomei** [tools/godep#504]
```
 → godep save
godep: Package (database/sql) not found

 → godep version
godep v74 (darwin/amd64/go1.6.2)
```

ideas?

**Comment by carlosmn** [comment]
I've found this to happen when the version of go you're using (that godep shells out to) is different from the one which godep was built with. I had installed godep with 1.6 but I'm now using 1.7 and it looks like it can't tell that the built-in packages correspond to 1.7.

I re-installed godep with 1.7 and it's working again now.

**Comment by nvartolomei** [comment]
Forgot about this. The problem was fixed by exporting correct GOROOT env variable.
