### ISSUE TITLE
Any idea about placing Godeps.json under vendor/ folder?

### ISSUE THREAD

**Issue by xuxiangyang** [tools/godep#505]
Hi, since go:1.5 release, the official solution for dependents became use vendor folder, especially , after releasing go:1.7, there is no need for GO15VENDOREXPERIMENT env.

why Godep place Godeps.json under Godeps folder? could it place under the vendor folder? if it could work, I would like to send you a PR.

Thx

**Comment by rafaeljusto** [comment]
`.godeps.json` file in project root instead of the Godeps directory would also be cool.

**Comment by AlexandreRoba** [comment]
I'm not sure this would make much sense to have it in the vendor folder.
Unless I'm mistaken but the vendor folder should not be under source control but the Godeps.json needs to be. Putting them in this folder would create confusion...
It could be at the root level.

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
