### ISSUE TITLE
godep restore fails on different remote

### ISSUE THREAD

**Issue by ianomad** [tools/godep#508]
### Expected behavior

I would expect it at least copy from vendor if it can't check it out
### Actual behavior

It is trying to fetch it by url, while it is actually a forked version, so go get wouldn't work
### Steps to reproduce behavior

Go get any lib, fork it, go to $GOPATH/src/youlib/ and checkout your fork (remote would be github.com/yourname/master) 
### `godep version` output

godep v74 (linux/amd64/go1.6.2)
### `go version` output

go version go1.6.2 linux/amd64
### Contents of Godeps.json file

`
{
    "ImportPath": "git.mspot.com/samsungplus/samsung-plus-api",
    "GoVersion": "go1.6",
    "GodepVersion": "v74",
    "Deps": [
        {
            "ImportPath": "github.com/BurntSushi/toml",
            "Comment": "v0.2.0-9-gf0aeabc",
            "Rev": "f0aeabca5a127c4078abb8c8d64298b147264b55"
        },
        {
            "ImportPath": "github.com/Sirupsen/logrus",
            "Comment": "v0.10.0-36-g08a8a7c",
            "Rev": "08a8a7c27e3d058a8989316a850daad1c10bf4ab"
        },
        {
            "ImportPath": "github.com/facebookgo/inject",
            "Rev": "643b7206b487b04fbea325cf6e8d06a66f8db772"
        },
        {
            "ImportPath": "github.com/facebookgo/structtag",
            "Rev": "217e25fb96916cc60332e399c9aa63f5c422ceed"
        },
        {
            "ImportPath": "github.com/fsnotify/fsnotify",
            "Comment": "v1.3.1",
            "Rev": "a8a77c9133d2d6fd8334f3260d06f60e8d80a5fb"
        },
        {
            "ImportPath": "github.com/go-errors/errors",
            "Rev": "a41850380601eeb43f4350f7d17c6bbd8944aaf8"
        },
        {
            "ImportPath": "github.com/go-sql-driver/mysql",
            "Comment": "v1.2-198-g0b58b37",
            "Rev": "0b58b37b664c21f3010e836f1b931e1d0b0b0685"
        },
        {
            "ImportPath": "github.com/gorilla/context",
            "Comment": "v1.1-4-gaed02d1",
            "Rev": "aed02d124ae4a0e94fea4541c8effd05bf0c8296"
        },
        {
            "ImportPath": "github.com/gorilla/mux",
            "Comment": "v1.1-13-g9fa818a",
            "Rev": "9fa818a44c2bf1396a17f9d5a3c0f6dd39d2ff8e"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/hcl/ast",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/hcl/parser",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/hcl/scanner",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/hcl/strconv",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/hcl/token",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/json/parser",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/json/scanner",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/hashicorp/hcl/json/token",
            "Rev": "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
        },
        {
            "ImportPath": "github.com/jinzhu/gorm",
            "Comment": "v1.0-52-gdda88dd",
            "Rev": "dda88dd08ca822a98ebc944b537ce81c16eeea46"
        },
        {
            "ImportPath": "github.com/jinzhu/gorm/dialects/mysql",
            "Comment": "v1.0-52-gdda88dd",
            "Rev": "dda88dd08ca822a98ebc944b537ce81c16eeea46"
        },
        {
            "ImportPath": "github.com/jinzhu/inflection",
            "Rev": "8f4d3a0d04ce0b7c0cf3126fb98524246d00d102"
        },
        {
            "ImportPath": "github.com/kr/fs",
            "Rev": "2788f0dbd16903de03cb8186e5c7d97b69ad387b"
        },
        {
            "ImportPath": "github.com/magiconair/properties",
            "Comment": "v1.7.0-3-gb3f6dd5",
            "Rev": "b3f6dd549956e8a61ea4a686a1c02a33d5bdda4b"
        },
        {
            "ImportPath": "github.com/mitchellh/mapstructure",
            "Rev": "ca63d7c062ee3c9f34db231e352b60012b4fd0c1"
        },
        {
            "ImportPath": "github.com/newrelic/go-agent",
            "Comment": "v1.0.0-3-g0025337",
            "Rev": "0025337aa82e68c91636a4eb64d1285f37c3d722"
        },
        {
            "ImportPath": "github.com/newrelic/go-agent/internal",
            "Comment": "v1.0.0-3-g0025337",
            "Rev": "0025337aa82e68c91636a4eb64d1285f37c3d722"
        },
        {
            "ImportPath": "github.com/newrelic/go-agent/internal/jsonx",
            "Comment": "v1.0.0-3-g0025337",
            "Rev": "0025337aa82e68c91636a4eb64d1285f37c3d722"
        },
        {
            "ImportPath": "github.com/newrelic/go-agent/internal/logger",
            "Comment": "v1.0.0-3-g0025337",
            "Rev": "0025337aa82e68c91636a4eb64d1285f37c3d722"
        },
        {
            "ImportPath": "github.com/newrelic/go-agent/internal/sysinfo",
            "Comment": "v1.0.0-3-g0025337",
            "Rev": "0025337aa82e68c91636a4eb64d1285f37c3d722"
        },
        {
            "ImportPath": "github.com/newrelic/go-agent/internal/utilization",
            "Comment": "v1.0.0-3-g0025337",
            "Rev": "0025337aa82e68c91636a4eb64d1285f37c3d722"
        },
        {
            "ImportPath": "github.com/pkg/errors",
            "Comment": "v0.7.0-13-ga221380",
            "Rev": "a22138067af1c4942683050411a841ade67fe1eb"
        },
        {
            "ImportPath": "github.com/pkg/sftp",
            "Rev": "a71e8f580e3b622ebff585309160b1cc549ef4d2"
        },
        {
            "ImportPath": "github.com/remind101/newrelic",
            "Rev": "53ed956ba53eaf62b1ecce4698606605aea9a9ba"
        },
        {
            "ImportPath": "github.com/remind101/newrelic/sdk",
            "Rev": "53ed956ba53eaf62b1ecce4698606605aea9a9ba"
        },
        {
            "ImportPath": "github.com/spf13/afero",
            "Rev": "cc9c21814bb945440253108c4d3c65c85aac3c68"
        },
        {
            "ImportPath": "github.com/spf13/afero/mem",
            "Rev": "cc9c21814bb945440253108c4d3c65c85aac3c68"
        },
        {
            "ImportPath": "github.com/spf13/afero/sftp",
            "Rev": "cc9c21814bb945440253108c4d3c65c85aac3c68"
        },
        {
            "ImportPath": "github.com/spf13/cast",
            "Rev": "e31f36ffc91a2ba9ddb72a4b6a607ff9b3d3cb63"
        },
        {
            "ImportPath": "github.com/spf13/jwalterweatherman",
            "Rev": "33c24e77fb80341fe7130ee7c594256ff08ccc46"
        },
        {
            "ImportPath": "github.com/spf13/pflag",
            "Rev": "f676131e2660dc8cd88de99f7486d34aa8172635"
        },
        {
            "ImportPath": "github.com/spf13/viper",
            "Rev": "346299ea79e446ebdddb834371ceba2e5926b732"
        },
        {
            "ImportPath": "github.com/urfave/negroni",
            "Comment": "v0.2.0-48-gdcaac91",
            "Rev": "dcaac9107a7a6ba4cf5143afc145e2b70a1c12c2"
        },
        {
            "ImportPath": "golang.org/x/crypto/curve25519",
            "Rev": "e0d166c33c321d0ff863f459a5882096e334f508"
        },
        {
            "ImportPath": "golang.org/x/crypto/ed25519",
            "Rev": "e0d166c33c321d0ff863f459a5882096e334f508"
        },
        {
            "ImportPath": "golang.org/x/crypto/ed25519/internal/edwards25519",
            "Rev": "e0d166c33c321d0ff863f459a5882096e334f508"
        },
        {
            "ImportPath": "golang.org/x/crypto/ssh",
            "Rev": "e0d166c33c321d0ff863f459a5882096e334f508"
        },
        {
            "ImportPath": "golang.org/x/net/context",
            "Rev": "d7bf3545bb0dacf009c535b3d3fbf53ac0a339ab"
        },
        {
            "ImportPath": "golang.org/x/sys/unix",
            "Rev": "a646d33e2ee3172a661fc09bca23bb4889a41bc8"
        },
        {
            "ImportPath": "golang.org/x/text/transform",
            "Rev": "2910a502d2bf9e43193af9d68ca516529614eed3"
        },
        {
            "ImportPath": "golang.org/x/text/unicode/norm",
            "Rev": "2910a502d2bf9e43193af9d68ca516529614eed3"
        },
        {
            "ImportPath": "gopkg.in/yaml.v2",
            "Rev": "e4d366fc3c7938e2958e662b4258c7a89e1f0e3e"
        }
    ]
}

`

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
