### ISSUE TITLE
[feature] optional lowercase godep folder/file instead of the uppercase

### ISSUE THREAD

**Issue by paddie** [tools/godep#509]
the godep folder created in the repo root is currently created with an upper-case G (Godep), and so is the Godep.json file. I'm genuinely interested in why that is (but mostly just annoyed :) ).

Mostly for consistency reasons, since the command is `godep`, but also because there doesn't seem to be a good reason for it. Could anyone enlighten me?

**Comment by freeformz** [comment]
I don't know the history. Tool late to change now really. Maybe @kr can shed some light on it?

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
