### ISSUE TITLE
Non-vendored operation: godep go should override the entire $GOPATH

### ISSUE THREAD

**Issue by antifuchs** [tools/godep#51]
To make us less worried about the state of possibly-inconsistent installations, it would be really useful to have an option (or config setting) to have `godep go` set `$GOPATH` variable to only the godep workspace. Currently, it appends to the existing `$GOPATH`, which is what we want to avoid by using godep (overriding the path entirely for every project means we get completely repeatable builds across machines/envs, which is super enticing to us).

We emulate this behavior via:
```
GOPATH=$(godep path) go build
```

**Comment by freeformz** [comment]
There's no real way to accomplish this AFAIK in go land w/o going down the `gb` path.

A `godep status` or `godep list` command to ensure everything in use is probably the best that can be done for now. I'm going to close this in favor of: #273
