### ISSUE TITLE
godep update 

### ISSUE THREAD

**Issue by plv1313** [tools/godep#513]
Hello, 

So I have two go projects name them A and B. So A has its own vendor folder and Godeps and has a dependency : 
    {
            "ImportPath": "gopkg.in/mgo.v2",
            "Comment": "r2016.08.01-5-g3f83fa5",
            "Rev": "3f83fa5005286a7fe593b055f0d7771a7dce4655"
        },
        {
            "ImportPath": "gopkg.in/mgo.v2/bson",
            "Comment": "r2016.08.01-5-g3f83fa5",
            "Rev": "3f83fa5005286a7fe593b055f0d7771a7dce4655"
        },

Now project B has a dependency on A and has its own dependency as well on:

{
            "ImportPath": "gopkg.in/mgo.v2/bson",
            "Comment": "r2016.08.01-5-g3f83fa5",
            "Rev": "3f83fa5005286a7fe593b055f0d7771a7dce4655"
        },

So lets say I do an update on project A that I want B to have it as well and is not linked with the bson dep. So what I am trying to do is try to update only the A dependency on project B by doing:

godep update A/...

But after doing that the project B fails to build because now the Godeps folder has as well:

```
{
        "ImportPath": "A/vendor/gopkg.in/mgo.v2/bson",
        "Rev": "5b7eee0a1b45e5530d9125cff36c1e5e15908d3f"
    },
```

Any idea how to avoid that? As it seems is trying to get the bson of the vendor and not its own.

**Comment by GrimTheReaper** [comment]
Experiencing the same issue.

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
