### ISSUE TITLE
git+ssh for private git repositories

### ISSUE THREAD

**Issue by cicerocomp** [tools/godep#514]
### Expected behavior

It should work for SSH key.
`.netrc` prevent you from using two-factor-authentication.
https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/
### Actual behavior

It works for `~/.netrc` https://github.com/tools/godep/issues/58
### `godep version` output

`godep v74 (darwin/amd64/go1.7rc1)`
### `go version` output

`go version go1.7rc1 darwin/amd64`
### Contents of Godeps.json file

private repos

**Comment by freeformz** [comment]
godep just shells out to git.

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
