### ISSUE TITLE
Missing libraries after execute `godep save`

### ISSUE THREAD

**Issue by jommgoncalves** [tools/godep#516]
### Expected behavior

After execute `godep save` we expected that all dependencies are in the file `Godeps/Godeps.json`.
### Actual behavior

The library `github.com/bmizerany/assert` used in all `*_test.go` is missing.
### Steps to reproduce behavior

godep save
### `godep version` output

godep v74 (darwin/amd64/go1.6.2)
### `go version` output

go version go1.6.3 darwin/amd64

**Comment by chnrxn** [comment]
I saw the same behavior too. If the main package is not in the current directory, could you try supplying the path to the main package? E.g. godep save -v ./cmd/... 

Note: I put all my main packages under ./cmd/, hence my example command.

**Comment by freeformz** [comment]
`godep save` w/o a package spec defaults to '.'. So if there are not
packages in the current directory nothing will be saved.
