### ISSUE TITLE
Allow convenient installation of binaries with godep get?

### ISSUE THREAD

**Issue by antifuchs** [tools/godep#52]
For things like gox (see #34), it would be really nice to be able to have the binaries available on the workspace (that definitely does interfere with vendored operation). I'm sure there must be an easy way to install the binaries from things, the way `go get` does, but I haven't been able to discover how, yet.

Here's what I tried:

* `GOPATH=$(godep path) godep go build github.com/mitchellh/gox` - this puts a `gox` binary in the project root
* `GOPATH=$(godep path) godep go install github.com/mitchellh/gox` - this has no observable effect (no binary being installed anywhere, it seems).

**Comment by freeformz** [comment]
This is possible by specifying the path to the full vendored package, so something like:
```console
$ go install -v github.com/my/project/Godeps/_workspace/src/github.com/your/project/cmd/thing
or
$ go install -v github.com/my/project/vendor/github.com/your/project/cmd/thing
```
works properly (AFAIKCT) with rewriting or the vendor experiment.
