### ISSUE TITLE
vendor experiment detection does not work with Go 1.8beta1

### ISSUE THREAD

**Issue by stapelberg** [tools/godep#526]
### Expected behavior

`godep save ./...` should write to `vendor/`

### Actual behavior

`godep save ./...` writes to `Godeps/_workspace`

### Steps to reproduce behavior

1. Install Go 1.8beta1
2. `export GO15VENDOREXPERIMENT=1`
3. `godep save ./...`

### `godep version` output

godep v75 (linux/amd64/go1.8beta1)

### `go version` output

go version go1.8beta1 linux/amd64

### Contents of Godeps.json file

N/A

### Details

determineVendor() in https://github.com/tools/godep/blob/e36e043d5ddb09d8d933ae332a17ba4ae7f614cc/main.go#L78 uses a whitelist of Go versions which does not include Go 1.8 yet.

**Comment by willglynn** [comment]
This remains broken under `go1.8beta2`, as is expected given the implementation of `determineVendor()`.

**Comment by parkr** [comment]
Fixed by #524.

**Comment by parkr** [comment]
@freeformz, have a sec to merge the related PR?

**Comment by parkr** [comment]
Thank you very much, @freeformz! If you need any help going through PR's, please let me know. I'd be happy to help!

**Comment by freeformz** [comment]
@parkr If you are interested sure, but my time has mostly moved to working with/on the tool being worked on by the go-pm community (coming soon).

**Comment by pierrre** [comment]
@freeformz `the tool being worked on by the go-pm community`
which one ? is it public ?

**Comment by parkr** [comment]
@freeformz I'd be honored to maintain this tool. A first step is to mark that it's in maintenance mode and no features will be added going forward. What do you think?

**Comment by freeformz** [comment]
@parkr It is not public yet, but you should check out https://groups.google.com/forum/#!topic/go-package-management/P8TehVoFLjg. Re: maintenance mode, throw up some PRs. ;-)
