### ISSUE TITLE
Godep does not save dependencies for packages with build tags

### ISSUE THREAD

**Issue by brettonfinch-wf** [tools/godep#529]
### Expected behavior
godep save ./... should save all dependencies for all files, regardless of if the files have a tag and !tag build tag in the code

### Actual behavior
Packages that have a build tag, but do not have a !build tag do not get processed

### Steps to reproduce behavior
I have a project like this
- $GOPATH/src/myProject
  |-- some_code.go (no build tags)
  |
  |-- subPackage1
  |    |-- more_code.go (no build tags)
  |
  |-- subPackage2
  |    |-- tagged_code.go (// + build mytag)

I have some code that uses `mytag` as a build tag but no code that uses `!mytag` as a build tag. When I run `godep save ./...` the dependencies for `tagged_code.go` are not written to Godeps.json or vendor. I can manually get those dependencies added by running `godep save ./... && godep save ./subPackage2` or by having a dummy file in subPackage2 with a `!mytag` build tag, but that's annoying to have to do.
### `godep version` output
godep v77 (darwin/amd64/go1.7.1)
### `go version` output
go version go1.7.4 darwin/amd64
### Contents of Godeps.json file
This is a private repro, can't post that

**Comment by freeformz** [comment]
Godep ignores build tags (except [ignore and appengine](https://github.com/tools/godep/blob/master/list.go#L22)), so I'm not sure why this is happening.

**Comment by freeformz** [comment]
With that said, I was able to [reproduce](https://github.com/freeformz/godeptags) this. :-(

**Comment by brettonfinch-wf** [comment]
That looks like the case I have setup in my project, nice to know your were able to reproduce it in an isolate case
