### ISSUE TITLE
godep v77 breaks with "is not using a known version control system"

### ISSUE THREAD

**Issue by stevenh** [tools/godep#531]
### Expected behaviour
godep save ./... should work

### Actual behaviour
godep: error while inspecting "/data/go/src/github.com": directory "/data/go/src/github.com" is not using a known version control system

Please note that the actual package directories are using known version control systems (git) but the intermediate directories are obviously not part of any repo.

### Steps to reproduce behaviour
run godep save ./... with a directory in the GOPATH that isn't part of a known version control system.

This works fine in v74 and v76.

### `godep version` output
godep v77 (freebsd/amd64/go1.7.4

### `go version` output
go version go1.7.4 freebsd/amd64

**Comment by freeformz** [comment]
It may be huge, but can you provide the output of `godep save -d -v ./... &> output` ?

**Comment by xrl** [comment]
@freeformz I have a similar issue. I'm new to the kubernetes project (as well as godep). Here's what I got:  https://gist.github.com/xrl/080e18909538e9d748eb87cd5d58c7ae . Downgrading to v74 got me going again.

**Comment by freeformz** [comment]
It looks like the change to stop using build.ImportDir in the code that handles './...' and the like is returning stuff above the current directory. There probably aren't tests for that specific issue, but I expected the existing tests to cover them. I'll have to dig more to figure out why.

**Comment by AlmogBaku** [comment]
same here

**Comment by turtlemonvh** [comment]
Temporary solution

```bash
go get gopkg.in/tools/godep.v76 && cp $GOPATH/bin/godep.v76 $GOPATH/bin/godep
```

**Comment by freeformz** [comment]
Fixed. Sorry about that. [Silly](https://github.com/tools/godep/commit/f15f6db5da33a4ac48be83e20b9dd838e14f117b) mistake. :-(
