### ISSUE TITLE
Godep panic

### ISSUE THREAD

**Issue by sosedoff** [tools/godep#532]
I used to run godep with no issues, however after last `go get -u github.com/tools/godep` im getting panics on any godep command. Here's the trace:

```
panic: godep:

goroutine 1 [running]:
panic(0x363dc0, 0xc420124880)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
log.(*Logger).SetPrefix(0xc420018140, 0x3dfd59, 0x7)
	/usr/local/Cellar/go/1.7/libexec/src/log/log.go:246 +0x6c
log.SetPrefix(0x3dfd59, 0x7)
	/usr/local/Cellar/go/1.7/libexec/src/log/log.go:277 +0x41
main.main()
	/Users/sosedoff/go/src/github.com/tools/godep/main.go:105 +0x6b
```

Running on OSX with:

```
go version go1.7 darwin/amd64
```

Not sure what happend, but it seems like it panics on this line: https://github.com/tools/godep/blob/master/main.go#L105

**Comment by freeformz** [comment]
Something is likely wrong with your go install as this is just calling a stdlib function of the log package.
