### ISSUE TITLE
godep path error

### ISSUE THREAD

**Issue by davidxiao** [tools/godep#536]
### Expected behavior
godep path should return GOPATH
### Actual behavior
godep path
Error: GO15VENDOREXPERIMENT is enabled and the vendor/ directory is not a valid Go workspace.
### Steps to reproduce behavior
$godep path
### `godep version` output
godep version
godep v79 (darwin/amd64/go1.7.5)
### `go version` output
go version
go version go1.7.5 darwin/amd64
### Contents of Godeps.json file
{
"ImportPath": "go-test",
"GoVersion": "go1.7",
"GodepVersion": "v79",
"Deps": [
                {
                        "ImportPath": "github.com/Sirupsen/logrus",
                        "Comment": "v0.11.2-1-g3f603f4",
                        "Rev": "3f603f494d61c73457fb234161d8982b9f0f0b71"
                },
                {
                        "ImportPath": "github.com/fsnotify/fsnotify",
                        "Comment": "v1.4.2-3-ga904159",
                        "Rev": "a904159b9206978bb6d53fcc7a769e5cd726c737"
                },
                ......
      ]
}

**Comment by erreobi** [comment]
I have the same problem

**Comment by mhughes** [comment]
I'm seeing the same issue 
>$ godep version
>godep v79 (windows/amd64/go1.8)

>$ go version
>go version go1.8 windows/amd64

Additionally it seems godep is trying to find packages in Godeps/_workspace

>$ godep get github.com/redacted/backend-go/hutch
>can't load package: package github.com/redacted/backend-go/hutch: cannot find package >"github.com/redacted/backend-go/hutch" in any of:
>        C:\Go\src\github.com\redacted\backend-go\hutch (from $GOROOT)
>        C:\Users\tute6\go\src\github.com\redacted\backend->go\Godeps\_workspace\src\github.com\redacted\backend-go\hutch (from $GOPATH)
>godep: go exit status 1
>godep: exit status 1

**Comment by chrispassas** [comment]
Same problem also.

**Comment by fifths** [comment]
$ godep version
godep v79 (linux/amd64/go1.8.3)

/home/fifths/go/src/test/Godeps/_workspace/src/gopkg.in/mgo.v2/bson (from $GOPATH)
godep: go exit status 1

 same problem

**Comment by ngauthier** [comment]
I noticed you're on windows. I have the same problem and I'm on windows but I'm on the linux subsystem (WSL).

```
nick@DESKTOP-5C3NHDT:~/go/src/github.com/ngauthier/meetspace$ go version
go version go1.8.3 linux/amd64
nick@DESKTOP-5C3NHDT:~/go/src/github.com/ngauthier/meetspace$ godep version
godep v79 (linux/amd64/go1.8.3)
nick@DESKTOP-5C3NHDT:~/go/src/github.com/ngauthier/meetspace$ godep path
Error: GO15VENDOREXPERIMENT is enabled and the vendor/ directory is not a valid Go workspace.
nick@DESKTOP-5C3NHDT:~/go/src/github.com/ngauthier/meetspace$ ls -l vendor/
total 0
drwxrwxrwx 0 nick nick 512 Jun 12 12:16 github.com
drwxrwxrwx 0 nick nick 512 Jun 12 12:16 golang.org
nick@DESKTOP-5C3NHDT:~/go/src/github.com/ngauthier/meetspace$
```

Could it be something weird with windows permissions or paths?

**Comment by tqoliver** [comment]
$ godep version
godep v79 (darwin/amd64/go1.8.1)

$ godep path
Error: GO15VENDOREXPERIMENT is enabled and the vendor/ directory is not a valid Go workspace.

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

**Comment by praveenkumar** [comment]
Same issue :(

```
$ godep version
godep v79 (linux/amd64/go1.7.5)

$ godep path
Error: GO15VENDOREXPERIMENT is enabled and the vendor/ directory is not a valid Go workspace.
```

**Comment by Skarlso** [comment]
Yep, here too.

```
godep path
Error: GO15VENDOREXPERIMENT is enabled and the vendor/ directory is not a valid Go workspace.
```

**Comment by javier-sanz** [comment]
Same environment as @Skarlso and I happens to me as well.

**Comment by alyandon** [comment]
I hit this as well and since there hasn't been any commit activity on godep since February, I decided to move to using glide.  It was extremely easy to set up for my particular projects - run glide init and commit the generated files.

**Comment by schmohlio** [comment]
same issue here:
```godep v79 (darwin/amd64/go1.9.1)```

seems this tool is rather unusable?

**Comment by ngauthier** [comment]
FYI in my case my GOPATH wasn't properly set up, and my source was not actually on my GOPATH. I was a bit confused because I was still getting used to the windows subsystem for linux. So I recommend double-checking your GOPATH and `pwd`.

**Comment by weichangdong** [comment]
i have same problem 

`$godep  path

Error: GO15VENDOREXPERIMENT is enabled and the vendor/ directory is not a valid Go workspace.`

and 
`$godep save

godep: dirty working tree (please commit changes): /code/go/src/github.com/astaxie/beego
godep: dirty working tree (please commit changes): /code/go/src/github.com/astaxie/beego/cache
godep: dirty working tree (please commit changes): /code/go/src/github.com/astaxie/beego/cache/memcache
godep: dirty working tree (please commit changes): /code/go/src/github.com/astaxie/beego/cache/redis
godep: dirty working tree (please commit changes): /code/go/src/github.com/astaxie/beego/config`

so many errors,why so many person  use it????  **use glide  is better than godep.**

**Comment by yyzybb537** [comment]
same issue here:
godep v79 (linux/amd64/go1.7.3)

**Comment by DnOberon** [comment]
same issue here

**Comment by xiaoyuzhoua** [comment]
the same issue with me

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
