### ISSUE TITLE
Cause error when work with project which doesn't use godep

### ISSUE THREAD

**Issue by lnshi** [tools/godep#539]
```
*"lsync/api".LsyncServer does not implement lsync.LsyncServer (wrong type for HealthCheck method)
    have HealthCheck("lsync/vendor/golang.org/x/net/context".Context, *microservice.Empty) (*microservice.HealthCheckRes, error)
    want HealthCheck("golang.org/x/net/context".Context, *microservice.Empty) (*microservice.HealthCheckRes, error)
```

See
**"lsync/vendor/golang.org/x/net/context".Context** vs **"golang.org/x/net/context".Context**, they are exactly same package, just because that I use `godep` so the path goes to `vender/...`, and the other project import it directly from `$GOPATH`, then the compiler report type error...

Any elegant way to deal with this?

**Comment by fiverrben** [comment]
I'm having a similar issue.
```ubuntu@box220:~/url_unfurl$ go version
go version go1.8.1 linux/amd64```

``` ubuntu@box220:~/url_unfurl$ godep version
godep v79 (linux/amd64/go1.8.1) ```

```
ubuntu@box220:~/url_unfurl$ make
godep restore ./...
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /home/ubuntu/url_unfurl
godep: [WARNING]:	$GOPATH: /home/ubuntu/.go_workspace:/usr/local/go_workspace
go build -o go_unfurl_service ./main/service.go
# command-line-arguments
main/service.go:27: cannot use router (type *"github.com/gin-gonic/gin".Engine) as type *"github.com/fiverr/url_unfurl/vendor/github.com/gin-gonic/gin".Engine in argument to service.Routes
make: *** [go_unfurl_service] Error 2
```

**Comment by jonathanfishner** [comment]
מה אני חווה פה ? 
@fiverrben

**Comment by huangjiuyuan** [comment]
I have encountered the same issue.

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
