### ISSUE TITLE
No command 'godep' found

### ISSUE THREAD

**Issue by connelevalsam** [tools/godep#544]
### Expected behavior
build dependencies.
### Actual behavior
No command 'godep' found, did you mean:
 Command 'godef' from package 'emboss' (universe)
 Command 'godex' from package 'golang-golang-x-tools' (universe)
godep: command not found
### Steps to reproduce behavior
create a project
do go get
set GOPATH to go/src/github.com/username/<project>
make <project> cd
then run godep save
### `godep version` output
No command 'godep' found, did you mean:
 Command 'godef' from package 'emboss' (universe)
 Command 'godex' from package 'golang-golang-x-tools' (universe)
godep: command not found
### `go version` output
go version go1.8.1 linux/amd64
### Contents of Godeps.json file

**Comment by NafisFaysal** [comment]
I think you have not set **GOBIN** correctly, so try export PATH=$GOPATH/bin:$PATH. I hope it will work out well.

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
