### ISSUE TITLE
update vendored deps to latest remote version

### ISSUE THREAD

**Issue by GlenDC** [tools/godep#545]
Expected a flag for the `godep update` command, or a separate command, which would easily allow me to update all dependencies in my vendor dir, to the latest _remote_ version, rather than the one in my `$GOPATH/src`dir. I'm OK if the `$GOPATH/src` packages are updated because of this action, but right now `godep update` only updates to the local packages, which is a bit annoying.

Perhaps this is out of scope for this project, but right now I'm solving this by having a python script which goes through all dependencies listed in the `Godeps.json` manifest, to update all dependencies one by one using `go get -u -d -v <DEP>`. While this works, it does feel like a big hack.

Obviously my hack would also work, in case we would have specified a specific version (range) in the godeps dir, as I'm currently not parsing that myself. So I guess if we would support this feature, we should respect such specified limitations as well.

It's because I try to update all dependencies to the latest stable/master version every 2 to 4 weeks, so that these incremental updates never get too big. And usually they contain nice bug fixes, without really breaking the public apis, so it's nice to do them quite regularly. However, would be great if I don't require some hacky script to do so.

Is this currently already possible with `godep`? If not, how would I start on supporting this, as I'm ok to put dev time in for this one myself.

### `godep version` output

```
$ godep version
godep v79 (darwin/amd64/go1.8)
```

### `go version` output

```
$ go version
go version go1.8 darwin/amd64
```

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
