### ISSUE TITLE
Add banner to README with link to golang/dep

### ISSUE THREAD

**Issue by ryan0x44** [tools/godep#546]
The number one search result for `godep` is this project, however the production-ready and soon-to-be-official tool [go dep](https://github.com/golang/dep) may be the actual project people are looking for. It would be awesome to place a banner at the top of the README with a note (and link) to disambiguate this :)

**Comment by nehagup** [comment]
I would like to make a PR for this.

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
