### ISSUE TITLE
Question about commit the vendor directory

### ISSUE THREAD

**Issue by iblancasa** [tools/godep#547]
I read this in the documentation:
> Read over the contents of vendor/ and make sure it looks reasonable. Then commit the Godeps/ and vendor/ directories to version control.

Why it is a good practice to commit the vendor directory? Usually this is something bad in other languages.

I didn't found information about this topic.

Thank you for your time.

**Comment by WrinklyNinja** [comment]
I'm wondering this too, since `godep restore` and `godep get` seem to have no problem downloading and installing the dependencies specified in `Godeps.json`. If we don't need offline builds, do we really need to commit the `vendor/` folder? Is something going to blow up in my face if I don't?

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
