### ISSUE TITLE
godep does not see vendored packages within thirdpadrty dependencies

### ISSUE THREAD

**Issue by srinarayanant** [tools/godep#556]
ISSUE : godep does not seem to see github.com/armon/go-radix vendored within hashicorp and gives out godep: Package (github.com/armon/go-radix) not found
`[root@centos7 src]# find /home -name *radix
/home/terraform-provider-vcloud-director-2/go/src/github.com/hashicorp/terraform/vendor/github.com/armon/go-radix`
### Expected behavior
 godep save to generate vendoring 
### Actual behavior
`[root@centos7 src]# godep save
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /home/terraform-provider-vcloud-director-2/go/src
godep: [WARNING]:	$GOPATH: /home/terraform-provider-vcloud-director-2/go/
godep: Package (github.com/armon/go-radix) not found
[root@centos7 src]# `
### Steps to reproduce behavior
Trying to setup vendoring for below project 
https://github.com/vmware/terraform-provider-vcloud-director 
`[root@centos7 src]# pwd
/home/terraform-provider-vcloud-director-2/go/src
[root@centos7 src]# env | grep GO
GOROOT=/opt/go
GOPATH=/home/terraform-provider-vcloud-director-2/go/`
### `godep version` output
godep v79 (linux/amd64/go1.9)

### `go version` output
go version go1.9 linux/amd64
### Contents of Godeps.json file

**Comment by freeformz** [comment]
I am closing this issue because the repo is going to be archived.
