### ISSUE TITLE
go subcommand should ensure that all dependencies are pinned

### ISSUE THREAD

**Issue by kr** [tools/godep#6]
If the package has a dependency not listed in Godeps, the go tool process run by `godep go` will use whatever version happens to be installed in the outer workspace, which could be different on various machines or at various times.

Command `godep go` should check for this and raise an error.

**Comment by freeformz** [comment]
I'm going to close this as it's pretty broad and I think a little outdated. As these things come up again (if they do) I'll open new issues/PRs.
