### ISSUE TITLE
godep restore seems broken: godep puts repository in detached head, and then tries to pull without specifying remote/branch

### ISSUE THREAD

**Issue by silasdavis** [tools/godep#60]
If you have previously used `godep restore` your git repositories will be in a detached head state, but godep tries to run git pull --ff-only, but this fails with 

```
From github.com:Foo/Bar
   19a3d36..c056ec2  master     -> origin/master
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>
```

Furthermore if you try and work with
```bash
export GOPATH=$(godep path)
godep restore
```

Nothing really works because the files under _workspace directory are not in their original git repositories so when godep tries:

```bash
git checkout 19a3d368eacde07ff631578ca7de3ec1d5e3a2cd
fatal: reference is not a tree: 19a3d368eacde07ff631578ca7de3ec1d5e3a2cd
```

These seem pretty fundamental so I don't really understand how this hasn't come up before - perhaps I'm missing something, but I don't see how restore can work unless you have synchronised your repositories manually...

**Comment by mbforbes** [comment]
:thumbsup: Same problem here

**Comment by pbdeuchler** [comment]
:+1: same problem here

**Comment by kjsteuer** [comment]
:+1: same problem here. Any known workarounds?

**Comment by schickling** [comment]
+1

**Comment by morpheyesh** [comment]
same here...solution?

**Comment by bhcleek** [comment]
We recently ran into this problem and were able to resolve it. In our case, the problem stemmed from the migration of the Go tools (golang.org/x/*) repositories to Git in December. The SHAs stored in Godeps.json were Mercurial SHAs, which of course don't exist in the Git repositories. Once we updated the SHAs to their proper Git counterparts, all was well.

**Comment by nathanjordan** [comment]
Also having this problem, haven't had much luck resolving the underlying issue, but switching the revisions to <code>master</code> instead of the sha at least let the command succeed.

**Comment by freeformz** [comment]
For those of you having this problem:

1) is it with golang switch to golang.org/x / github? If so you will likely need to update your deps in a brute source kinda way as per @bhcleek 's suggetions. I recently had to do something similar for https://github.com/sclasen/swfsm/pull/60

2) Can you provide a repeatable test case?

**Comment by danielalves** [comment]
For those having this problem on Travis, a workaround that worked for me was to follow [Travis notes on godep](http://docs.travis-ci.com/user/languages/go/#godep-support) and not calling `godep restore` before tests. This will not be a problem since GOPATH will be prefixed with `${TRAVIS_BUILD_DIR}/Godeps/_workspace`. But, for this to work, you must be versioning your vendor code (the `_workspace` dir) in your project, which is a [Godep recommendation](https://github.com/tools/godep#getting-started) anyway). Hope it helps.

**Comment by freeformz** [comment]
Travis shouldn't do that as that's an implementation detail of godep and may break in the future.

**Comment by pdxjohnny** [comment]
:thumbsup: Same problem here

**Comment by freeformz** [comment]
@pdxjohnny This works fine for me:

```console
$ go get -u go get -u github.com/authit/crypto
$ cd $GOPATH/src/github.com/authit/crypto
$ godep restore
```

I would try nuking `$GOPATH/src/github.com/spf13/cobra` and try `godep restore` again.

BTW: `godep restore` isn't really necessary unless you don't want to wrap your `go` commands with `godep`. I would also encourage the authors of the package to rewrite their deps.
