### ISSUE TITLE
godep save should not update existing packages by default

### ISSUE THREAD

**Issue by kr** [tools/godep#65]
By analogy with 'go get'.

Running `godep save` with no flags should keep already-saved dependencies as they are, and only add missing packages. Running `godep save -u` will then be necessary to update versions.

**Comment by drewwells** [comment]
Should `godep save` automatically update dependencies? If `godep save` is the exact opposite of `godep restore`, I would expect save to update vendored packages from the newer ones in `gopath`. It appears only `godep update ./...` does this, or `rm -rf Godeps; godep save ./...`
