### ISSUE TITLE
godep save ./... fails when a package imports another package in the same repo

### ISSUE THREAD

**Issue by josharian** [tools/godep#69]
### Reproduce

``` bash
go get github.com/josharian/godepbug
cd $GOPATH/src/github.com/josharian/godepbug
go build ./...  # sanity check
godep save ./...  # initial save succeeds
git add .
git commit -m "Vendor"
godep save ./...  # save after commit fails
```
### Result

``` bash
godep: dirty working tree: $GOPATH/src/github.com/josharian/godepbug
godep: error loading dependencies
```
### Diagnosis

`github.com/josharian/godepbug` contains a package (`subpkg`) that references another package in the same repo. (This is not uncommon -- one package has an interface, another package has a struct that satisfies it.) When running `godep save ./...`, the act of updating `Godeps` for one of the packages puts the local tree in a dirty state, which causes the `godep save` for the other package to fail.

Running just `godep save` is not an alternative, since it does not necessarily pick up all dependencies from all packages.

A fix to #53 will likely fix this as well, since it will likely involve changing `Godeps` after all preliminary work is done. Wanted to file this as well, though, so that it was on the radar.
### Workaround

``` bash
rm -rf Godeps
git add --all .
git commit -m "Unvendor"
godep save ./...
git add .
git commit -m "Vendor"
git rebase -i HEAD^2
```

**Comment by kamal-github** [comment]
after godep save ./..., how to put build in vendor/ directory?

**Comment by freeformz** [comment]
@kamal-github Please open a new issue describing the problem and don't comment on an old issue.
