### ISSUE TITLE
Managing local changes

### ISSUE THREAD

**Issue by rnapier** [tools/godep#79]
Do you have a workflow in mind for how to deal with local changes? In particular, I have this kind of situation:
- There's some opensource project I use
- I godep it
- Now I want to fix it somehow
- I do… what?
- I issue a pull request
- It's accepted and merged
- I do… what?

I know this is a broader Go problem, but I'm thinking about it in terms of how I work with (the anticipated) "godep save -r" and update.

I've been doing this a bit by hand, but basically "… what?" looks like "I break the build for awhile and push random untested stuff up to my github fork's master which hopefully no one is following." In particular, my problem is that I need these things to work cross-platform, so I'd really like to test it out on multiple machines before I push up to my fork.

Here's my half-baked idea of how it might work:
- go get X
- godep save -r X (rewrites everything)
- Hey, I need a change to X
- I fork X
- godep restore -r X (rewrites everything to use the non-Godeps version; does it delete it out of Godeps?)
- ... at this point I really want a command that changes "github.com/x/y" to "github.com/myfork/y"
- I work in the non-Godeps copy of my fork. I branch. I commit things. I throw thing between machines without pushing to GitHub. Finally there is joy.
- I push to my fork on GitHub. I open a pull request.
- godep save -r X (rewrites github/myfork/y back into Godeps)
- At some point the pull request is accepted
- ... I run some command that switches my Godep from the fork to the original ...

Am I overthinking this? Is there a simpler approach?

**Comment by glasser** [comment]
However, as long as you have a fork of a package, nobody else will be able to run `godep restore` because nothing in your Godeps.json teaches them in what repository they will find the Rev in question, right?

**Comment by kr** [comment]
> However, as long as you have a fork of a package, nobody else will be able to run godep restore because nothing in your Godeps.json teaches them in what repository they will find the Rev in question, right?

That's right. I had been considering adding a field to Godeps.json to handle this case for some time. This issue is mentioned in https://github.com/kardianos/vendor-spec/issues/6 and #207 that I can find.

**Comment by zhouhaibing089** [comment]
two years later, nothing changed?
