### ISSUE TITLE
godep get doesn't get rev:

### ISSUE THREAD

**Issue by luck02** [tools/godep#80]
We are relying on a number of external libaries.

When my godep specifies:
		{
			"ImportPath": "github.com/dustin/go-humanize",
			"Rev": "152bd44907e2ce04ecfb87d783ebf98160ada012"
		},

In my gopath I'm seeing that go-humanize is on master (Which is about 3 commits ahead of 'rev'

I've confirmed my commit exists by:
app:~/go/src/github.com/dustin/go-humanize$ git cat-file -t "152bd44907e2ce04ecfb87d783ebf98160ada012"
commit

So the commit exists, however I'm seeing master in my gopath which is very problematic.  We have many libraries and their all on master.

I can manually set to my target commit with:
git checkout "152bd44907e2ce04ecfb87d783ebf98160ada012"

I get a detached head state, but that's fine.

Thank you.

PS: "'s added to sha's to prevent them from being interpreted as godep commits by github

**Comment by zenlinTechnofreak** [comment]
@luck02 @shurcooL I also met the same problem.
When we wirte specified Rev into Godeps.json, How can I get the right version of the imported godeps.
I have tried  go get -d in the newest version of godep tool, but it did not do it, it just pull the newest version of the import lib to the $GOPATH, but not the specfied version.

Can anyone help me to know that?thanks very much.

**Comment by freeformz** [comment]
Godep no longer works this way and we make the following assumptions:

1. godep save was used and the `_workspace` was committed to git.
1. If the dependencies **were** saved with the `-r` flag, the `go` tool itself w/o needing to modify `$GOPATH` or wrapping commands with `godep` can be used to `go install` the project. This is the recommended way to use `godep` and you will have the least amount of problems using it this way.
1. If the dependencies were **NOT** saved with the `-r` flag, then **one** of two things **must** happen:
    1. `go` tool commands to build code must be wrapped with `godep`, so `godep go install` and the like. This happens to re-exec the go tool with a modified `$GOPATH`, but this is just an implementation detail, subject to change at whim (although it is unlikely to).
    1. `godep restore` must be run before using the `go` tool to build code. This modifies the copies of the dependencies in your `$GOPATH` by checking out the `Rev`s for each dependency in the proper `$GOPATH` location. This is sub-optimal.

I hope this help clarify things. I'll try to improve the docs.

PS: rewrites do not work with the Go15 `vendor/` experiment further complicating things, but this is be reflected in the docs already.
