### ISSUE TITLE
Godep saving github dependencies saves them as submodules?

### ISSUE THREAD

**Issue by shuhaowu** [tools/godep#83]
When I use godep save, i see a git repository getting cloned. My repository is a submodule. Does that mean a submodule is suppose to be included in my master repo? That means I have to do submodule init?

If this is the case, why am I even using godep as I can just use a vendor directory with git submodules on its own without having to think about godep.

**Comment by freeformz** [comment]
godep doesn't do anything with submodules AFAIK. Is this reproducible with the current version of godep and can a publicly accessible reproducer be made available?
