### ISSUE TITLE
save misses dependencies under build constraints

### ISSUE THREAD

**Issue by kr** [tools/godep#84]
If a dependency is under build constraints that are not locally satisfied (for example, a foo_windows.go file on a unix machine), then godep save won't pick it up.

**Comment by jzelinskie** [comment]
I believe that I created a duplicate issue at #161. However, some new information has come to light: if a library is using the `!` operator in a build line (i.e. `// +build !linux`),  even the `-tags` parameter on `go list` won't help.

**Comment by freeformz** [comment]
Closing in favor of #271.
